### ISSUE TITLE
Implement unconstrained parameterization

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#10]
Change the constrained parameterization to an unconstrained one and update the analytic derivatives.

**Comment by jeff-regier** [comment]
I need this functionality for SGVB too. It's not debugged or fully implemented yet, but I have a version of it in the "sgvb" branch. https://github.com/jeff-regier/Celeste.jl/blob/sgvb/src/Transform.jl

**Comment by rgiordan** [comment]
Ok.  Just in case you didn't see it, the free_transform in the master branch has all of these except for the mu "box constraints"  (it also uses a (mean, variance) parameterization of the gamma distribution).  FYI, I was getting problems with NLOpt and the free transform, though.

The transform remake looks cool.  Do you want to maybe merge that with the master separately from the sgd stuff?

**Comment by jeff-regier** [comment]
I finished debugging and testing the version of "Transform.jl" in the "sgvb" branch. It supports arbitrary `D` and arbitrary `Ia`. The free_transform code just works for `D` = `Ia` = 2, right?

The version of Transform.jl in sgvb, however, is for a somewhat different model than the master branch uses---all quantities are random. Probably better to put off merging it into master (or to manually copy any lines that are helpful).

**Comment by rgiordan** [comment]
> I finished debugging and testing the version of "Transform.jl" in the
> "sgvb" branch. It supports arbitrary D and arbitrary Ia. The
> free_transform code just works for D = Ia = 2, right?

Yes, that's right.  Making it work for general D and Ia wouldn't be too
much work, though, and not worth doing a big tricky merge just for that.

**Comment by rgiordan** [comment]
Done in https://github.com/jeff-regier/Celeste.jl/pull/51
