### ISSUE TITLE
Parallelize ELBO calculation across pixels ?

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#100]

**Comment by rgiordan** [comment]
It occurred to me that another parallelization strategy could be to define a task as a single trust region step.  If the optimization hasn't converged yet, then the step-taking task would add another task to the queue.  In addition to the image and model parameters, tasks would also have to save some intermediate optimization information, but I made a point of factorizing all the needed information into a single type in the trust region code.

**Comment by kpamnany** [comment]
We've decided to parallelize at source level.
