### ISSUE TITLE
script to pre-process one frame

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#114]
Through pre-processing, transform an SDSS frame into "tasks", 1 per known astronomical object. The tasks are bundled into JLD files. Each frame gets its own JLD file. For each astronomical object, the corresponding task contains everything necessary for processing that object, including
- the tiles/pixels relevant to it
- the parameters for this astronomical object from an existing SDSS catalog (for initialization)
- the catalog entries for all neighboring astronomical objects (treated as fixed, for now)
- the point spread functions for the tiles
- the gain and calibration constants for the tiles
- local linearized world coordinates for each tile / subimage

Neighboring astronomical objects are those that may contribute photons to any of the included tiles.

A new `Task` immutable should be declared in `CelesteTypes.jl`.

Sample usage:

```
./run_celeste.jl --stage preprocess --run  3900 --camcol 4 --field 829
```

Input should be fetched from NERSC, e.g.

```
/global/projecta/projectdirs/sdss/data/sdss/dr8/boss/photoObj/301/1000/1
```

We should be able to remove all the scripts below once this issue is closed.
- staging/download_fits_files.py
- staging/images_for_ra_dec.py
- staging/preprocess_image.jl
- staging/read_window_flist.jl
- get_astrometry_psf.py
- get_tractor_images.py

**Comment by kbarbary** [comment]
We've significantly reduced the runtime of preprocessing with #119 and #121 and hopefully will continue to do that with #120. Is it still necessary to run preprocessing as a separate step? Having to serialize all relevant structures to disk and back adds significant mental and runtime overhead; I hope we can avoid it if at all possible.

**Comment by jeff-regier** [comment]
Sure, we can merge the preprocessing stage and the processing. Probably whatever design lets us close issue #116 soonest is best.

**Comment by rgiordan** [comment]
That sounds good to me!  Those pre-processing improvements look pretty
sweet, and the less data wrangling the better.

**Comment by kbarbary** [comment]
Great. I'm going to close this and focus on #115 and #116. We can reopen if we decide that preprocessing is actually necessary for some reason.
