### ISSUE TITLE
fit PSF with least squares

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#120]
rather than using GaussianMixtures.jl to perform EM

**Comment by kbarbary** [comment]
It seems like the run-time performance of GaussianMixtures is not actually that bad, but the compile performance is a killer. For example, after loading a `RawPSFComponents` and running

``` julia
@time psf_gmm, scale = fit_psf_gaussians(raw_psf)
@time psf_gmm, scale = fit_psf_gaussians(raw_psf)
```

I see

``` julia
 17.973990 seconds (35.54 M allocations: 2.139 GB, 2.78% gc time)
  0.201622 seconds (1.69 M allocations: 71.089 MB, 9.68% gc time)
```

I would guess that this could be improved in GaussianMixtures. (It is already using precompilation though.)

**Comment by jeff-regier** [comment]
Yep, this issue is more about fitting the PSF well rather than speed. It's probably easiest for @rgiordan to work on this since he wrote the PSF code.

**Comment by kbarbary** [comment]
Ah, I see. Well, hopefully this will also give us a bit more control over performance and we can have the best of both worlds.

**Comment by jeff-regier** [comment]
Getting rid of GaussianMixtures will also help us migrate to Julia 0.5. I'm not sure how to work though those errors otherwise. @rgiordan -- Are you / will you work on this?

**Comment by rgiordan** [comment]
Yes, I will work on this after the parameter bounds fix.

**Comment by rgiordan** [comment]
Any objections to taking Celeste down to two PSF components (per Dustin's having done so for DECaLS)?

**Comment by jeff-regier** [comment]
Up to you. I'm a little concerned about the fit not working well with 3
components, since we know Dustin did it that way, and that's the way that
got good results before. But a 50% speed up would be nice, and since
neither 2 or 3 are great we might as well take the speed up

**Comment by rgiordan** [comment]
Cool.  When I make this change I'll set it up so the number of PSF components is not hard-coded, so it will be easier to go back and forth if needed.

**Comment by rgiordan** [comment]
Another reason not to worry is that two components fit with LS are still a better fit (in terms of LS) than three fit with EM.

**Comment by rgiordan** [comment]
@jeff-regier , you use `GaussianMixtures` in `gen_priors.jl` (line 66).  Shall we just comment that out for now to get rid of the package quickly?

**Comment by rgiordan** [comment]
Sorry, I take that back -- I think we can leave it in and simply remove `GaussianMixtures` from `REQUIRE` since `gen_priors.jl` is in bin.  It's bad form, but not too bad.

**Comment by jeff-regier** [comment]
Yes, let's do that. We'll figure out what to do with gen_priors.jl another
time

**Comment by rgiordan** [comment]
This is probably still too slow -- around a second to a second and a half per source on my computer.  About half the time is spent initializing  `BvnComponent`s, which I currently need to do for every pixel since it's immutable.  @jeff-regier , what do you think about making `BvnComponent` mutable?  What are the downsides?

**Comment by jeff-regier** [comment]
I make things immutable by default but mutating it is going to make it go
noticeably faster, we should do that.

Why do you initialize BvnComponents every pixel? Do you mean that you
initialize it for every iteration of the optimization?

**Comment by rgiordan** [comment]
Oh man, I did a dumb thing.  Yes, I can pull that out of the loop.  That will probably just fix this problem.  Sorry

**Comment by rgiordan** [comment]
It's down to about 0.4 seconds per source.  Maybe re-scaling will make it faster, but otherwise this might have to do for now.

**Comment by rgiordan** [comment]
This is fast enough now, I think.
