### ISSUE TITLE
Make sure all the necessary sources are included

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#130]
@kbarbary , the way `celeste.jl` divides up the celestial objects isn't correct -- you can't partition the catalog entries by slicing the array.  If two objects are in the same tile, then you need to make sure both the objects are in the model params object.

One correct way to do it is something like the block of code in `limit_to_object_data` where I populate the `relevant_sources` vector.

**Comment by kbarbary** [comment]
Good to know. The easy fix is to take out the partitioning, or just not use `--part=` on the command line. I'll keep this in mind when working on #123.
