### ISSUE TITLE
Dtree.jl for source level parallelism

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#133]
Source-level parallelism using @kpamnany 's `Dtree.jl` library on Cori.

A bash script to run dtree:

```
#!/bin/bash -l

#SBATCH --partition=debug
#SBATCH --nodes=64
#SBATCH --ntasks-per-node=2
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=16
#SBATCH --job-name=dtreebench
#SBATCH --time=00:10:00

export OMP_NUM_THREADS=16
export JULIA_NUM_THREADS=16
export I_MPI_PMI_LIBRARY=/opt/slurm/default/lib/libpmi.so
srun -n 128 -c 16 /global/homes/k/kpamnany/julia/julia /global/homes/k/kpamnany/.julia/v0.5/Dtree/test/dtreebench.jl
```

Save that in `dtreebench.sl` and run it from the login node with:

```
> sbatch dtreebench.sl
```

**Comment by jeff-regier** [comment]
@rgiordan -- Will we still need `CelesteCluster.jl`, `submit_darrays_to_cluster.sh`, `submit_process_image_to_cluster.sh`, and `distributed_benchmark.jl` once this issue is done?  (Can they be deleted along with the PR that closes this issue?)

**Comment by kbarbary** [comment]
Yeah I was wondering about `CelesteCluster.jl` when working on submodules.
