### ISSUE TITLE
Scalable Newton's method

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#136]
On each node of the supercomputer, we may want to run Newton's method on all the sources in a roughly field-size region of the sky, rather than optimizing each source in isolation. That would give us more work to divide among the threads on each node.

We'd want to store the Hessian as a sparse matrix. Probably the built-in sparse matrix format would be fast enough, even though it ignores the block structure. Rather than inverting it, we'd use conjugate gradient from IterativeSolvers.jl to right multiply the inverse Hessian by a vector.

**Comment by rgiordan** [comment]
Just FYI, the current trust region method (which I took out of Nocedal and Wright) requires repeated inverse hessian-gradient products of (H + \lambda I) for a range of candidate lambda, as well as an eigenvalue decomposition.

I know there's work being done on scalable trust region methods (I don't know much about it), but going to a much larger Hessian may be a bit more complicated than just dropping a CG algorithm into the current code.

**Comment by jeff-regier** [comment]
Could we use just the top few eigenvalues and corresponding eigenvectors, or do we need the whole EVD? The latter could be a problem. I'm less worried about the hessian-gradient products because cg really is fast, and the run time now is dominated by evaluating the objective function, not the optimization. I'll take a look at Nocedal and Wright.

What articles have you seen about scalable trust region methods? The sparse hessian with O(n) fill might make our problem quite different (and easier) than the cases addressed in the literature.

**Comment by rgiordan** [comment]
You actually need the minimum eigenvalue, iirc.  We should chat about this
in person sometime.  I think it's certainly possible with the whole sparse
Hessian, but if the only reason to do it is to use threads, then I'm not
sure it will be worth it.

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment]
Finding the minimum eigenvalue in linear time shouldn't be a big deal: inverse iterations and lanzos method. Let's find time to discuss this in person if @kpamnany reports that pixel-level parallelism doesn't work well.

**Comment by rgiordan** [comment]
What about sources that don't interact with other sources but whose sub
problems converge quickly?  Will you keep evaluating their Hessians while
the slowest source converges?

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment]
We may want to partition the light sources into connected components during preprocessing, where sources are "connected" if they interact. The larger components may still benefit from multithreaded Newton's method
