### ISSUE TITLE
add quasars to the model

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#14]
The objects at the following ra-dec coordinates are quasars in our dataset of "stamps".
- 5.0820, 0.9728
- 5.0075, 0.9102
- 5.2982, 0.0274
- 5.6378, 0.1212
- 5.0161, 0.1945
- 5.1439, 0.0885

**Comment by rgiordan** [comment]
NB: #103 implemented support for the necessary multi-dimensional simplexes.

**Comment by rgiordan** [comment]
I'm confused -- did quasars get added?

**Comment by jeff-regier** [comment]
Yes, but there are still just two types of light sources: point sources (i=1) and galaxies (i=2). Point sources includes both quasars and stars. That's reflected in the new prior. (the `.jld` file) in the `cfg` directory.
