### ISSUE TITLE
choose_patch_radius() is too conservative in some cases

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#142]
An example is 

```
run = "004263"
camcol = "5"
field = "0117"
objid = "1237663784734359803"
```

**Comment by jeff-regier** [comment]
Did this get fixed in the recent PRs?

**Comment by rgiordan** [comment]
No, it didn't.  I think it's not a showstopper.  It would just be nice to
be more careful about it at some later point.

**Comment by jeff-regier** [comment]
It's wildly conservative in some cases, I think. I added in the upper bound below to keep individual sources from allocating huge amounts of memory, e.g. objid 1237662224072638610, but it's still probably way too conservative usually. 

```
        radii_map[s] = min(radii_map[s], 25) # hack: upper bound radius at 25 arc seconds
```

**Comment by jeff-regier** [comment]
We're going to switch soon (issue #157) to initializing based on the images rather than based on an existing catalog. The function `choose_patch_radius()` won't be around much longer.
