### ISSUE TITLE
Initialize without using existing catalogs

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#157]

**Comment by jeff-regier** [comment]
We probably want to implement a source-detection method like this one:
http://cosmo.nyu.edu/hogg/research/2014/05/02/coadd.pdf

Or if not, we at least want to be familiar with the method in the paper.

**Comment by gostevehoward** [comment]
Thanks, I'll take a look at that paper.

**Comment by jeff-regier** [comment]
If after doing the match filter initialization we think there's room for improvement, we may want to consider doing something with convolutional neural networks. I think that could work really well  But it's possible just finding all the peaks after applying the matched filter will solve the problem.

**Comment by jeff-regier** [comment]
I wrote some code awhile ago that implements the matched filter idea for finding peaks. I don't know if this is necessarily what we want to do, but it may be worth looking over.

https://github.com/jeff-regier/Celeste.jl/blob/a2199d497b3fc0ef57c3deab93b405368081578c/src/ModelInit.jl#L91-L158
