### ISSUE TITLE
y coordinates out of bounds

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#167]
Is this a bug?

```
./celeste.jl infer-nersc 0.5 0.51 0.5 0.51 .
...
20-Mar 15:41:53:INFO:root:reading field (4263,5,119)
20-Mar 15:41:54:INFO:root:reading field (4263,5,120)
20-Mar 15:41:56:INFO:root:reading field (4930,5,395)
ERROR: LoadError: y coordinates out of bounds
 in interp_sky at /global/homes/j/jregier/.julia/v0.4/Celeste/src/SDSSIO.jl:38
 in read_sky at /global/homes/j/jregier/.julia/v0.4/Celeste/src/SDSSIO.jl:86
 in read_frame at /global/homes/j/jregier/.julia/v0.4/Celeste/src/SDSSIO.jl:105
 in read_sdss_field at /global/homes/j/jregier/.julia/v0.4/Celeste/src/SkyImages.jl:244
 in infer at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:134
 in infer_nersc at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:332
 in main at /global/u2/j/jregier/Celeste/bin/celeste.jl:36
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /global/u2/j/jregier/Celeste/bin/celeste.jl, in expression starting on line 42
```

**Comment by kbarbary** [comment]
This is a check that the we're not interpolating outside the bounds where the sky is defined.

I'll have a look at the specific file later tonight (I'm headed to the airport right now). Its possible that it's a bug. Alternatively, SDSS intends that we should extrapolate past the defined grid. (Perhaps just by a pixel or two.)

**Comment by kbarbary** [comment]
The problem with this file is that the y coordinates in the sky go up to `186.56`, but the sky array has size `(256, 171)`. If I understand the SDSS sky scheme, the coordinates should be within the size of the sky array.

I could change `sky_interp` to extrapolate using a constant value, but it's not clear that this is not a problem with the file itself. Any SDSS documentation on interpreting the sky representation?

**Comment by rgiordan** [comment]
The sky interpolation is documented in the frame FITS file:

http://data.sdss3.org/datamodel/files/BOSS_PHOTOOBJ/frames/RERUN/RUN/CAMCOL/frame.html

It says "There are cases at the end of runs where the y-size of ALLSKY is
less than 186, which requires one to extrapolate off the end of the
ALLSKYimage in the y-direction when using XINTERP and YINTERP. This
extrapolation should be a constant extrapolation (not linear)."

**Comment by kbarbary** [comment]
Perfect, thanks Ryan! I'll fix the code appropriately, but maybe not until
tomorrow.
