### ISSUE TITLE
excessive PSF fitting

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#178]
Even though the bounding box specified is small (just 4 sources), a PSF is being fit a huge number of times...perhaps for every primary source?

```
$ ./celeste.jl --logging=DEBUG infer-nersc 200.15 200.17 38.15 38.17

23-Mar 09:19:23:INFO:root:1571 primary sources
23-Mar 09:19:23:INFO:root:876 primary sources after MIN_FLUX cut
23-Mar 09:19:23:INFO:root:processing 4 sources in RA/Dec range
...
```

The program hasn't finished running but it looks like it's already fit 74 PSFs:

```
jregier@cori05~/Celeste/bin $ grep "Iter 1$" run30 | wc -l
74
```

Here `run30` contains the output. The regex `Iter 1$` occurs whenever a new optimization is begun. 74 seems way too high.

**Comment by kbarbary** [comment]
Isn't the PSF fit separately for each image for each source? So you would expect more than 4 \* Nimages PSF fits.

**Comment by jeff-regier** [comment]
You're right, thanks, I didn't consider how many run-camcol-fields cover this region. There are 4 fields, each has 5 bands, and there are 4 sources. So up to 80 PSF fits are possible, if all 4 sources are imaged in all 4 fields.
