### ISSUE TITLE
Excessive memory utilization

### ISSUE THREAD

**Issue by kpamnany** [jeff-regier/Celeste.jl#180]
The instrumented `distributed` branch:

```
$ export OMP_NUM_THREADS=1
$ export JULIA_NUM_THREADS=1
$ bin/celeste.jl infer-nersc 200 200.02 38.1 38.13 $SCRATCH
timing (1 inferences):
infer avg: 181.222810705
field ids avg: 0.770702978
dump output avg: 3.529306283
read primary avg: 1.380862115
filter catalog avg: 0.027401061
read images avg: 6.666787441
init model params avg: 5.203631448
psf: 3.708009111
fit: 30.036252533200003 (for 5 fits)
181.864038 seconds (764.54 M allocations: 60.215 GB, 20.84% gc time)
```

This will scale poorly because GC is serial.

**Comment by rgiordan** [comment]
I'll run a profiler to see where the problem might be.

**Comment by rgiordan** [comment]
There were a couple small easy changes which I put in https://github.com/jeff-regier/Celeste.jl/pull/184.  I think saving more memory allocation will require putting source brightness and bvn caches in elbo_vars and pulling elbo_vars out of ElboDeriv.jl and into the optimization type.  The result will be allocating all the memory for a source once at the beginning of the optimization step.  That'll be a bit of work and take some time to do, so how necessary do you think that is, @kpamnany ?

**Comment by kpamnany** [comment]
#184 doesn't appear to have helped. On the `distributed` branch, yesterday I saw:

```
[1] 472.067230 seconds (1.58 G allocations: 136.034 GB, 31.51% gc time)
```

This is the largest percentage I've seen, but it is well over 20% of runtime, every time. I just ran it on `master`:
`
605.717740 seconds (1.58 G allocations: 136.645 GB, 20.36% gc time)
`
This final run was with `--track-allocation=user` (which is probably why it is much slower) and copied all the `.mem` files to `/global/cscratch1/sd/kpamnany/celeste.mem/`.

**Comment by kpamnany** [comment]
Much improved by PR #199!

```
[1]  83.320145 seconds (112.69 M allocations: 11.352 GB, 4.80% gc time)
```
