### ISSUE TITLE
star position is off

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#186]
Many objects' positions seem to be off. For the object with objid `1237663784734491542`, for example, Celeste reports its ra/dec as 0.556922/0.624469, but primary finds it at 0.557017/0.624494 . (Why does it move away from the initialization? )

The [Sky Server Navigation Tool](http://skyserver.sdss.org/dr12/en/tools/chart/navi.aspx) suggests Primary (and Photo on the coadd catalog) are right, and that Celeste is pretty far off. (But I don't know exactly how that web tool accounts for the PSF.) @rgiordan  Do you have time to look into this? There are other problems with the scores too, and I could use help getting to the bottom of this one. Is it strange the optimizer converges here in just 2 steps?

With PR #185, these results can be recreated with two commands:

```
./celeste.jl --logging=DEBUG infer-object 4263 5 119 1237663784734491542 .

./celeste.jl --logging=DEBUG score-object 4263 5 119 1237663784734491542 .  /global/homes/j/jregier/coadd_catalog_from_casjobs.fit 
```

**Comment by rgiordan** [comment]
Yes, I can try to take a look at this.  I have some 205B to do but I'll
prioritize this when it's done.

**Comment by rgiordan** [comment]
This is a very dim object and I strongly suspect that the trim_source_tiles
function is being too conservative when it eliminates pixels.

I can think of two solutions, and we may want a combination.  One is to
make sure that at least a certain radius of pixels around the original
object are selected.  Another is to set the noise_fraction to be a function
of the brightness of the object.  The former is easier and probably better
-- let me put together a PR.

Ryan

**Comment by rgiordan** [comment]
Fixed in https://github.com/jeff-regier/Celeste.jl/pull/187
