### ISSUE TITLE
flux way too high

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#189]
For objid 1237663784734490878 (frame 4263, run 5, field 119), the flux we predict is _way_ too high. I've seen this kind of thing happen before when we also predict that a galaxy is much larger than it actual is, but that isn't the case here.

Coadd and Celeste predict this object is a galaxy (Primary predicts "star" -- ha!). We claim the r band flux (if it's a galaxy) is 6959 nanomaggies but Coadd says only 522 nanomaggies.

http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237663277928022167

Some of the flags suggest this detection is saturated, but if anything, I'd expect Celeste to underestimate the brightness in that case. (Also, if it's very saturated, I'd expect this object to get filtered out in the coadd query to casjobs.) There's also a cosmic ray flag set but I don't see it.

@kbarbary @rgiordan  Any thoughts on what's happening here? Sources like this are really screwing up our scores.

**Comment by rgiordan** [comment]
I'm taking a look.

**Comment by jeff-regier** [comment]
The way brightness was calculated for Coadd was a bit off. (Only the more prominent component, dev vs exp, was being used, but they should be summed.) So the true Coadd flux is 928, not 522. Still, much smaller than 6959.

**Comment by rgiordan** [comment]
Strangely, I'm seeing Celeste doing something that looks like the right thing.  For example, in band three, Celeste's residual is much better than the catalog's residual (see images; also, the total absolute residual is smaller for Celeste).

![catalog_residual](https://cloud.githubusercontent.com/assets/4494910/14159109/f23f7e7a-f688-11e5-9d0b-cae82bfa805d.png)
![celeste_residual](https://cloud.githubusercontent.com/assets/4494910/14159110/f2412d42-f688-11e5-814a-527850adcffa.png)

However, I'll also note that Celeste is not terminating NM in fifty iterations, so that might also be a problem.  I'll keep looking.

**Comment by rgiordan** [comment]
@jeff-regier ,

**Comment by rgiordan** [comment]
Sorry, hit the wrong button.

**Comment by rgiordan** [comment]
In this run / camcol /field, Celeste's very bright fit looks better in every band than the catalog.  Let me take a look at the coadds to see what's wrong.

**Comment by rgiordan** [comment]
@jeff-regier , after taking a quick look at the infer stuff in `api.jl`, I think you could save me some time by telling me how to get the coadd images and catalogs for a particular object id.

**Comment by jeff-regier** [comment]
Sure. The coadd catalogs from casjobs. (You can log in with your google
account.)

http://skyserver.sdss.org/casjobs/login.aspx

An sample SQL I use to load the catalogs is in our "doc" directory. It's
casjobs_query.sql

I haven't used the coadd images before. They're runs #106 and #206. They
might just be stored with the other image data.

**Comment by jeff-regier** [comment]
According to Dustin the error is with Coadd: the detection is saturated but it's saturated flag is not set. We need to filter out objects like this. I think the way to do this is to modify `load_primary` in `api.jl` so that it doesn't load saturated sources, or other sources with bad flags set. That way they'll be omitted for scoring latter in the code, when a match can't be found.

@kbarbary Do you have any time to work on this issue? I may be in a better position to fix #191 because I had the same problem awhile ago.

**Comment by kbarbary** [comment]
This seems non-essential for SC16 and I'm not going to be able to work on Celeste after that.

**Comment by jeff-regier** [comment]
We've got to report some scientific results in the paper too. We don't need amazing performance, but we do need to maintain our lead over current system. I can do it though if you don't have time.

**Comment by jeff-regier** [comment]
Dustin confirms that the problem is with Coadd, as its saturated flag isn't set when it should be. You might think we could nonetheless exclude saturated sources based on Primary's saturated flag, but this flag turns out to be set way too often, and furthermore, excluding the sources Primary flags as saturated doesn't turn out to help Celeste's performance relative to Primary. I think we can get a bit more use from the Coadd catalog, but soon it may make sense to think about the problem as strictly unsupervised.
