### ISSUE TITLE
inaccurate galaxy angles

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#191]
Celeste appears to not be finding galaxy's angles very accurately. (Or else something is wrong with the score function.) Celeste is currently off by 45 degrees on average, while primary (and Celeste in the ICML paper) is off by about 20 degrees. (Random guessing is 90 degrees off.)

Consider objid = 1237663784734490990. It's a bright object. It's axis ratio is low enough that angle means something. (With an axis ratio of 1, the galaxy appears as a circle, and angle doesn't have a meaning.) In the sky navigator tool (coordinates: 0.537991, 0.553257), it's obvious which direction it lies. Both Primary and Photo determine that this galaxy is about 175 degrees in angle. Celeste returns 85 degrees.

**Comment by rgiordan** [comment]
I'll bet we're 90 degress off of the catalog's notion of "angle" in Celeste.  Check out these images from that 1237663784734490990 as Celeste sees them.  I will look into this.

![screenshot from 2016-03-31 15-05-52](https://cloud.githubusercontent.com/assets/4494910/14192393/495c9ce6-f752-11e5-94ed-40ee7f96f961.png)

Wouldn't random guessing be forty-five degrees off?

**Comment by jeff-regier** [comment]
You're right, 45 degrees off is random. 90 is the most possible.

And yeah I'm pretty sure it's 90 off, with perhaps one computing angles
clockwise and the other counterclockwise.

The problem may affect initialization too, not just scoring... I notice
some really big Newton steps away from the initial value, suggesting the
initialization could be off

**Comment by rgiordan** [comment]
Yes, looking at this catalog image, it's clear that the initialization is off by 90 degrees.  Fixing this could result in a modest speedup, too.

**Comment by rgiordan** [comment]
Here's the logic that has apparently been in Celeste for a while:

```
        # use tractor convention of defining phi as -1 * the phi catalog
        fits_phi *= -1.0

        phi90 = 90 - fits_phi
        phi90 -= floor(phi90 / 180) * 180
        phi90 *= (pi / 180)
```

@jeff-regier , do you remember why you did it this way?  The [photoObj documentation](http://data.sdss3.org/datamodel/files/BOSS_PHOTOOBJ/RERUN/RUN/CAMCOL/photoObj.html) is not very helpful.

**Comment by jeff-regier** [comment]
That's the way the worked for the stamps. You can tell when it works by
examining individual galaxies, but it was not easy. It seems like the
photoobj angels and stamp catalog angles differ by 90 degrees and direction
of rotation.

**Comment by rgiordan** [comment]
Ok, the original Celeste conversion from phi to our angle was indeed wrong.  I think it was easy to confuse because we list locations as (h, w), which is (vertical, horizontal) rather than the usual (x, y).  I added a note and fixed it.  This particular source now fits 33% faster, too.  :)

**Comment by rgiordan** [comment]
Fixed in https://github.com/jeff-regier/Celeste.jl/pull/201
