### ISSUE TITLE
Exception when multithreading sources loop

### ISSUE THREAD

**Issue by kpamnany** [jeff-regier/Celeste.jl#194]
On the `distributed` branch, running infer-box for 200.0, 200.05, 38.1, 38.15 shows:

```
31-Mar 11:53:54:ERROR:root:MethodError(Celeste.Transform.from_vp!,([[199.92051641581162,38.125260458678675,0.053857095539569855,0.8,2.5617858658145543,0.2,8.249544966973962,6.904930496483599,0.001,0.001,2.453371249317735,1.1381083258356846,-2.0192355860558746,2.7982136430670157,2.4113951430061826,-0.16656473729791074,-0.086380351496638,2.195025809683977,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[199.92121393679156,38.12428898815124,0.985,0.8,2.4957921347911456,0.2,6.014581286063356,6.040389706117954,0.001,0.001,2.57556408722376,1.3670034493101066,1.0807003851601205,0.5540415343731754,2.5433324386739145,1.457219941972664,1.0392010270497039,0.5664007370314359,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[199.94374033274605,38.00608566523853,0.985,0.8,2.4893835705230063,0.2,5.476493366777806,5.466965673959515,0.001,0.001,1.9153583905368512,0.7883827122295944,0.23989004560153862,0.20275619304951947,1.9019085704695826,0.7999817469210406,0.2772002224954835,0.16089538728656835,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.00571450545644,38.15921796194146,0.6244618892669678,0.985,3.0038841888892676,14.344434545497702,7.154245071997035,9.731753106791235,0.001,0.001,-4.171156447987887,0.09950250909783967,3.2953358902263283,2.172273907304518,0.2233667132105378,0.4639896110614135,0.6987894607004412,0.5798061819385671,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[200.00267682416614,38.16035026759626,0.49721333384513855,0.9639732241630554,1.2044268535293499,36.23011136295819,3.6969895219471396,7.712340860236655,0.001,0.001,-0.9542663302494644,9.0,1.3078232920248962,-9.0,-0.7728305441725973,9.0,1.656400806082218,-9.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[199.9802364668787,38.16244143102247,0.9000900983810425,0.8,2.318931806536065,0.2,4.0342816875034435,4.215424791702232,0.001,0.001,0.7798203603128944,-0.07340232256186169,-9.0,9.0,0.8038858865577284,0.08451185218025709,-9.0,9.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.01378412915247,38.13470443693799,0.015,0.8,2.5029310709882395,0.2,3.877248138247805,3.8835114855580604,0.001,0.001,2.3714462010024207,1.1021998177976282,0.869846275774862,0.4445144319559642,2.2469140116162696,1.2341006275967936,0.8475961963130763,0.47439617959118896,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.00210989977558,38.145717622671974,0.015,0.8,2.4930637262543596,0.2,3.3790942013390315,3.3687387172095424,0.001,0.001,3.029305108277814,1.048580639733431,0.8763450193963116,0.40515763128968685,3.2847219021761243,1.159804348319616,0.8785871271099001,0.4144005683777239,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.0111058171791,38.1569060519365,0.4341650903224945,0.8288547396659851,1.7375546858240611,33.473498893506594,2.572670642872922,6.27971746626689,0.001,0.001,-0.9553341715203686,9.0,1.391543877841741,-9.0,-9.0,9.0,2.3408860933357656,-8.654291884347208,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[200.00816029643858,38.16282354279024,0.06619570404291153,0.27115342020988464,2.2222954776940957,40.15469551086426,2.272299675093294,6.058283387024609,0.001,0.001,-0.9539642889286339,9.0,1.032636738452248,-9.0,-0.7723039688047613,9.0,1.7110786806332485,-9.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[200.00426323658914,38.157037978218284,0.08592106401920319,0.4620562195777893,2.198345470273931,35.444642558242336,2.8794693712578154,6.754654552152722,0.001,0.001,9.0,2.2343552989294975,1.1986003721714131,-9.0,9.0,2.684781475663497,1.483428060683508,-9.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[200.01380041291054,38.155770402215836,0.015,0.8,0.42285778314721745,0.2,2.422322648402628,2.5408889466026197,0.001,0.001,-1.38983261695355,2.892864962599527,0.5581470094118397,-0.9524393217349749,-1.6027756013010923,2.9928733380603094,0.5084038180200295,-0.8560563421558356,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.01512482043032,38.15527073543513,0.015,0.8,0.4708241106986891,0.2,2.458810340608089,2.589450057335616,0.001,0.001,-1.3467721131275414,3.569134022612518,-0.4665235407834228,-0.3958249598954625,-1.028148717278864,3.3242832122700428,-0.5605935938056904,-0.04996951864914652,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.8,0.19999999999999996,0.5,0.5,0.5,0.5],[200.03076148800884,38.16391472581975,0.985,0.7549183964729309,2.529563480837359,0.39687839270842196,1.8548014800219488,1.9244687945467338,0.001,0.001,3.9633115613773024,1.1177531347453467,-9.0,9.0,7.846167042449079,-1.8741584334800347,-9.0,9.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.2,0.8,0.5,0.5,0.5,0.5],[199.99635702846626,38.16309129465312,0.015,0.05000000074505806,0.594315822552045,1.257923140068247,2.540845586403616,2.6766635135517083,0.001,0.001,-9.0,9.0,-0.4655130960706689,-0.3802806183019092,-9.0,9.0,-0.5131223943011932,-0.30712346481937125,0.01,0.01,0.01,0.01,0.01,0
<snipped>
```

**Comment by kpamnany** [comment]
With JULIA_NUM_THREADS=8, it will sometimes segfault after this.

**Comment by rgiordan** [comment]
Kiran, could you please send the whole trace (ideally with debug logging)?

**Comment by kpamnany** [comment]
Please see `/global/cscratch1/sd/kpamnany/celeste_crash.log` on Cori. I terminated the run after seeing the error in there, so it isn't a start-to-finish log.

**Comment by kpamnany** [comment]
It is difficult to tell which source is causing this because thread IDs aren't being displayed in any of these logging calls and there are 3 threads running concurrently. Hopefully you can figure out the state of each thread from the log.

**Comment by jeff-regier** [comment]
I'll try running it without threads, for that region of the sky.

**Comment by kpamnany** [comment]
I did that already, but the error doesn't show. It doesn't show with 2 threads either, which suggests a race condition that is triggered in the presence of sufficient parallelism.

**Comment by kpamnany** [comment]
Please pull the `distributed` branch; I just pushed the (small) change to use threads on the sources loop rather than on the pixels.

**Comment by jeff-regier** [comment]
So the exception is getting caught and logged, and then the program continues with the next source. But we don't even see that exception without threads, so presumably the original problem happens before the exception is thrown. I haven't encountered a MethodError before while running Celeste.

**Comment by kpamnany** [comment]
Add more threads and it segfaults every so often after the exception. Also, I think something breaks in Julia because there are major slowdowns and warnings about SIMD, post-exception.

**Comment by jeff-regier** [comment]
If it's a race condition, what resource might multiple threads be trying to
access? Aren't the the threads are operating pretty much independently one
they've been assigned sources to work on?

**Comment by kpamnany** [comment]
That's the hard question, right? :) It's my understanding as well that since each thread has its own ModelParams, there should be no interaction between them.

**Comment by jeff-regier** [comment]
A minimum working example of the problem would be helpful to have. Can the
problem be recreated without all the Dtree and Celeste code?

**Comment by kpamnany** [comment]
Dtree is not involved; this is running single node. I'm not sure what you mean by without Celeste code... the threading happens on the loop in `infer()` in `src/api.jl`. Without threads, the problem doesn't occur.

**Comment by kpamnany** [comment]
Note that it is possible that the race is in a C library; perhaps one of the packages that Celeste is using? We may need to synchronize access to such a library (i.e. use a lock around calls) if we can figure out that one is the culprit.

**Comment by rgiordan** [comment]
Ok, here might be the problem.  @kpamnany , the line with the error is 422 in `BivariateNormals.jl`:

```
const empty_sig_sf =
    GalaxySigmaDerivs(Array(NumType, 0, 0), Array(NumType, 0, 0, 0));
```

In order to prevent allocating memory for `GalaxySigmaDerivs` for every star when that data structure isn't used at all, I just declared it constant and gave it to every star.  I'm not sure how julia handles constants like this, but I can imagine it causing problems somehow across threads.  What do you think?  It is easy to fix -- at the expense of allocating some extra memory -- by just going back to the way it was before I made this change.

**Comment by rgiordan** [comment]
Try merging the branch `dont_allocate_constant_empty_sig_sf` and give it another go?

**Comment by kpamnany** [comment]
It's a constant, which means it is read-only. You can share read-only data across threads. I can't imagine that it would be the problem, but I'll give it a try.

**Comment by kpamnany** [comment]
Are the only changes in `BivariateNormals.jl`?

**Comment by rgiordan** [comment]
Yes, just that one line.

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by kpamnany** [comment]
Still see the error. Ran with 8 threads, logging level INFO: `/global/cscratch1/sd/kpamnany/no_empty_sig_sf.log`.

Note that the `MethodError` seems to happen only once. From comparing the two logs, the first 4 elements of the list in the error appear to be the same. Also, this seems to happen while sources 7 or 373 are being optimized.

**Comment by kpamnany** [comment]
Ran it again. This time I logged a segfault with logging level DEBUG: `/global/cscratch1/sd/kpamnany/no_empty_sig_sf2.log`. In this log, source 373 isn't around, but again source 7 is being optimized. So I think it is safe to conclude that something about source 7 appears to be causing the problem.

**Comment by rgiordan** [comment]
Sorry, I just looked more carefully and realized that the error in
BivarateNormals.jl was actually you interrupting Celeste. :(

**Comment by rgiordan** [comment]
A slightly long shot -- merge `set_type_of_vp_free` and try again?

**Comment by jeff-regier** [comment]
Is it the PSF fitting that's the problem, or the optimization? (Have you
tried running it with only the PSF fitting commented in?)

**Comment by jeff-regier** [comment]
Kiran, What command are you using to launch the job? Do you want me to try
recreating the problem with various parts of the code commented out, to
figure out what part of the code is problematic?

**Comment by rgiordan** [comment]
If the segfault trace is to be believed, the error is

zeros(0, 0)

Let me change to zeros(NumType, 3, 2) and see if it goes away?

**Comment by rgiordan** [comment]
If you merge `set_type_of_vp_free` and try again it will include that
change.

Also, +1 to sending the command so Jeff and I can try ourselves.

**Comment by kpamnany** [comment]
```
$ salloc -N 1 -p debug -t 00:30:00 --qos=premium
...
$ cd .julia/v0.5/Celeste
$ git checkout distributed
$ export OMP_NUM_THREADS=1
$ export JULIA_NUM_THREADS=8
$ bin/celeste.jl infer-box 200.0 200.05 38.1 38.15 $SCRATCH &> $SCRATCH/logfile
```

**Comment by kpamnany** [comment]
I'm reasonably certain it's happening during optimization. I'm somewhat certain that it has to do with the optimization of source 7 because every MethodError I've seen has been thrown after source 7 was trimmed, but before it was successfully optimized. I suspect this particular optimization is taking a different code path than the optimizations of the other sources in this area of sky and there's some non-threadsafe code being run, either in Julia or in C.

I have no idea what exactly is being corrupted and how. Note that even Base functions like `rand()` are non-threadsafe because they use global state.

**Comment by kpamnany** [comment]
This seems to have gone away, so I'm closing this for now.
