### ISSUE TITLE
set good patch sizes

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#2]
A patch is the region of images affected by a source. The code currently allows the user to specify the size of the patch for each source. But there isn't code yet that picks a good size patch, based on estimates of the brightness and size of the source.

**Comment by jeff-regier** [comment]
Hi @rgiordan , OK if we close this issue? I recall that for now you're setting the patch sizes conservatively. In the  `dat/sample_field` data all the sources look pretty far apart, except for one pair. Are there sources except for this pair that have overlapping patches? If not, the patch sizes are probably good enough as is.

**Comment by rgiordan** [comment]
I'd like to leave this open for now.  What we have is a first step, but is ridiculously conservative and probably has pretty detrimental performance implications.  There are probably big gains to doing this right, and it is not currently done right.

**Comment by rgiordan** [comment]
This problem is fixed with the `trim_source_tiles` function, which is a better solution anyway.
