### ISSUE TITLE
Aborts with dimension mismatch

### ISSUE THREAD

**Issue by kpamnany** [jeff-regier/Celeste.jl#203]
```
$ bin/celeste.jl infer-box 200.0 200.1 38.1 38.2 $SCRATCH
<snip>
01-Apr 16:00:50:INFO:root:initializing celeste without PSF fit
01-Apr 16:00:52:INFO:root:Loading variational parameters from catalogs.
01-Apr 16:01:07:INFO:root:fitting PSF for all relevant sources
01-Apr 16:01:07:INFO:root:Converged.
01-Apr 16:01:08:INFO:root:Converged.
01-Apr 16:01:08:INFO:root:Converged.
<snip>
01-Apr 16:03:14:INFO:root:Converged.
01-Apr 16:03:14:INFO:root:Converged.
01-Apr 16:03:14:INFO:root:Converged.
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
01-Apr 16:03:18:ERROR:root:DimensionMismatch("tried to assign 20-element array to 1x5 destination")
<snip>
```

**Comment by rgiordan** [comment]
Could you tell the branch / multithreading state please?  The path to the
full log?  Maybe a run with DEBUG logging?

This doesn't happen for me with one thread.  It would help me a lot to be
able to run multithreaded myself.  It would also really help to know what
line this is happening on.

**Comment by kpamnany** [comment]
This is on master, with `JULIA_NUM_THREADS=8`. You don't have to do anything beyond set `JULIA_NUM_THREADS` to anything greater than 1 (the default is 4, so you don't have to do anything at all), and Celeste will run multithreaded. I'll rerun and save the log with DEBUG.

**Comment by kpamnany** [comment]
See `/global/cscratch1/sd/kpamnany/log_8.out`.

**Comment by rgiordan** [comment]
Ok, I get the same error.  I'm looking at it.  How annoying that it doesn't
come with a line number.

**Comment by rgiordan** [comment]
Ah, I see the problem.  Another hardcoded "5" from when we only had five
bands.  I'll send a patch soon.

**Comment by rgiordan** [comment]
Potential fix in the branch fix_203.  Testing now.

**Comment by kpamnany** [comment]
:+1:

**Comment by rgiordan** [comment]
Added a relevant unit test, which now passes.  Pull and give it a try,
Kiran?

**Comment by kpamnany** [comment]
Isn't showing up. Last commit on master was `dont_use_mp_array`, an hour ago.

**Comment by kpamnany** [comment]
Oh, branch `fix_203`? Okay.

**Comment by rgiordan** [comment]
It works for me.  I'll make a PR.

**Comment by rgiordan** [comment]
Fixed in https://github.com/jeff-regier/Celeste.jl/pull/204
