### ISSUE TITLE
Trimming takes close to as much time as optimization

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#205]
This can be fixed by pre-processing active pixels.

**Comment by jeff-regier** [comment]
Hey Ryan, Is this still an issue? I don't recall that trimming taking too long.

**Comment by rgiordan** [comment]
I suspect it is, but the solution is pretty invasive with our current large-scale plans.  The way this happens (IIRC) is that with a small star, trimming requires rendering all the pixels in the object's active tiles, only a small fraction of which end up relevant for optimization.  Rendering the value of many pixels once can be close to as expensive as rendering few pixels, with derivatives, 20 or so times.

However, I think the solution I had in mind was to do the trimming as part of a pre-processing step.  That way you at least don't pay this price multiple times, and you can reduce the size of the dataset up front by quite a lot.  However, since we've pivoted way from a pre-processing step and instead are now doing the in-memory fixed-size arrays approach, it doesn't seem feasible.

Given this, it's up to you whether you want to close the issue or leave it open.

**Comment by jeff-regier** [comment]
OK I see, it's more about small sources. Maybe rather than dividing the image into a bunch of tiles, we should just save just the subimage for each image-source pair. Get rid of tiles entirely (or almost entirely...they may be useful in a couple of places as a cheap spatial index.)

Getting rid of tiles is pretty invasive, but let's leave this open. I can imagine it leading to a nice speed up and more readable code.

**Comment by rgiordan** [comment]
Per the phone call, this is a separate issue from getting rid of tiles.  Even with the features described in https://github.com/jeff-regier/Celeste.jl/issues/316, you will still not want to process all the pixels for every source.

**Comment by jeff-regier** [comment]
I think I closed this in #340 : `trim_tiles!` is no more. `trim_source_tiles!` is no more. ActivePixels are found during pre-processing, directly. (There's no setting things to `NaN` ahead of time now and then finding out pixels aren't `NaN` every iteration.)
