### ISSUE TITLE
skip really large galaxies and dim sources

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#209]
@rgiordan Do we have logic to skip really large galaxies? We may have tasks that don't finish during the large runs if we don't skip them. (Though the code is ridiculously fast now!)

I'm also wondering about the cuts based on brightness. We're skipping sources based on their max band brightness in physical units, I think. But some bands (e.g. z) record very few photons regardless of how bright the source is in physical units. Might it be better to just cut based on r band brightness, rather than a max over bands? (Computing the expected number of photons in all bands might be ideal, but r band brightness is probably pretty highly correlated with the total.)

**Comment by rgiordan** [comment]
> @rgiordan https://github.com/rgiordan Do we have logic to skip really
> large galaxies? We may have tasks that don't finish during the large runs
> if we don't skip them. (Though the code is ridiculously fast now!)
> 
> Not right now, no.

I think a good way to do that would be to have trim_source_tiles return a
count of active pixels and threshold based on that.

As part of this, we should save some metadata in the output.  Part of that
could also be whether the optimization hit the maximum number of iterations.

I have some time this evening.  Want me to do this?

**Comment by rgiordan** [comment]
> I'm also wondering about the cuts based on brightness. We're skipping
> sources based on their max band brightness in physical units, I think. But
> some bands (e.g. z) record very few photons regardless of how bright the
> source is in physical units. Might it be better to just cut based on r band
> brightness, rather than a max over bands? (Computing the expected number of
> photons in all bands might be ideal, but r band brightness is probably
> pretty highly correlated with the total.)
> 
> I don't have an opinion about this.  All else equal, I'd say let's not
> change something that's been working for a while now unless we have a good
> reason.

**Comment by jeff-regier** [comment]
There's also a flag (24) that indicates whether a light source is really large. We could cut on that in the SDSSIO module, the same way we skip bright sources already. If the active pixel count is readily available, that's probably preferable.

**Comment by jeff-regier** [comment]
If a small light source overlaps with a large galaxy, and the small light source is the active source, will the objective function get evaluated on just the pixels relevant to the small light source?

**Comment by rgiordan** [comment]
Actually, skipping on 24 would be better, I think!  It's cleaner to
describe (less arbitrary), and the very act of running trim_source_tiles on
a very large object could take a long time (trim_source_tiles evaluates the
likelihood at all the pixels that are candidates for elimination, leading
to at least one very slow, all-pixel function evaluation).

**Comment by jeff-regier** [comment]
Sounds good. I think we're going to want to maintain two sets of sources:
1) sources to optimize, 2) sources to render when they are neighbors of an
active source. Set 2 contains set 1. Right now I believe bright objects are
getting filtered out entirely, but they should get included in set 2 at
least.

**Comment by rgiordan** [comment]
Good point.  Could we put the flag information in CatalogEntry and then
filter them in infer() rather than removing them when we load the catalog?
That's probably the right way to deal with saturated sources as well.

**Comment by jeff-regier** [comment]
The maximum patch size is set to 100 pixels, so large galaxies just get truncated. They won't use up huge amounts of processing---I think that's good enough for now. Ultimately sub-sampling their pixels is the way to go.
