### ISSUE TITLE
initialize_model_params() hotspot

### ISSUE THREAD

**Issue by kpamnany** [jeff-regier/Celeste.jl#217]
Here are logs of two of the processes from a 32 process run which took 903 seconds. Included are the fastest and the slowest, as well as the runtimes for `initialize_model_params()` across all the processes:

https://gist.github.com/kpamnany/e15d46d651a31e9264388c57ee1c76f1

Note that PSF fitting and source optimization together do not take as much time.

**Comment by jeff-regier** [comment]
How big were the regions of the sky for each of the 32 processes?

**Comment by jeff-regier** [comment]
Probably this loop from `initialize_model_params` is the problem:

```
    for b = 1:length(blob)
        for s=1:mp.S
            mp.patches[s, b] = SkyPatch(cat[s], blob[b], fit_psf=fit_psf,
                         scale_patch_size=scale_patch_size)
        end
    end
```

As we increase the region of the sky passed to `infer`, the number of blobs and the number of sources both increase linearly, leading to quadratic runtime here. But most blobs won't contain any particular source.

**Comment by kpamnany** [comment]
I'm not sure I understand your response -- is this something that can be fixed? It looks like the loop above should be parallelizable, once we get threads back. But can anything be done differently/faster?

Also, we aren't increasing the size of the region of sky passed to `infer()`, we call `infer()` repeatedly with a 0.03x0.03 sky region.

**Comment by jeff-regier** [comment]
Maybe I don't get it. You're always calling `infer` with a 0.03x0.03 sky region, but when the whole program is operating on a large of sky, each call to `infer` takes way longer?

Hmm...are you passing all the `fieldids` to `infer` each time, or just the `fieldids` relevant to that region?

**Comment by jeff-regier** [comment]
Yep, I think that's it. It looks like your `divide_and_infer` function is calling `infer` each time with all the `fieldids` for the whole 1x0.5 degree sky region. Instead call `infer` with just the `fieldids` returned by `query_overlapping_fieldids` for the relevant 0.03x0.03 sky region.

**Comment by kpamnany** [comment]
Makes sense. I'll try fixing this.

**Comment by jeff-regier** [comment]
Awesome! That might close #215 too, if each process was loading all the fields for the whole 0.5 degree region rather than just the fields overlapping the 0.009 degree subregion.
