### ISSUE TITLE
Changed meaning of .*= and ./= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [jeff-regier/Celeste.jl#243]
Your code uses `x .*= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .* y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.*` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in cases where it looks like you want to work in-place anyway?  But if it were a problem you could always change it to `x = x .* y`.

Similarly for `./=`.

**Comment by jeff-regier** [comment]
Good to know! I actually thought the meaning of `x .*= y` was `broadcast!(identity, x, x .* y)` all along...I'm lucky not to have had more trouble before.
