### ISSUE TITLE
register Dtree.jl and enable travis-ci

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#244]

**Comment by jeff-regier** [comment]
With the lines

```
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install mpich2 libmpich2-3 libmpich2-dev -y
  - sudo apt-get install openmpi-bin openmpi-common libopenmpi-dev mpi-default-dev -qq -y
```

added to `.travis.yml`, I can list `Dtree` in Celeste's `REQUIRE` file wo breaking the unit tests. Probably some of these apt package aren't necessary even. @kpamnany -- You may want to do something like this to test Dtree on travis.

**Comment by kpamnany** [comment]
Dtree master has Travis enabled and passes now.

**Comment by jeff-regier** [comment]
Awesome!
