### ISSUE TITLE
remove hard-coded nersc paths, so infer-box works elsewhere too

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#253]
@tkelman @vtjnash
I just tried `./celeste.jl infer-box ...` on my own computer, with the data from `$SCRATCH` on Cori copied locally. Unfortunately some parts of the code use files outside of $SCRATCH, in the `/global/projecta/...` directory. For the time being, I think we're stuck running celeste.jl on nersc.

**Comment by rcthomas** [comment]
That's effectively a bug at NERSC too!  All inputs should be staged to $SCRATCH from /project and then when Celeste is off and running it should _only_ be reading/writing to $SCRATCH (or the burst buffer).
