### ISSUE TITLE
refactor bivariate_normals.jl

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#256]
Move `GalaxyCacheComponent` to the `ElboDeriv` module, along with everything else about galaxies in `bivariate_normals.jl`.

**Comment by rgiordan** [comment]
Despite the misleading name, `GalaxyCacheComponent` and its related functions are just ways of taking derivatives of a bivariate normal with respect to its various shape parameters.  This is why it is in `bivaraite_normals.jl` -- there is nothing galaxy-specific about it.

Maybe this refactoring should just be a renaming to clarify this fact.

**Comment by jeff-regier** [comment]
That could work, I got confused when I came to that file via the PSF optimization code. We should probably move it to the `deterministic_VI` directory too once the PSF model is no longer based on Gaussians.
