### ISSUE TITLE
Fix METADATA.jl

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#258]
METADATA.jl's entry for Celeste [refers to a now non-existent commit](https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/Celeste/versions/0.1.0/sha1).

@jeff-regier, you probably know what new commit would be best to tag.

**Comment by jeff-regier** [comment]
Fixed in JuliaLang/METADATA.jl/#5872
