### ISSUE TITLE
Fix unit tests after refactor

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#262]
The tests `test_trim_source_tiles()` and `test_process_active_pixels()` are important but didn't get updated after the last refactor.

**Comment by rgiordan** [comment]
Tentatively fixed in https://github.com/jeff-regier/Celeste.jl/pull/279

**Comment by jeff-regier** [comment]
I think #279 fixed #275 rather than this one.

**Comment by rgiordan** [comment]
Fixed in https://github.com/jeff-regier/Celeste.jl/pull/301, for real this time.

**Comment by jeff-regier** [comment]
Thanks for fixing them
