### ISSUE TITLE
ForwardDiff 0.2 slow compile time

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#264]
The master branch of optim with our trust region code requires ForwardDiff v0.2, but this has really slow compile time, making unit tests much slower than before.

I have removed ForwardDiff from inference which was a good idea anyway (PR forthcoming).  However, removing all the old differentiation unit tests makes me a little uncomfortable.

@jeff-regier, what if we fork ForwardDiff v0.1.8, give it a new name like ForwardDiffOld, and use only the old version in unit tests, allowing Optim to use the newest version?  Is that hopelessly hacky?

**Comment by jeff-regier** [comment]
That's not so bad given the circumstances. I think you'd want to modify `runtests.jl` to clone `ForwardDiffOld` and build it, if it isn't already installed. `ForwardDiffOld` would be an unregistered package, presumably.

**Comment by rgiordan** [comment]
It also happens that time for derivative tests for a few complicated functions (the ELBO itself and some of its higher-level functions) dominate the increased test time.  They are

```
test_elbo()
test_add_log_term()
test_e_g_s_functions()
test_real_image()
```

Maybe we can just do without those tests for now.

**Comment by jeff-regier** [comment]
Isn't `test_elbo()` one of our most important tests?

**Comment by rgiordan** [comment]
Yes, though one that currently takes fifteen minutes, and whose functionality is tested indirectly in several other ways.  Still, I think you're right, it would be better to clone an old fork of ForwardDiff than remove this test.

**Comment by jeff-regier** [comment]
It seems we're stuck with the slow compile times for now. In the Julia 0.5 issues, I see a lot issues about performance regressions that people are working on, so I'm hopeful speed will improve in the future, wo us doing anything.
