### ISSUE TITLE
log-normal brightness priors and variational distribution

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#27]
rather than a gamma distribution

**Comment by rgiordan** [comment]
Any progress on this?  It will be Hessian time soon.

**Comment by jeff-regier** [comment]
Unfortunately I haven't had time, and next week looks hectic too. Flying back from icml today, 3 lectures to plan, trying to detect a syntheric asteroid by Thursday.....Do you mind taking this over? I don't want to slow you down, and it's not a major change, though unit tests probably need to be modified too.

**Comment by rgiordan** [comment]
Can you explain again why it is that you think the lognormal will be better
than the gamma?

**Comment by jeff-regier** [comment]
I fit a gamma and a log normal to a large catalog of stars (resp galaxies).
The fit log normal matches the empirical distribution quite well, at many
quantiles. The gamma really doesn't model the tails well as all, e.g. a
value that is the 99% quantile for the gamma is an 80% quantile for the
empirical cdf. (I don't remember the numbers exactly but that's the scale
of the misfit.)

Also a histogram of stars (resp galaxies) in the stamps from stripe 82
shows that a fit log normal matches closely but that a gamma doesn't.

**Comment by rgiordan** [comment]
Sorry if I'm confused, but the lognormal is supposed to be describing the
posterior uncertainty about the brightness for a single body, not the
marginal distribution of brightness across celestial bodies, right?  I'm
not clear what the marginal distribution has to do with the best posterior
approximation.

**Comment by jeff-regier** [comment]
No, I was referring to the prior. But if you make the prior lognormal you
probably want to make the variational distribution lognormal too.

**Comment by rgiordan** [comment]
Ok, that makes sense.  I will add this to my plate.  On a related note,
could I ask you to put comments and documentation in KL.jl?

**Comment by jeff-regier** [comment]
Yes, will do

**Comment by jeff-regier** [comment]
I added documentation to KL.jl and committed it. Sorry for the delay.

**Comment by rgiordan** [comment]
Could you also please comment up `gen_priors.jl`, too, particularly what sort of catalog file you expect `catalog.fits` to be?  (It seems easier to just ask you than to guess and chase stuff around.)

Also, could you say what's going on at line 46 of `Modelinit.jl`?  Where are those magic numbers from?  Why aren't you using the fit values?

**Comment by jeff-regier** [comment]
Line 46 is blank in master. Right now the magic numbers on line 45 are the parameters for gamma priors on star and galaxy brightnesses. If you use `r_fit1` and `r_fit2` instead the magic numbers, you'll be using the log normal parameters rather than the gamma dist parameters.

I'll look over `gen_priors.jl` and add comments. I think you'd just need to know the format for `r_fit1` and `r_fit2`. The `dat` directory contains output from running the current version of `gen_priors.jl`, both for `D=2` and `D=64`.

**Comment by rgiordan** [comment]
Yeah, but what catalog fits file do you run gen_priors.jl on?

**Comment by jeff-regier** [comment]
Dustin sent me those catalogs awhile ago. They're big files, hundreds of megabytes. They might contain a lot of the objects contained in SDSS. You don't have them? They had names like `stars.fits` and `gals.fits`. Shall I share them with you through Dropbox?

A few notes on variables loaded in ModelInit.jl: `r_fit1` is for stars, and `r_fit2` is for galaxies. Each is a `2 x D` matrix---1 column per component of the mixture. For a particular column, the first entry is the location parameter of a log normal, and the second entry is the scale parameter of a log normal.

**Comment by rgiordan** [comment]
Ah, no, I don't have them.  I'd like to, though.  I only have 400MB free on
my (non-paid) DropBox account, but I can accept them one at a time if
they're each smaller than that.

**Comment by jeff-regier** [comment]
These links will expire, but for now you can get the catalogs here:

http://tempsend.com/85F7A1C8E6
http://tempsend.com/1DDE5A99BC

**Comment by rgiordan** [comment]
Done in https://github.com/jeff-regier/Celeste.jl/pull/88.
