### ISSUE TITLE
log probability function

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#273]
@andymiller -- If you fill out the `celeste_mcmc.jl` script in the `jr/mcmc` branch,  I'll integrate it with the rest of Celeste, so it runs on the supercomputer. As long as the markov chain mixes within a few thousand steps per light source, we should be able to run it on cori for the full SDSS dataset.

Also, @rgiordan expressed interest in reusing your joint probability function for LRVB. And we could reuse that function for AEVB/SGVB too.

**Comment by rgiordan** [comment]
@andymiller , I'll be happy to review this when you're done.

Just to clear up some confusion, LRVB uses the ELBO as it is currently written.  It doesn't require evaluating the log likelihood at a draw.  The log likelihood will still be useful for SGVB and MAP estimation, though.

Andy, you're probably a long way along on this already, but I thought I'd mention that in other code that I've written that does both MCMC and VB I've found that one tidy way to re-use a lot of code is to write the expected log likelihood and prior entirely in terms of the variational moment parameters (i.e., the expectations of every term that appears in the likelihood and prior).  The you can write simple functions that convert your chosen variational parameterization into the moment parameterization, or that converts a draw into degenerate moments (i.e. where all the "expectations" are just their arguments evaluated at a single draw).

Of course, there's no need to do it that way, I just thought I'd mention it.  I'll be happy to look at whatever you've chosen.

**Comment by andymiller** [comment]
@rgiordan, I just opened a PR on the `jr/mcmc` branch.  I think you all more or less set it up easily for me to do this --- the expectations of fluxes are a simple function of the variational parameters, which allows for easy conversion.  

Let me know what you think --- if we can get fast gradients of these functions, then re-parameterization-trick-style variational inference should be pretty straightforward.

**Comment by andymiller** [comment]
@jeff-regier, I'm starting a new branch to incorporate `logprob.jl` into the `Model` module.  I noticed that `get_active_pixels` was refactored into the `DeterministicVI` module (but has a to-do to be moved into pre-processing).  That function relies on the `ElboArgs` type, which the `logprob` code relies on (as well as the `get_active_pixels` function).  Should we move both of those either into `Model` or a module that doesn't depend on `Model`?

**Comment by jeff-regier** [comment]
Hi @andymiller, Let's leave `ElboArgs` in the `DeterministicVI` module: it's specific to a particular type of inference (VI) and thus it's not a property of the model. `get_active_pixels`, on the other hand, belongs in `Model` since all the inference methods will use it. For issue #310, we want to change get_active_pixels to use your log probability function, and presumably move it into `Model` at the same time. That issue is just in the On Hold column because it needs your log prob function.

**Comment by andymiller** [comment]
@jeff-regier, sounds good.  Because `logprob.jl` will need the `get_active_pixels` function, I will tackle both of these issues in the new logprob branch. 
I imagine I will create a `get_active_pixels` function that takes in the types accessed through the `ElboArgs` object passed into the existing version.  I will probably have to move the `ActivePixel` type into the `Model` module as well.

**Comment by jeff-regier** [comment]
Yeah, sounds good, `ActivePixel` belongs in `Model` too, probably near wherever `get_active_pixels` is defined. It looks like you can just call `get_active_pixel` with the images, it doesn't need all the other stuff in the `ea` instance of `ElboArgs`.

**Comment by andymiller** [comment]
@jeff-regier, the `ActivePixel` type and `get_active_pixels` were easy to move into the `Model` module, but now I'm running into a different issue.  The log likelihood function, at this point, relies on the `populate_fsm_vecs!` function in `deterministic_vi/elbo.jl` (which, in turn, relies on the `ElboIntermediateVariables` type).  I'm trying to figure out how to get the `fsm_vecs!` functionality without duplicating code or moving `Elbo` specific stuff into `Model` --- do you have any thoughts on this?

**Comment by jeff-regier** [comment]
I think the way to go is to move `populate_fsm_vecs!` to `Model`, along
with any methods it calls. Then change `populate_fsm_vecs!` so that it
takes as arguments just the fields from `ElboIntermediateVariables` that it
needs, e.g. `fs0m_vec`, `fs1m_vec`. You won't need any of the fields
relating to brightness from `ElboIntermediateVariables`. Does that make
sense?

**Comment by andymiller** [comment]
Yes -- sounds good.  I am moving all of the function logic into `Model`, but leaving wrappers in the `DeterministicVI` module.
