### ISSUE TITLE
accuracy benchmarks based on galsim data

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#293]

**Comment by gostevehoward** [comment]
Here's where I'm at right now.

My first pass at the GalSim script was generated a grid of random images. My thinking now is to define a list of benchmark cases each as a set of parameters to GalSim, mostly corresponding to parameters inferred by Celeste. So, for example, a CSV like [this](https://github.com/gostevehoward/Celeste.jl/blob/galsim_benchmark/benchmark/galsim/galsim_truth.csv), in which we start with a tiny, noiseless, bright galaxy; then, one at a time, we add rotation and ellipticity, varying size, varying flux, etc; then we try all those transformations together, then add noise. The [generate_test_image.py](https://github.com/gostevehoward/Celeste.jl/blob/galsim_benchmark/benchmark/galsim/generate_test_image.py) script reads this CSV and writes a series of FITS images, one for each test case (I know there's a way to put multiple images in a single FITS file, but is it worth the complexity?). Here's an idea of what those images look like, right now:

![Sample test images](https://cloud.githubusercontent.com/assets/1097616/18592205/a904f6da-7bea-11e6-94d6-c48b22d198b0.png)

The [benchmark script](https://github.com/gostevehoward/Celeste.jl/blob/galsim_benchmark/benchmark/galsim/GalsimBenchmark.jl) reads the same CSV, reads in each corresponding image and runs Celeste on it. In theory this can report the inferred and true values side-by-side, or in the future just report some overall accuracy metric and flag if anything's way off.

However, I keep running into [that issue where the optimization crashes](https://github.com/jeff-regier/Celeste.jl/issues/292#issuecomment-247197908). Ryan helpfully debugged the first one and gave me lots of tips (in that issue's comments thread) on how to debug them myself. So I think now is the time for me to learn more about how the optimization works, what all these parameters mean, and how to debug such issues myself.

**Comment by rcthomas** [comment]
Writing multi-extension FITS files shouldn't be that complex:

http://docs.astropy.org/en/stable/generated/examples/io/create-mef.html#sphx-glr-generated-examples-io-create-mef-py

Galsim is just using pyfits or astropy.io.fits to do this.  It may do it for you already.  But the nice thing would be a single csv would go with a single FITS file at least.

**Comment by gostevehoward** [comment]
For what it's worth, I did change it to write/read a single multi-extension FITS file, here: https://github.com/gostevehoward/Celeste.jl/commit/dd4cb64d8f09d31e6e3e7a5f8df0248dafab6130

**Comment by jeff-regier** [comment]
Sounds easier to work with. Is it straightforward to also store in the fits
file the parameters that generated the images (ie the ground truth)?

**Comment by gostevehoward** [comment]
Yeah that is a good idea, I'll look into it: https://github.com/jeff-regier/Celeste.jl/issues/333

**Comment by gostevehoward** [comment]
This has been gradually completed over many other issues; there is more that can be done but I think it's fair to close this.

Users can get started with the [README here](https://github.com/jeff-regier/Celeste.jl/blob/master/benchmark/galsim/README.md).

**Comment by jeff-regier** [comment]
@gostevehoward  Any chance there's an issue with the units (pixels vs arc seconds or something) that explains the misfit of half-light radius here:
```
│ 60  │ "bright_galaxy"               │ "X center (world coords)"    │ 0.005335   │ 0.005335   │
│ 61  │ "bright_galaxy"               │ "Y center (world coords)"    │ 0.005335   │ 0.005335   │
│ 62  │ "bright_galaxy"               │ "Minor/major axis ratio"     │ 0.4        │ 0.404819   │
│ 63  │ "bright_galaxy"               │ "Angle (degrees)"            │ 0          │ 0.0        │
│ 64  │ "bright_galaxy"               │ "Half-light radius (pixels)" │ 3.78788    │ 5.67052    │
│ 65  │ "bright_galaxy"               │ "Brightness (nMgy)"          │ 20         │ 19.9419    │
│ 66  │ "bright_galaxy"               │ "Probability of galaxy"      │ 1          │ 0.994971   │
```
I know our model has some issues with half-light radius, but what I don't get is how brightness, angle, and axis ratio can all be so accurate while the radius is off by so much (nearly 80% too big). IIRC, a galaxy with a much larger radius but the same brightness is much dimmer at its center, since brightness is a total across pixels, not the intensity at the galaxy center. (Is it that not the case?)

What was the brightness initialized to for "bright galaxy"? Did we end up with a brightness that's nearly correct because we initialized to something near the truth and got stuck in a local minima? Otherwise it seems like quite a coincidence that all the parameters are accurate while scale is so wrong. A units mismatch would be a nice (and easily fixed) explanation, but maybe that's wishful thinking?

**Comment by gostevehoward** [comment]
I agree, it doesn't make sense that half-light radius is off by so much and
everything else is dead on. Something must be off either in the galsim
generation script or the Celeste code. I would like to look into it further.

**Comment by gostevehoward** [comment]
I made #437
