### ISSUE TITLE
Add pixel mask to ElboDeriv.jl

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#31]
In order to read real frames which sometimes have bad pixels, we need to be able to assign zero weights to certain pixels in ElboDeriv.

**Comment by jeff-regier** [comment]
How about storing `NaN` in the image as the value for corrupted pixels? (The type of `NaN` is `Float64`.) That way we don't need a separate data structure to store whether pixels are good or bad.

**Comment by rgiordan** [comment]
That's a great idea.  Let's leave this issue open because we'll still need to add the NaN checking to ElboDeriv.
