### ISSUE TITLE
Get rid of tiles

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#316]
For a rasterized psf (https://github.com/jeff-regier/Celeste.jl/issues/87), tiles don't make a lot of sense, mostly because the light from pixels in a particular tile extend beyond that tile after convolution with the PSF.

Right now the main reason we have tiles is to limit the sources that we process (via `tile_source_map`).  Instead of this, we could just have a vector of vectors from sources to the sources that are nearby according to the same logic used to decide whether sources affect a tile.

In case sources affect a lot of tiles, we could additionally add some logic in all the functions that evaluate values and derivatives of `BvnComponent`s and `GalaxyCacheComponents` to return zero automatically if the point is some number of standard deviations away from its mean.  That is probably a good idea in its own right.

This could result in considerable simplification of the `Image` structure and pre-processing, too.

@jeff-regier , @gostevehoward , any thoughts or things that I have missed?

**Comment by jeff-regier** [comment]
This is also worth doing from the reason in #205. I'll close that issue because this one subsumes it.

**Comment by jeff-regier** [comment]
This is a pretty involved issue. Here's an attempt at breaking it down into smaller issues:

stage 1:
- [ ] extend `ActivePixel` to include `epsilon` and `x_nbm`
- [ ] revised `log_prob.jl` and `elbo.jl` to use the new fields in `ActivePixel`---gives fast memory access without tiles
- [ ] Do trimming by forming `ActivePixel`s in a loop, calling into a per-pixel function in logprob to get the expected brightness, and saving the `ActivePixel` iff it exceeds a threshold
- [x] Move `get_active_pixels()` to preprocessing
- [ ] Save `ActivePixel`s in patches--they belong to a source-image pair
- [ ] delete `get_sources_per_tile`, `get_local_sources`, and `local_source_candidates`
- [ ] delete `get_tile_source_map`; delete `get_tile_source_map`
- [ ] make sure unit test pass; commit; PR

stage 2:
- [ ] delete everything in `image_model.jl` except `Image`
- [ ] delete tile unit tests like `test_tile_image`  and `test_tile_predicted_image`
- [ ] In SampleData.jl, chance `make_elbo_args` to load `ElboArgs` with `Image`s, not `TiledImages`
- [ ] revise until no output from `grep -i tile test/*.jl` 
- [ ] revise until no output from `grep -i tile -r src/`
- [ ] get unit tests passing; delete redundant unit tests; commit; PR
