### ISSUE TITLE
Avoid unrealistic "colors" in benchmarking

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#320]
Right now I'm copying the same image into all five filter bands. This creates an unrealistic color distribution which may clash with Celeste's priors and throw off inference for other parameters. Possible fixes: (a) only pass one image in one band; (b) scale the image in each band to a realistic distribution, e.g., one taken from test stamps or synthetic image code.

**Comment by gostevehoward** [comment]
Done here:

https://github.com/gostevehoward/Celeste.jl/commit/dd4cb64d8f09d31e6e3e7a5f8df0248dafab6130

I scaled flux in each band by a realistic amount and had the GalSim script write distinct files for each band, so we'd get unique noise, correct scaling relative to background, etc.

Inferred answers don't seem to have gotten more accurate, but cross one thing off the list...

**Comment by jeff-regier** [comment]
Looks good. The colors seemed by far like the most likely source of the
problem. What's left to check? Have you tried making stars with galsim?
Those are easier to debug because they don't have shape parameters.

**Comment by gostevehoward** [comment]
Not yet, that's next up to try: https://github.com/jeff-regier/Celeste.jl/issues/321
