### ISSUE TITLE
Make a test case with stars

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#321]
Right now I don't attempt to generate star images which should be detected as stars, even though Galsim does have the capability to do that (at least I think it does, because the Great3 data includes star images). I need to figure out how to generate an appropriate test case that Celeste will (or should be expected to) classify as a star.

**Comment by gostevehoward** [comment]
Done [here](https://github.com/gostevehoward/Celeste.jl/commit/2bd1a26175ffef40a808a6a807f1458baefe147f).

Increasing `loc_width` (by 2000x) and tweaking my positioning code in `generate_test_image.py`, Celeste now pinpoints positions of the stars perfectly. Progress. Unfortunately, the reference brightness estimates still seem to be ~20% too high, consistently. Probably something I'm doing wrong in handling the color bands somewhere along the way. I tried to get the mode of the "color" prior [here](https://github.com/gostevehoward/Celeste.jl/blob/galsim_benchmark/benchmark/galsim/GalsimBenchmark.jl#L65), maybe that is off. The other problem is that Celeste still always thinks everything is a galaxy. Maybe an issue with the PSF mismatched between the generation script and Celeste. In any case it all falls under #322.

**Comment by jeff-regier** [comment]
For brightness, do either the median or the mode of the variational distribution match more closely than the mean? Brightness is log normal, so 
- the mean is `exp(vs[ids.r1[1]] + vs[ids.r2[1]] /  2)`
- the median is `exp(vs[ids.r1[1]])`
- the mode is `exp(vs[ids.r1[1]] - vs[ids.r2[1]])`
