### ISSUE TITLE
Debug why location and brightness are mis-estimated

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#322]
Currently location, scale and brightness are showing clear biases in my benchmark cases. We need to rule out the (likely) possibility that it's a problem with inputs (poor CatalogEntry initializations, unrealistic colors, etc) so that any remaining inaccuracies can be attributed to Celeste's optimization. This will require me to do things like run each benchmark image with multiple initializations and look at objective values and maybe gradients to determine whether it's a problem with local optima or what.

**Comment by gostevehoward** [comment]
Some ideas from the weekly call:
- Ensure rasterized PSF sums to one
- Use elbo_likelihood (?) instead of elbo when calling `maximize_f`to avoid the influence of the prior
- check raw sum of pixel values in generated images to ensure it matches the total flux given to GalSim

**Comment by jeff-regier** [comment]
How different are the mean, the median, and the mode for the brightness according to the variational distribution? Is it the mean that is consistently 20% too high? The mean should be unbiased across a population of stars. For a particular star, it's the median that minimizes the absolute error (i.e. L1 error), so it wouldn't be a hack to use that instead of the mean.

**Comment by jeff-regier** [comment]
One other idea: In `test/test_elbo.jl`, there's a function `test_that_star_truth_is_most_likely()`. For synthetic data generated from the our model, this function confirms that the true brightness is more likely than a brightness 10% higher than the truth. If you make a GalSim image containing one star that's like the star in this test case, then the true brightness should be most likely for it too. If it isn't, you're pretty close to finding the source of the discrepancy. And if it is, you're pretty close too!

**Comment by gostevehoward** [comment]
Update: I've been trying to figure out both why the brightness estimates are high and why it consistently estimates stars as galaxies. I thought maybe solving the second problem would shed light on the first.
- I was not able to figure out where in the code to find a rasterized PSF which I could sum.
- I tried using `elbo_likelihood` instead of `elbo` in `maximize_f` but saw the same results.
- I added an assertion that the raw sum of pixel values in the GalSim-generated code matches what we would expect.
- I figured out that Celeste seems to expect that the pixels given to it have the sky background counts added in; I changed `generate_test_image.py` to include those. This causes Celeste to overestimate brightness by much more (understandably), but as far as I can tell this is what is happening in the tests. It's very possible I'm misunderstanding something here which is the root cause of the brightness problem.
- I figured out that the PSF parameters in `PsfComponent` are expected to be in pixel coordinates, not world coordinates, and changed that. No change in behavior.
- I checked for differences between the mean/median/mode of the lognormal brightness distribution but they are all very close; the variance is very small.
- I looked at the image used in `test_that_star_truth_is_most_likely()`.
  - First of all, it is very very bright: ~2300 nMgy whereas the median star in the prior is ~20 nMgy. I tried making my Galsim star equally bright and observed the same pattern (overestimated brightness, high probability that the object is a galaxy).
  - Secondly, I think maybe the reason the object is more likely a star than a galaxy in that test is because the star color ratios `vp.c1[:, 1]` are a better fit to the image than the galaxy color ratios `vp.c1[:, 2]`. But when actually running Celeste, the color ratios for both types get fit very well to the image. So I'm not sure why Celeste is always estimating the object as 99.5% galaxy in my GalSim tests, but I don't think `test_that_star_truth_is_most_likely()` sheds much light on this because it's not a fair comparison.

**Comment by jeff-regier** [comment]
In `test_that_star_truth_is_more_likely()` we're calling `elbo_likelihood()`, not `elbo()`. The former doesn't use the color priors, so it shouldn't matter if the star color ratios are a better fit than the galaxy color ratios. 

Would you upload plots of your galsim generated star that is ~2300 nMgy, and the synthetic star from `test_that_star_truth_is_most_likely()`, so that we can visually inspect them side-by-side?

I've had good results with the `Images.jl` and `ImageViewer.jl` packages, for plotting intensities.

Another plot that would be helpful: A "subtracted" image, that subtracts the model's predicted intensity at each pixel from the observed intensity. Might reveal that the model PSF and the galsim PSF don't match, for instance.

**Comment by jeff-regier** [comment]
Also, for your galsim image, would you try running `elbo_likelihood()` manually (not by calling the optimizer), for both the ground truth and for a brightness that's 10% too high? It's not likely, but possible, that the optimizer is going off the rails. Anyway, this problem will be easier to debug if your test of the galsim data looks as much like `test_that_star_truth_is_most_likely()` as possible.

**Comment by gostevehoward** [comment]
Quick update: I started changing the PSF used in GalSim to be nearly identical to that used in `test_that_star_truth...`. This actually fixed the problem with brightness.

I figured out the problem was that `ElboArgs.psf_K` was set to 2, the default. I had been using a PSF composed of three identical `PsfComponent`s, each with `alphaBar = 1/3`. (This was because of the comment in #292 which turned out to be a red herring but I never changed it back.) Putting weight on the third PSF component, which was ignored in the elbo, messed everything up. Putting weight just on the first one (or two) fixed the brightness problem.

The PSF in `test_that_star_truth...` also has three components but the third has zero weight. The `ElboArgs` used there also sets `psf_K = 2`.

Could we assert that `psf_K` equals the number of `PsfComponent`s in each image's `psf`? Does `psf_K` need to be passed in the first place, if we can just look at the number of components in each image's `psf`?

**Comment by gostevehoward** [comment]
Also the probability of galaxy `vp[ids.a[2]]` is still close to one for the star images.

What I was saying about colors was regarding the values of `ElboArgs.vp[1][ids.c1[:, 1]]` versus `ElboArgs.vp[1][ids.c1[:, 2]]` (which, in this test, are initialized from `SampleData.sample_{star,galaxy}_fluxes`). If I understand right these are the parameters used to compute the likelihood and are separate from the priors. So the fact that the former are better fit to the test images than the latter would cause the likelihood of star to be higher than the likelihood galaxy, i.e., would make the likelihood with `ea.vp[1][ids.a[:, 1]] = [.99, .01 ]` higher than the likelihood with `ea.vp[1][ids.a[:, 1]] = [.9, .1 ]`?

**Comment by jeff-regier** [comment]
Huzzah! Glad you found this problem. I'm all for avoiding having multiple specifications of `psf_K`, but I think the PSF is going to change entirely shortly once @rgiordan makes a PR, so I wouldn't bother with the issue for now. Or add an assertion quickly if it's easy.

The elbo has two terms: `elbo_likelihood()` and `elbo_kl()`. `ElboArgs.vp[1][ids.c1[:,:]]` shows up in both. `elbo_kl()` penalizes settings of `ElboArgs.vp[1][ids.c1[:,:]]` that deviate from the prior distribution. Would you open a new issue for the star/galaxy mix up?

**Comment by gostevehoward** [comment]
OK I'll make this issue for the brightness and break out new issues for star/galaxy and also for e_scale which seems off too. For the record, here's the current output of the benchmark script, at [this commit](https://github.com/gostevehoward/Celeste.jl/commit/646a18f506ca4494e3861bacc8734dd6419b2b2a):

```
│ Row │ label                                       │ field                        │ expected │ actual   │
├─────┼─────────────────────────────────────────────┼──────────────────────────────┼──────────┼──────────┤
│ 1   │ "simple star"                               │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 2   │ "simple star"                               │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 3   │ "simple star"                               │ "Brightness (nMgy)"          │ 40       │ 39.7125  │
│ 4   │ "simple star"                               │ "Probability of galaxy"      │ 0        │ 0.995    │
│ 5   │ "star position 1"                           │ "X center (world coords)"    │ 16.0     │ 16.0     │
│ 6   │ "star position 1"                           │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 7   │ "star position 1"                           │ "Brightness (nMgy)"          │ 40       │ 39.7128  │
│ 8   │ "star position 1"                           │ "Probability of galaxy"      │ 0        │ 0.995    │
│ 9   │ "star position 2"                           │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 10  │ "star position 2"                           │ "Y center (world coords)"    │ 20.0     │ 20.0     │
│ 11  │ "star position 2"                           │ "Brightness (nMgy)"          │ 40       │ 39.7128  │
│ 12  │ "star position 2"                           │ "Probability of galaxy"      │ 0        │ 0.995    │
│ 13  │ "dim star"                                  │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 14  │ "dim star"                                  │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 15  │ "dim star"                                  │ "Brightness (nMgy)"          │ 20       │ 19.8392  │
│ 16  │ "dim star"                                  │ "Probability of galaxy"      │ 0        │ 0.995    │
│ 17  │ "bright star"                               │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 18  │ "bright star"                               │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 19  │ "bright star"                               │ "Brightness (nMgy)"          │ 80       │ 79.4684  │
│ 20  │ "bright star"                               │ "Probability of galaxy"      │ 0        │ 0.995    │
│ 21  │ "star with noise"                           │ "X center (world coords)"    │ 17.0     │ 16.9988  │
│ 22  │ "star with noise"                           │ "Y center (world coords)"    │ 19.0     │ 18.997   │
│ 23  │ "star with noise"                           │ "Brightness (nMgy)"          │ 40       │ 39.4909  │
│ 24  │ "star with noise"                           │ "Probability of galaxy"      │ 0        │ 0.994999 │
│ 25  │ "angle and axis ratio 1"                    │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 26  │ "angle and axis ratio 1"                    │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 27  │ "angle and axis ratio 1"                    │ "Minor/major axis ratio"     │ 0.2      │ 0.226211 │
│ 28  │ "angle and axis ratio 1"                    │ "Angle (degrees)"            │ 15       │ 15.0038  │
│ 29  │ "angle and axis ratio 1"                    │ "Half-light radius (arcsec)" │ 1.0      │ 2.82768  │
│ 30  │ "angle and axis ratio 1"                    │ "Brightness (nMgy)"          │ 10       │ 9.96979  │
│ 31  │ "angle and axis ratio 1"                    │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 32  │ "angle and axis ratio 2"                    │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 33  │ "angle and axis ratio 2"                    │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 34  │ "angle and axis ratio 2"                    │ "Minor/major axis ratio"     │ 0.4      │ 0.423371 │
│ 35  │ "angle and axis ratio 2"                    │ "Angle (degrees)"            │ 160      │ 159.991  │
│ 36  │ "angle and axis ratio 2"                    │ "Half-light radius (arcsec)" │ 1.0      │ 2.02488  │
│ 37  │ "angle and axis ratio 2"                    │ "Brightness (nMgy)"          │ 10       │ 9.98955  │
│ 38  │ "angle and axis ratio 2"                    │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 39  │ "radius 1"                                  │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 40  │ "radius 1"                                  │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 41  │ "radius 1"                                  │ "Minor/major axis ratio"     │ 1.0      │ 0.989999 │
│ 42  │ "radius 1"                                  │ "Angle (degrees)"            │ 0        │ 109.752  │
│ 43  │ "radius 1"                                  │ "Half-light radius (arcsec)" │ 0.5      │ 0.708908 │
│ 44  │ "radius 1"                                  │ "Brightness (nMgy)"          │ 10       │ 10.002   │
│ 45  │ "radius 1"                                  │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 46  │ "radius 2"                                  │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 47  │ "radius 2"                                  │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 48  │ "radius 2"                                  │ "Minor/major axis ratio"     │ 1.0      │ 0.989997 │
│ 49  │ "radius 2"                                  │ "Angle (degrees)"            │ 0        │ 153.755  │
│ 50  │ "radius 2"                                  │ "Half-light radius (arcsec)" │ 1.5      │ 1.92164  │
│ 51  │ "radius 2"                                  │ "Brightness (nMgy)"          │ 10       │ 9.95357  │
│ 52  │ "radius 2"                                  │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 53  │ "flux 1"                                    │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 54  │ "flux 1"                                    │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 55  │ "flux 1"                                    │ "Minor/major axis ratio"     │ 1.0      │ 0.989994 │
│ 56  │ "flux 1"                                    │ "Angle (degrees)"            │ 0        │ 25.0852  │
│ 57  │ "flux 1"                                    │ "Half-light radius (arcsec)" │ 1.0      │ 1.31145  │
│ 58  │ "flux 1"                                    │ "Brightness (nMgy)"          │ 5        │ 5.00059  │
│ 59  │ "flux 1"                                    │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 60  │ "flux 2"                                    │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 61  │ "flux 2"                                    │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 62  │ "flux 2"                                    │ "Minor/major axis ratio"     │ 1.0      │ 0.989999 │
│ 63  │ "flux 2"                                    │ "Angle (degrees)"            │ 0        │ 89.8155  │
│ 64  │ "flux 2"                                    │ "Half-light radius (arcsec)" │ 1.0      │ 1.31256  │
│ 65  │ "flux 2"                                    │ "Brightness (nMgy)"          │ 20       │ 20.0266  │
│ 66  │ "flux 2"                                    │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 67  │ "everything"                                │ "X center (world coords)"    │ 18.3     │ 18.3001  │
│ 68  │ "everything"                                │ "Y center (world coords)"    │ 17.3     │ 17.3002  │
│ 69  │ "everything"                                │ "Minor/major axis ratio"     │ 0.4      │ 0.41336  │
│ 70  │ "everything"                                │ "Angle (degrees)"            │ 15       │ 15.0015  │
│ 71  │ "everything"                                │ "Half-light radius (arcsec)" │ 1.5      │ 2.98704  │
│ 72  │ "everything"                                │ "Brightness (nMgy)"          │ 15       │ 14.9267  │
│ 73  │ "everything"                                │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 74  │ "everything with noise"                     │ "X center (world coords)"    │ 18.3     │ 18.3156  │
│ 75  │ "everything with noise"                     │ "Y center (world coords)"    │ 17.3     │ 17.3142  │
│ 76  │ "everything with noise"                     │ "Minor/major axis ratio"     │ 0.4      │ 0.416039 │
│ 77  │ "everything with noise"                     │ "Angle (degrees)"            │ 15       │ 15.2922  │
│ 78  │ "everything with noise"                     │ "Half-light radius (arcsec)" │ 1.5      │ 2.98853  │
│ 79  │ "everything with noise"                     │ "Brightness (nMgy)"          │ 15       │ 14.7095  │
│ 80  │ "everything with noise"                     │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 81  │ "everything with noise and low background"  │ "X center (world coords)"    │ 18.3     │ 18.296   │
│ 82  │ "everything with noise and low background"  │ "Y center (world coords)"    │ 17.3     │ 17.2954  │
│ 83  │ "everything with noise and low background"  │ "Minor/major axis ratio"     │ 0.4      │ 0.407092 │
│ 84  │ "everything with noise and low background"  │ "Angle (degrees)"            │ 15       │ 14.668   │
│ 85  │ "everything with noise and low background"  │ "Half-light radius (arcsec)" │ 1.5      │ 3.01222  │
│ 86  │ "everything with noise and low background"  │ "Brightness (nMgy)"          │ 15       │ 14.74    │
│ 87  │ "everything with noise and low background"  │ "Probability of galaxy"      │ 1        │ 0.995    │
│ 88  │ "everything with noise and high background" │ "X center (world coords)"    │ 18.3     │ 18.2877  │
│ 89  │ "everything with noise and high background" │ "Y center (world coords)"    │ 17.3     │ 17.3019  │
│ 90  │ "everything with noise and high background" │ "Minor/major axis ratio"     │ 0.4      │ 0.410065 │
│ 91  │ "everything with noise and high background" │ "Angle (degrees)"            │ 15       │ 15.2242  │
│ 92  │ "everything with noise and high background" │ "Half-light radius (arcsec)" │ 1.5      │ 3.03322  │
│ 93  │ "everything with noise and high background" │ "Brightness (nMgy)"          │ 15       │ 14.6634  │
│ 94  │ "everything with noise and high background" │ "Probability of galaxy"      │ 1        │ 0.995    │
```

**Comment by gostevehoward** [comment]
Created #369 for the star/galaxy issue. @jeff-regier says to not debug the e_scale issue because it has been seen on stripe 82 as well.
