### ISSUE TITLE
Include trimming in GalSim benchmark script

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#323]
Part of the cause of the infamous "epsilon > 0 crashes" might be the fact that the benchmark images are large compared to the size of the galaxy (in some cases more than others) and therefore include pixels very far from the light source which usually would be trimmed out. In order to make the benchmarks more efficient, they should use the same trimming code that is ordinarily used.

**Comment by gostevehoward** [comment]
I added a simple call to trim_source_tiles!(). Remains to investigate whether it is doing exactly what we want it to do.

https://github.com/gostevehoward/Celeste.jl/commit/0a6c87195db06fb6e61fbcbb93712be261e13db4

**Comment by jeff-regier** [comment]
Can we close this issue @gostevehoward ? (Was it part of your recent PR?)

**Comment by gostevehoward** [comment]
Sure. I added trimming but never checked whether it was working properly on these tests. But I think the original motivation for caring about this (the epsilon = 0 thingy) isn't bothering anyone now so let's not waste time on it unless something comes up again.
