### ISSUE TITLE
Move `VariationalParams` from `Model` to `DeterministicVI`

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#327]
Also, `FreeVariationalParams`.

**Comment by jeff-regier** [comment]
@andymiller -- Rather than creating a `GalShape` type to call `load_bvn_mixtures` , could you reuse the `LatentState` type (or whatever it's call now)? That contains all the galaxy shape parameters, as well as some extra ones.

**Comment by andymiller** [comment]
That sounds good, @jeff-regier.  In `param_set.jl` there seem to be `GalaxyPosParams` that has all the fields I need.  What are these used for?  Also, it looks like fields are all `Int`s of some type --- is there a way to reuse this code, or should I just define my own types?

**Comment by jeff-regier** [comment]
I suggest defining a new ParamSet in `param_set.jl`, something like

```
immutable LatentStateIndexes <: ParamSet
    u::Vector{Int}
    e_dev::Int
    e_axis::Int
    e_angle::Int
    e_scale::Int
    r::Vector{Int}
    c::Matrix{Int}
    a::Matrix{Int}
    k::Matrix{Int}

    LatentStateIndexes() =
        new([1, 2], 3, 4, 5, 6,
            collect(7:(7+Ia-1)),  # r
            reshape((7+Ia):(7+Ia+(B-1)*Ia-1), (B-1, Ia)),  # c
            reshape((7+Ia+(B-1)*Ia):(7+2Ia+(B-1)*Ia-1), (Ia, 1)),  # a
            reshape((7+2Ia+(B-1)*Ia):(7+2Ia+(B-1)*Ia+D*Ia-1), (D, Ia))) # k
end
```

You could use an instance of this type throughout `Model`, just as we're using `ids` (an instance of `CanonicalParams`) currently.  A better name for `CanonicalParams`, now that we're merging MCMC and VI, might be `VariationalParamIndexes`.

**Comment by andymiller** [comment]
Oh --- I see how these are being used.  

Is this kind of indexing faster than using a vector of typed objects, where the type with named fields?

**Comment by jeff-regier** [comment]
You could also reused `GalaxyPosParams` if you just need `u` and the `e_...` indexes. But it probably makes more sense to pass the full latent state (a vector of length 22) for each source to every function in `Model` rather than just the galaxy state (a vector of length 6).

Yes -- This is approach is for speed. Keeping all the params in a vector keeps them together in memory. With a composite type, each field is a pointer to a vector, so a single source has its parameters all over the place.

**Comment by andymiller** [comment]
Great --- I'll create a LatentStateIndexes object for this.  Thanks!

**Comment by andymiller** [comment]
@jeff-regier - it looks like `VariationalParams` and `FreeVariationalParams` are used in `Transform.jl`, which is imported by `DeterministicVI.jl`.  As `Transform.jl` sits at a higher level, moving these types in there seems to work and pass tests.  Can you think of a better spot for them?

**Comment by jeff-regier** [comment]
No, that's a fine spot. We should really either make Transform part of
DeterministicVI or else get the VI stuff out of Transform. But that's for
another time, and not a really high priority.
