### ISSUE TITLE
Write tests for rasterized PSF code

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#356]

**Comment by rgiordan** [comment]
The convolution functions have tests, but I will still need to incorporate the PSF into all the standard ELBO tests.

Note that ForwardDiff cannot differentiate through the FFT, which is written on C++, which will affect a lot of tests.  I need to look into going back to numeric differentiation.

**Comment by rgiordan** [comment]
Some basic tests were done in https://github.com/jeff-regier/Celeste.jl/pull/447.  As of right now, ```verify_sample_galaxy``` fails because the brightness is off by 3% rather than 1% (even though it gets a lower ELBO value than the MOG).

**Comment by jeff-regier** [comment]
OK if we close this issue then? Whether or not the tests are passing, they've been written, and that's all the title says.

Could the 3% be because the cubic interpolation isn't flux conserving? (Does the 3% figure drop as the PSF gets larger?)

**Comment by rgiordan** [comment]
I'm not convinced that the FFT code is adequately tested.  The FFT ELBO wasn't optimizing at all on real examples until a few days ago for reasons we still don't completely understand, and it still doesn't pass the most basic galaxy test.  If nothing else, there are tests in ```test_elbo``` and ```test_optimization``` that should have FFT versions.

It is certainly possible that flux non-preservation is problem.  I'll be looking into it.

**Comment by rgiordan** [comment]
I'm going to leave this to the long-term maintainers of the Celeste package.  If the FFT version is going to be the default, the bulk of the unit tests should be using it, in my opinion.
