### ISSUE TITLE
Debug why GalSim stars are predicted to be galaxies

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#369]

**Comment by jeff-regier** [comment]
On stripe 82, we misclassify about 20% of stars as galaxies but only about 5% of galaxies as stars. I suspect that's because we don't have priors on the galaxy shape parameters, so galaxies have more degrees of freedom to fit the data, and they aren't being penalized by prior distributions for having that freedom. We'll address this problem in #348.

What you're seeing may or may not be due to the same issue. For a sufficiently bright star, with normal star colors, your should find that it's a star with very high probability. If you that works, I'd say your code is fine and that we could close this issue and handle the underlying problem in #348.

**Comment by gostevehoward** [comment]
I have not managed to make a case that gets classified as a star. The uploaded test cases include an 80 nMgy star. I tried making it 200 nMgy with no change. Here's the full vp:

```
32×2 DataFrames.DataFrame
│ Row │ id_name   │ vp          │
├─────┼───────────┼─────────────┤
│ 1   │ "u_1"     │ 18.0        │
│ 2   │ "u_2"     │ 18.0        │
│ 3   │ "e_dev"   │ 0.0100007   │
│ 4   │ "e_axis"  │ 0.989996    │
│ 5   │ "e_angle" │ 10.0        │
│ 6   │ "e_scale" │ 0.275842    │
│ 7   │ "r1_1"    │ 5.29207     │
│ 8   │ "r1_2"    │ 5.29829     │
│ 9   │ "r2_1"    │ 0.000100023 │
│ 10  │ "r2_2"    │ 0.0001      │
│ 11  │ "c1_1_1"  │ 1.60823     │
│ 12  │ "c1_2_1"  │ 0.717688    │
│ 13  │ "c1_3_1"  │ 0.300146    │
│ 14  │ "c1_4_1"  │ 0.16889     │
│ 15  │ "c1_1_2"  │ 1.60654     │
│ 16  │ "c1_2_2"  │ 0.717319    │
│ 17  │ "c1_3_2"  │ 0.300134    │
│ 18  │ "c1_4_2"  │ 0.168844    │
│ 19  │ "c2_1_1"  │ 0.000101229 │
│ 20  │ "c2_2_1"  │ 0.000100223 │
│ 21  │ "c2_3_1"  │ 0.000100087 │
│ 22  │ "c2_4_1"  │ 0.000100119 │
│ 23  │ "c2_1_2"  │ 0.000100021 │
│ 24  │ "c2_2_2"  │ 0.000100003 │
│ 25  │ "c2_3_2"  │ 0.000100001 │
│ 26  │ "c2_4_2"  │ 0.000100002 │
│ 27  │ "a_1_1"   │ 0.00500007  │
│ 28  │ "a_2_1"   │ 0.995       │
│ 29  │ "k_1_1"   │ 0.00500357  │
│ 30  │ "k_2_1"   │ 0.994996    │
│ 31  │ "k_1_2"   │ 0.00500611  │
│ 32  │ "k_2_2"   │ 0.994994    │
```

Here's the test case output:

```
11×4 DataFrames.DataFrame
│ Row │ label              │ field                        │ expected │ actual   │
├─────┼────────────────────┼──────────────────────────────┼──────────┼──────────┤
│ 1   │ "very bright star" │ "X center (world coords)"    │ 18.0     │ 18.0     │
│ 2   │ "very bright star" │ "Y center (world coords)"    │ 18.0     │ 18.0     │
│ 3   │ "very bright star" │ "Minor/major axis ratio"     │ NA       │ 0.989996 │
│ 4   │ "very bright star" │ "Angle (degrees)"            │ NA       │ 32.9578  │
│ 5   │ "very bright star" │ "Half-light radius (arcsec)" │ NA       │ 0.275842 │
│ 6   │ "very bright star" │ "Brightness (nMgy)"          │ 200.0    │ 198.754  │
│ 7   │ "very bright star" │ "Color band 1-2 ratio"       │ NA       │ 4.99397  │
│ 8   │ "very bright star" │ "Color band 2-3 ratio"       │ NA       │ 2.04969  │
│ 9   │ "very bright star" │ "Color band 3-4 ratio"       │ NA       │ 1.35006  │
│ 10  │ "very bright star" │ "Color band 4-5 ratio"       │ NA       │ 1.18399  │
│ 11  │ "very bright star" │ "Probability of galaxy"      │ 0        │ 0.995    │
```

I think the colors are typical for the (second component of the) star color prior but maybe I'm misinterpreting that. Is there a good example of an image that is actually inferred to be (most likely) a star in the test cases? I looked briefly but didn't find one.

**Comment by jeff-regier** [comment]
That unit test is the place to start, the `test_that_truth_is_most_likely()`
one. Also test_optimization.jl has examples of correctly classified stars.

**Comment by gostevehoward** [comment]
OK. I don't think `test_that_*_is_most_likely` is helpful here because it
just looks at the likelihood, it doesn't run inference, so the fact that
the image happens to fit the preset star parameters makes the star
likelihood higher, but that doesn't reflect what happens in inference. In
inference the color parameters for both star and galaxy get very well
fitted to the data. Like you said in the other thread, it seems like the KL
term should be penalizing the galaxy fit more; I guess it's not, but
`test_that_*_is_most_likely` doesn't help us with that.

I'll look at `test_optimization.jl`

**Comment by gostevehoward** [comment]
Update: @rgiordan suggested I look at residual images for the star predictions. The star residuals were positive in the center and negative towards the edges, suggesting the Celeste PSF was too narrow. Hence the galaxy scale parameter could be used to make the galaxy fit the image better. Making the Celeste PSF slightly wider reduced the star residuals and caused Celeste to predict the star test cases as stars rather than galaxies, finally. Those pesky PSFs. I'll try to figure out exactly why they're not matching up the way I thought they should, tomorrow. Perhaps that will shed some light on the scale issue to. (FWIW my hack of just guessing a slightly larger PSF width did not fix the scale issue for galaxies.)

**Comment by jeff-regier** [comment]
Interesting finding!

**Comment by gostevehoward** [comment]
For the record, my best explanation for what's causing this is that the GalSim test images are using a very small PSF (sigma = 1.33 pixels), so there can be a substantial difference between (a) the density value at the center of this pixel (times the area of the pixel) and (b) the integral of the density over the pixel area. Jeff's feeling is that realistic PSFs will always be larger than one pixel by enough of a margin to make this issue safe to ignore.

Here's a bright star image from a GalSim test:

![true_image](https://cloud.githubusercontent.com/assets/1097616/19949192/97768be8-a10d-11e6-91d3-9b58b65617fd.png)

Here's the predicted image assuming the object is a star:

![star_image](https://cloud.githubusercontent.com/assets/1097616/19949194/9b9bf0d2-a10d-11e6-9c53-9f6c99b33a70.png)

Here are the residuals:

![star_residuals](https://cloud.githubusercontent.com/assets/1097616/19949197/9e49e6cc-a10d-11e6-914c-01797262b336.png)

The predicted image is too high in the center and too low towards the edges. This first made me think the Celeste PSF was small. But it's also consistent with the above point sample vs. integration issue. We can confirm this is actually happening. The star has 200,000 counts total flux and the PSF has sigma = 1 pixel. The middle pixel from the Celeste predicted image has ~31,600 counts, approximately equal to 1/2pi \* 200,000 (Celeste estimates a brightness slightly lower than 200k counts to achieve best possible fit). The GalSim middle pixel has value ~29,300; the integral of the standard bivariate normal over [-.5,.5]^2 is ~.147 which is approx. 29,300 / 200,000.

I tried a little hack to test the idea. I changed `eval_bvn_pdf!()` to compute the pdf at the center (a) and the four corners (b, c, d, e), then return (2a + b + c + d + e) / 6 as the evaluated mass (in `bvn_derivs.f_pre[1]`; I didn't touch the derivatives). This is a sort of trapezoidal rule in 2D using triangles, I'm sure there's a nicer way but this was simple. This did cause the star residuals to get much smaller and caused Celeste to predict the stars as stars (and to predict brightness more accurately).

However, it should be noted that as I mentioned in the previous comment, just making the Celeste PSF slightly larger made it predict stars as stars too. So this fact alone doesn't confirm that we found the "real" problem.

**Comment by gostevehoward** [comment]
Minor update: changing the PSF sigma from 1 to 3 pixels caused some, but not all, stars to be predicted as stars. Changing it to 4 pixels made it reliable.

**Comment by jeff-regier** [comment]
Do you mean changing the PSF from 1 to 3 pixels caused some, but not all, stars to be predicted _as stars_? It gets better when you increase the PSF variance, right?

**Comment by jeff-regier** [comment]
That is some really thorough analysis Steve, in your previous post. The explanation seems very plausible to me.

**Comment by gostevehoward** [comment]
Sorry, yes, changing PSF sigma 1 to 3 pixels caused some but not all stars to be correctly predicted as stars. Setting PSF sigma = 4 pixels caused all stars to be correctly predicted as stars. (Updated comment above for posterity.) Higher PSF sigma = more accurate results, presumably because the center point density more closely matches the integrated density over the pixel.
