### ISSUE TITLE
Read SDSS catalog into Celeste

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#37]
Jeff -- what do you think about just writing a simple python wrapper around tractor to read in the existing catalog and write to a Celeste-readable csv or something?

You can take a look at what it does in [tractor/sdss.py/_get_sources](https://github.com/dstndstn/tractor/blob/f1d92f0569e61f920932635b469222a2ac989ed7/tractor/sdss.py#L217).  It mostly looks like bookkeeping.  This would also let us deal cleanly later with alternative initializations.

**Comment by jeff-regier** [comment]
I think we'll want to output a catalog in the SDSS format too, not just read one in. It's probably better to engage with the SDSS FITS format from the beginning, than to have to understand the Tractor format from the beginning, and then perhaps later the FITS format too.

I think we can limit ourselves to just the most recent SDSS data release. That appears to cut down the number of lines that would need to be ported.

Also `_get_sources` appears to return just the sources near a specified location. But we probably want to load the whole catalog for a particular frame at once. (Is that the case?)

**Comment by rgiordan** [comment]
That's a good point about eventually having to write it out, too.  I will do it in Julia.

_get_sources has the option to only read from a specified location, but at the end of the day it is reading a FITS catalog file that is indexed by run, camcol, and field, just like the image files.  We can just read the whole thing.

**Comment by rgiordan** [comment]
Done with e7e8f76da4404ecb8d133ce3601808deb0054f41.
