### ISSUE TITLE
Add GalSim test cases with overlapping star/galaxy, overlapping star/star

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#370]

**Comment by jeff-regier** [comment]
A few test images with 3 sources overlapping would be good too. Maybe in one all 3 sources could overlap, whereas in the another just two pairs would overlap?

**Comment by gostevehoward** [comment]
Done and new FITS file uploaded to portal.nersc.

**Comment by jeff-regier** [comment]
Awesome. @agnusmaximus -- Please reach out to Steve when you're ready to test Cyclades on galsim data.
