### ISSUE TITLE
Merge all the GalSim work in, add README and upload built FITS file

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#371]

**Comment by jeff-regier** [comment]
Rather the checking in the FITS files, please store them in

```
/project/projectdirs/dasrepo/www/
```

perhaps in a `celeste` directory, and make everything world readable.  Then you should be able to see it on the web at

http://portal.nersc.gov/project/dasrepo/

Then maybe add a Makefile, like `test/data/Makefile`, to the benchmarks directory, that fetches these images. Or the benchmarks script do the fetching. Either way seems fine.

**Comment by gostevehoward** [comment]
See README [here](https://github.com/gostevehoward/Celeste.jl/tree/galsim_benchmark/benchmark/galsim)

I don't seem to have write permissions to the `dasrepo/www` dir:

```
showard@edison03:~> mkdir /project/projectdirs/dasrepo/www/celeste             
mkdir: cannot create directory `/project/projectdirs/dasrepo/www/celeste': Permission denied
```

**Comment by gostevehoward** [comment]
If anyone's itching to look at the FITS file and doesn't want to install Vagrant or wait for Rollin to give me write access to `/dasrepo/www`, here's the current version:

[galsim_test_images.fits.zip](https://github.com/jeff-regier/Celeste.jl/files/554604/galsim_test_images.fits.zip)

**Comment by jeff-regier** [comment]
Oh, maybe that's even better than storing them on the nersc servers. I didn't know about github file hosting.

**Comment by rcthomas** [comment]
Added @gostevehoward to dasrepo file group.  Might take ~20 min to propagate.  Let me know if it's not working after an hour (if you use it).

**Comment by gostevehoward** [comment]
@rcthomas I'm in the group but still can't write to `.../dasrepo/www` because its owner/group is `racah/racah`:

```
showard@edison03:~> mkdir /project/projectdirs/dasrepo/www/celeste
mkdir: cannot create directory `/project/projectdirs/dasrepo/www/celeste': Permission denied
showard@edison03:~> groups
showard dasrepo
showard@edison03:~> ls -ld /project/projectdirs/dasrepo/www
drwxrwxr-x 4 racah racah 512 Jun 24 16:52 /project/projectdirs/dasrepo/www
showard@edison03:~> ls -ld /project/projectdirs/dasrepo    
drwxrwxr-x 14 prabhat dasrepo 131072 Oct 13 16:47 /project/projectdirs/dasrepo
```

@jeff-regier I don't know much about github file hosting, it might be awkward if the only interface is to attach files to issues and comments.

**Comment by rcthomas** [comment]
Ah didn't notice that sorry.  I chgrp'ed www to dasrepo and then tested your mkdir, it's there now.  I notice you are using The Civilized Person Shell.  Sadly it is kind of borked on the Crays and I personally gave up trying to use zsh and just go with bash :(

**Comment by gostevehoward** [comment]
Haha, thanks for the heads up, I'll switch back to bash. I had noticed some funny things going on.

Here's the uploaded FITS: http://portal.nersc.gov/project/dasrepo/celeste/galsim_test_images.fits

Will write a Makefile to fetch that (#373)
