### ISSUE TITLE
render sky subtracted images

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#374]
Write a function the uses the `Images.jl` and `ImageViewer.jl` libraries to render sky subtracted images, perhaps as part of an image containing three subimages: the original image, the mean image of the variational distribution, and the sky subtracted image.

This function should have a few options:
- save to disk as a png or display
- divide each pixel of the sky subtracted image by the square root of mean image
- render with log scaling (?)

Maybe this belongs in a utils.jl script, included directly in the Celeste module?

**Comment by rgiordan** [comment]
Most of this is already done in ```CelesteEDA.jl```.
