### ISSUE TITLE
try running taskfarmer on 2 TB of SDSS data

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#379]

**Comment by jeff-regier** [comment]
Using taskfarmer, I ran the `infer-rcf.jl` script on the run-camcal-fields (RCFs) that overlap with the RA x Dec bounding box [140, 165] x [10, 40]. This box contains 34,987 RCFs, about 4% of all of SDSS, or about 2TB. All but 2 RCFs were finished processing successfully. I used up to 128 nodes, but also experimented with 32 and 64 nodes. The throughput doubled when the number of nodes doubled, though I was not using the burstbuffer. On each node I ran 8 processes, each with 4 threads. The jobs lasted up to 6 hours. I submitted 4 jobs to process all the RCFs.

To process the primary detections in one RCF, `infer-rcf.jl` typically loads about 10 other RCFs too. Yet the total time in `infer_source()` was about 90% of the runtime, again, without using the burstbuffer. That 10% also includes compiling, launching processes, selecting tasks, etc.

About 20% of all RCFs contain 0 primary detections. The average number of primary detections per RCF is about 400. The most primary detections in one RCF is 770. The output contains optimized parameters for 10,508,485 light sources. 2363 light sources do not appear in the output catalog due to errors during processing.

**Comment by rcthomas** [comment]
Cool, Job IDs below.

```
rthomas@cori08:~> sacct -u jregier -S 2016-11-04 -X
JobID    JobName  Partition    Account  AllocCPUS      State ExitCode
------------ ---------- ---------- ---------- ---------- ---------- --------
3043811         celeste    regular    dasrepo       4096    TIMEOUT      1:0
3044401         celeste    regular    dasrepo       8192    TIMEOUT      1:0
3047230         celeste    regular    dasrepo       6144  COMPLETED      0:0
3048013         celeste    regular    dasrepo         64  COMPLETED      0:0
```
