### ISSUE TITLE
joint inference on 4 nodes

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#384]
Use [Garbo.jl](https://github.com/kpamnany/Garbo.jl) to run joint inference on 2 or 4 supercomputer nodes. It's unclear whether we want the mulitnode distribution of work to look more like sky division parallelism (implemented in `ParallelRun.jl`) or source division parallelism (implemented in `source_division_inference.jl` on the `src_div_par` branch). Each had some issues, and neither seems exactly compatible with joint inference. But in either case, each node has ownership of some light sources. Optimized parameters are stored in a global array now. We probably need another global array to synchronize optimization across nodes.

@kpamnany , @agnusmaximus -- Let's discuss this during the conference call tomorrow, or right afterwards.

**Comment by kpamnany** [comment]
Joint inference will apply to how many light sources concurrently? I assume there'll be a maximum cap of some sort?

**Comment by jeff-regier** [comment]
Ideally there's no maximum. Any sources that overlap with each other would be optimized jointly. Jointly doesn't have to mean "concurrently" though. Just that the optimal value for one light source's parameters depend on the other light source's parameters.

We should probably do a walkthrough of Max's code sometime soon.

**Comment by jeff-regier** [comment]
It's no longer necessary for Cyclades manage work for multiple nodes with the red-black approach to node-level parallelism.
