### ISSUE TITLE
WCS coordinates, not pixel coordinates

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#4]
Encode source locations in WCS coordinates, not pixel coordinates. Stamps are pixel aligned, so pixel coordinates were fine before. Frames in different bands aren't exactly pixel aligned.

**Comment by rgiordan** [comment]
I started a "wcs" branch to work on this.

Just a few questions to get started:
- I should be looking at the files in dat/sample_field, right?
- Is there a reason load_field is commented out?
- What does this comment mean: "# temporary, until dustin gets back to me"?
- What does this one mean: "# this doesn't look right...way too small"?
- Anything else I should know?

**Comment by jeff-regier** [comment]
Yes, start with `dat/sample_field`.

"load_field" is commented out because I never finished writing it. I made some progress, but I stopped when I realized that I'd need to fit the PSF myself, and just used stamps for ICML.

The lines immediately following "temporary..." read in metadata from the stamps instead of fields, just as a placeholder. I hadn't figured out how to populate those values for the fields. 

I hoped that value from column 70 was the sky background noise level. It was called "SKY" somewhere, after all. But it looks too small, in relation to the sky noise in the stamps.

The data you want (except for the PSF as a mixture of Gaussians) is probably mostly contained in `sample_field/calibPhotomGlobal-003900-6.fits` and `sample_field/photoField-003900-6.fits`. They're described on the following SDSS web pages:
http://data.sdss3.org/datamodel/files/PHOTO_CALIB/RERUN/RUN/nfcalib/calibPhotomGlobal.html
http://data.sdss3.org/datamodel/files/BOSS_PHOTOOBJ/RERUN/RUN/photoField.html

There's probably a lot more to know, but I don't know it either. :-) I'll forward you the email I got from Dustin about it, but you'll likely want to follow up with him.

**Comment by jeff-regier** [comment]
It looks like FITSIO.jl has some new high-level routines for reading FITS tables, added after I wrote `load_field`. You'll probably want to use them instead of doing it the way I did.

https://julia-fitsio.readthedocs.org/en/latest/api.html#table-operations

**Comment by rgiordan** [comment]
This is done in https://github.com/jeff-regier/Celeste.jl/pull/39 .
