### ISSUE TITLE
Add unit tests and factor the SDSS utilities into a separate package.

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#41]
There are at least a couple people in the AMPLab who want to use some of this functionality.

**Comment by rgiordan** [comment]
Jeff, I haven't split a git repo into two before.  I'm inclined to simply
- Create a completely new repo in which I add copies of the current files (so no git history)
- git rm the files from Celeste.jl (maintaining the history in Celeste.jl though the files are gone)
  Any objections to this?

**Comment by jeff-regier** [comment]
Splitting off the SDSS stuff sounds reasonable. Might some of the commands
in the post below do what you're talking about in a more principled way
than deleting and adding?

http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository

**Comment by rgiordan** [comment]
Done in https://github.com/jeff-regier/Celeste.jl/pull/53.  Still haven't pruned the package tree yet, though.
