### ISSUE TITLE
stage SDSS to the datawarp

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#412]
The datawarp is also known as the burstbuffer, an array of SSDs. 

http://www.nersc.gov/users/computational-systems/cori/burst-buffer/

**Comment by jeff-regier** [comment]
Done! 59 TB! Our partition on the burst buffer is named "celestebb". It was easier to decompress SDSS again than to copy it over from scratch. I used taskfarmer and 64 nodes this time rather than leaving `xargs -P 32` running over night on a few nodes. The `staging` directory now contains all the scripts needed to reload our partition.

**Comment by rcthomas** [comment]
Hi @jeff-regier, that's great.  Just making sure you're aware that the reservations have a finite lifetime on the BB (like 2 weeks I think), so you will have to re-stage again if the persistent period isn't long enough for you.

**Comment by jeff-regier** [comment]
Two weeks works, though 6 months would be better, i.e. now through GB. It's
not a big deal to reload it occasionally, though each reload takes 64 nodes
about 4 hours (~8000 CPU hours).
