### ISSUE TITLE
Debug why half-light radius is off in GalSim benchmarks

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#437]
For example (pasted from #293):

```
│ 60  │ "bright_galaxy"               │ "X center (world coords)"    │ 0.005335   │ 0.005335   │
│ 61  │ "bright_galaxy"               │ "Y center (world coords)"    │ 0.005335   │ 0.005335   │
│ 62  │ "bright_galaxy"               │ "Minor/major axis ratio"     │ 0.4        │ 0.404819   │
│ 63  │ "bright_galaxy"               │ "Angle (degrees)"            │ 0          │ 0.0        │
│ 64  │ "bright_galaxy"               │ "Half-light radius (pixels)" │ 3.78788    │ 5.67052    │
│ 65  │ "bright_galaxy"               │ "Brightness (nMgy)"          │ 20         │ 19.9419    │
│ 66  │ "bright_galaxy"               │ "Probability of galaxy"      │ 1          │ 0.994971   │
```

**Comment by gostevehoward** [comment]
I think I figured this out. You might know much of this already but I'll write up everything I figured out so we're on the same page/for posterity.

First of all, I added a test case with a perfectly round galaxy (minor/major axis ratio = 1). This case has the same axis ratio (configured in GalSim) as "angle_and_axis_ratio_1" and "angle_and_axis_ratio_2"; the former has an axis ratio of 0.2, the latter of 0.4. Comparing the three is informative:

```
│ 3   │ "round_galaxy" │ "Minor/major axis ratio"     │ 1        │ 0.989962 │
│ 5   │ "round_galaxy" │ "Half-light radius (pixels)" │ 3.78788  │ 3.61934  │

│ 3   │ "angle_and_axis_ratio_2" │ "Minor/major axis ratio"     │ 0.4      │ 0.40537  │
│ 5   │ "angle_and_axis_ratio_2" │ "Half-light radius (pixels)" │ 3.78788  │ 5.64817  │

│ 3   │ "angle_and_axis_ratio_1" │ "Minor/major axis ratio"     │ 0.2      │ 0.205604 │
│ 5   │ "angle_and_axis_ratio_1" │ "Half-light radius (pixels)" │ 3.78788  │ 7.95618  │
```

For "round_galaxy" with an axis ratio of 1, the inferred half-light radius is almost right (4% low); as the axis ratio goes down the inferred half-light radius gets larger.

I think the issue is in how one defines "half-light radius" for a elliptical galaxy. The [Wikipedia page](https://en.wikipedia.org/wiki/Effective_radius) defines it only for circular galaxies. So both GalSim and Celeste seem to define it (implicitly, at least) in terms of an original circular galaxy which gets transformed to produce the observed galaxy.

The difference is that Celeste uses a transformation in which, starting from a circular galaxy (a collection of bivariate normals), we simply shrink along the minor (y) axis to achieve the desired axis ratio, then rotate (this I backed out from the code in [`get_bvn_cov`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/bivariate_normals.jl#L14), correct me if I'm wrong). GalSim works by producing a circular (exponential) galaxy with a given half-light radius, then calling `shear()`, which [produces an area-preserving transform](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/shear.py#L25). Effectively, if the minor/major axis ratio is `a`, then after shrinking the minor axis by `a`, it scales the whole image (both dimensions) by `1/sqrt(a)`, expanding it to preserve total area. This expansion is why Celeste infers a larger half-light radius. In both of the cases above, it's off by approximately by a factor of `1/sqrt(a)`.

I tried making `test_case_definitions.py` scale the images by `sqrt(a)` after applying the shear, making GalSim's transformation match Celeste's (in theory?); this causes Celeste to infer nearly-correct half-light radius in all three cases. It's consistently low, but it's much closer:

```
│ 5   │ "round_galaxy" │ "Half-light radius (pixels)" │ 3.78788  │ 3.61934  │
│ 5   │ "angle_and_axis_ratio_2" │ "Half-light radius (pixels)" │ 3.78788  │ 3.61477  │
│ 5   │ "angle_and_axis_ratio_1" │ "Half-light radius (pixels)" │ 3.78788  │ 3.61645  │
```

Question is, which is the right definition to use (if either)? GalSim's area-preserving transform seems nice, but this is a question for an astronomer, not me.

**Comment by jeff-regier** [comment]
This is great news! And the units issue you discovered with galsim data may apply to our stripe 82 validation also. Let's compare the half-light radii in units based on Galsim's area-preserving transform. The Celeste definition of half-light radius made sense to me at the time, but apparently it isn't the standard definition. I'll try scaling by `sqrt(a)` in the code for scoring Celeste on stripe 82 too.

**Comment by gostevehoward** [comment]
OK, I'm not sure which fix you prefer---

1. an internal change to Celeste's handling of `e_scale`, or 
2. a change in the `GalsimBenchmark.jl` script to scale up Celeste's `e_scale` value before comparing it with the GalSim value (and we would want to document this particular interpretation of `e_scale`), or
3. a change in the GalSim image generation script to shrink galaxies in generated images so that the half-light radius matches Celeste's definition.

**Comment by jeff-regier** [comment]
I think 2 is best --- a change to Celeste would be invasive, and it's no problem if Celeste's internal representation of parameters differs from what we report, so I prefer 2 to 1. For reporting, we might as well use units astronomers are familiar with, so I prefer 2 to 3, though that doesn't matter too much.
