### ISSUE TITLE
review logs from the full-SDSS run to see where estimated runtime differed from actual runtime

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#443]

**Comment by jeff-regier** [comment]
It's mostly the worst case that matters. The box with the longest run times was
```
infer-box.jl 109.5 109.75 -14.25 -14.0
```
It finished in
```
Celeste.ParallelRun.BoundingBox(109.5,109.75,-14.25,-14.0) took 13552.728412491 seconds
```

It's estimated hardness was
```
$ ./estimate-box-runtime.jl 109.5 109.75 -14.25 -14.0
...
[1] INFO: 73606 hardness (13 rcfs x 5662 targets) for region 109.5 109.75 -14.25 -14.0
```
which wasn't far from the limit (100,000). Had it exceeded 100,000, it would have been divided into smaller boxes. Instead it appeared in the top 6% of boxes.

The second most long-running task also appears in the top 6% of boxes according to estimated runtime.

On the other hand, the task that was estimated to take the longest (a full 100,000 units of difficulty) actually took only
```
slurm-3145502.out:[1] INFO: infer_box for Celeste.ParallelRun.BoundingBox(354.5,355.0,-2.5,-2.0) took 1444.118078708 seconds
```

Visual inspection of [the area estimated to be most difficult](http://legacysurvey.org/viewer?ra=354.5125&dec=2.5068&zoom=13&layer=sdssco) vs [the area that was actually the most difficult](http://legacysurvey.org/viewer?ra=109.5165&dec=-14.2466&zoom=13&layer=sdssco) shows that the latter has many more bright objects--looks like a star field. If necessary, we can more accurately estimate its difficulty by accounting for the brightness of the objects it contains, rather than just multiplying the number of light sources by the number of images.

@kpamnany

**Comment by kpamnany** [comment]
As I said in the other issue, I'm concerned that these boxes are too large for effective load balance. A single task with a runtime of ~3.75 hours is pretty crazy. If the task granularity is, in fact, too coarse, then we'll have to shrink the boxes, and we can consider improving the difficulty estimate at that point.
