### ISSUE TITLE
Assertion Error : 0 < scale on Joint Infer

### ISSUE THREAD

**Issue by agnusmaximus** [jeff-regier/Celeste.jl#446]
I get an assertion error: "@assert 0 < scale" on this line of the code: https://github.com/jeff-regier/Celeste.jl/blob/joint_infer_assertion_error/src/bivariate_normals.jl#L18

Steps to reproduce:

1. Pull the joint_infer_assertion_error branch.
2. run "julia ./test/runtests.jl joint_infer"
3. After about a minute of optimization the program should exit with the error.
    - The error is caught on https://github.com/jeff-regier/Celeste.jl/blob/joint_infer_assertion_error/src/cyclades.jl#L309

It's odd that this error only seems to happen after the first iteration, with non-default parameters for the NewtonTrustRegion optimizer.

Could it just be that using the default parameters is similar to using too large of a step size?

**Comment by jeff-regier** [comment]
Hi Max, What's the value of `scale` when the assertion is false? Is it `NaN` or something negative?

**Comment by agnusmaximus** [comment]
I think it's NaN... I'm making sure by checking right now

**Comment by agnusmaximus** [comment]
Update: yeah it's NaN

**Comment by jeff-regier** [comment]
Thanks for checking. I suspect it originates in the `Transform` module. The optimizer takes a step in the unconstrained parameter space, but that step turns out to be huge in the constrained parameter space. I wonder why it's `NaN` and not `Inf`....

**Comment by jeff-regier** [comment]
I followed the steps, but I don't get the assertion error. I just made a PR that attempts to catch the problem earlier, before `elbo` is called, by verifying that `vp` are all finite when constructing an `ElboArgs` instance. Does that stop the `0 < scale` error for you?

**Comment by agnusmaximus** [comment]
Hmm dang, I think I made a mistake. I updated the Optim package just now and the error went away.

**Comment by agnusmaximus** [comment]
Let my try some other stuff to make sure updating the package fixes everything

**Comment by agnusmaximus** [comment]
Hmm, yeah sorry about this, I think this error was due to my Optim package being outdated. With the upgraded Optim package everything works fine.

**Comment by jeff-regier** [comment]
No problem, glad it's working
