### ISSUE TITLE
Mysterious NLOpt Failures

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#47]
I came across an NLOpt failure using the free transform and spend a lot of the afternoon tracking it down with autodiff.  I managed to find a discrepancy between the hand-coded and forward autodiff derivatives.  The discrepancy was actually due to a numerical error in the autodiff, not in in the hand-coded derivatives.  However, the source of this error could manifest in subtle ways in the numerical optimization routine and we should keep it in mind.

I isolated the problem to the `gen_gamma_kl` function.  When `r1` and `r2` are very large, this function involves differences of very large floating point quantities that need to cancel each other out, which is numerically unstable.  This turns out to affect forward autodiff more than the hand-coded derivatives, though of course it potentially makes the actual value unstable as well.

Normally this isn't too bad because the box constraints keep `r1` and `r2` from being very large.  However, due to having re-parameterized the brightness in terms of its mean and variance, the box constraints on the transformed parameters were no longer constraining the actual gamma shape and scale parameters.

I've returned to simply using positivity constraints on the brightness parameters and the problem has gone away for now.  But if you do manage to find a reproducible instance of an NLOpt failure, let me know, because now we have some more powerful tools for diagnosing them.

**Comment by jeff-regier** [comment]
Might the numerical stability get better with #27 ?

**Comment by jeff-regier** [comment]
Can we close the issue since we're switching to Optim.jl and trust regions?

**Comment by rgiordan** [comment]
Let's leave it open until we actually make the switch.  The trust region approach isn't working perfectly yet.

**Comment by rgiordan** [comment]
I'm going to close this. The trust region is working as well as BFGS on real images.  I haven't explored switching all the tests over to the trust region yet -- I suspect on the tests' toy problems TR might be slower, and I suspect that will be a fussy change -- but this is no longer a blocking issue for real applications.
