### ISSUE TITLE
Generate a field with ~500 sources from GalSim

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#471]
Use the same dimensions as SDSS images, and report how often parameters are off by >1 SD, etc.

**Comment by gostevehoward** [comment]
For reference, from #461 (my bad making the duplicate):

Generate a field-sized image (in all 5 bands) containing around 500 light sources. Get the parameters for these light sources by sampling from our prior distributions. Place the light sources uniformly at random in the image. Some should overlap. Modify the galsim benchmark so that it can run on just this image, maybe by specify the FITS file containing this data.

**Comment by gostevehoward** [comment]
@jeff-regier: did you want to draw these from prior defined in `Model.load_prior()`? It has 99% prior probability of being a star, which it sounds like has been set artificially high to counteract the flexibility of the galaxy model? Do you want to bring that down for the purposes of generating this field? Or instead of drawing from the distribution did you want to just sample rows from a catalog such as [`coadd_for_4263_5_119.fit`](https://github.com/jeff-regier/Celeste.jl/blob/master/test/data/coadd_for_4263_5_119.fit) (and maybe randomize positions)?

**Comment by jeff-regier** [comment]
Ah, no, I'll find a better way to encode a "penalty" for not having parameterization-invariant priors on the galaxies' parameters. For now, please just hard code in your script `a = [0.28, 0.72]`, i.e. 28% stars and 72% galaxies.

**Comment by jeff-regier** [comment]
I haven't list priors yet for `e_fracdev`, `e_angle`, and `e_axis`. For `e_angle`, uniform on [0,180] is a reasonable prior. For `e_axis`, let's go with Beta(2,2) for now. For `e_fracdev`, maybe Beta(0.5, 0.5). I'll add more exact values to `Model.prior` in the future.

**Comment by gostevehoward** [comment]
FYI the galsim image generation code currently doesn't have any support for `e_dev`, it generates all galaxies using a pure exponential profile. We can make an issue to add that support and add some appropriate test cases.

**Comment by jeff-regier** [comment]
Is it galsim that doesn't support De Vaucouleurs galaxy profiles? Or you is it your Python code that only generates exponential galaxies? If the latter, what's involved in generating De Vaucouleurs galaxies too?

**Comment by gostevehoward** [comment]
The latter. GalSim supports the [de Vaucouleurs profile](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/base.py#L2665) the same as it supports the [exponential profile](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/base.py#L2568). Adding support is easy, just add another field to [`Galaxy`](https://github.com/jeff-regier/Celeste.jl/blob/master/benchmark/galsim/generate_test_image.py#L146) in `generate_test_images.py` and reference it [here](https://github.com/jeff-regier/Celeste.jl/blob/master/benchmark/galsim/generate_test_image.py#L182).

Question: is the `e_dev` parameter more of a belief mixture, akin to `ids.a`, the star/galaxy mixture? Or is it intended to be a flexible way of describing actual observed galaxy profiles? Put another way, do we want to only generate images that are either pure exponential or pure de Vaucouleurs, or do we want to actually generate images that are a mixture of an exponential profile and a de Vaucouleurs profile?

**Comment by jeff-regier** [comment]
Good question. It's a mixture weight, not a probability. Many galaxies are composites, somewhat like a dev galaxy and somewhat like an exp galaxy.

**Comment by gostevehoward** [comment]
Closing as done by #501; the `e_dev` issue is in #508 and debugging the accuracy will come after #510.
