### ISSUE TITLE
VB Solution is not invariant to a

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#48]
The test `test_elbo_invariance_to_a()` actually contains an extremely particular set of parameters that allow the test to pass, and the VB solution is not at all invariant to `a` in general.  For example, changing the fluxes in the unit test to 1000 rather than 100 times the sample fluxes causes `test_elbo_invariance_to_a()` to fail.

For an even more dramatic failure, try fitting only the star parameters to a dataset generated by `gen_sample_star_dataset(perturb=false)` with `a` fixed at 0.01, 0.5, and 0.99.  Here are the fit star brightnesses:

```
  a = 0.01  a = 0.5  a=0.99
  4470.74   5304.13  2422.03    
  1581.14    987.354    0.109955
  2558.08    393.688    0.591057
  2646.56      0.845658 0.79425 
 18480.3   18627.8  17495.4  
```

I've explored a few other examples and it seems like `a` dependence is more common than independence.  I'm not sure exactly what's going on.  I think you're right that the coupling must be in the lower bound term.  I can imagine this causing problems for optimization.

**Comment by rgiordan** [comment]
If you have a Poisson model for a single pixel, and you observe x electrons, then the MLE for y_1 in

```
a_1 y_1 + a_2 y_2 - x * log(a_1 y_1 + a_2 y_2)
```

is of course not invariant to a_1 -- per our intuition, the optimal value for a_1 y_1 will be the one that fits the residual between x and a_2 y_2.  The VB solution shouldn't be qualitatively different from this.  Can you explain again why you think it should be separable?

**Comment by jeff-regier** [comment]
The a_1 and a_2 shouldn't show up inside the log in our objective function,
unless you're using them to denote binary random variables.  Once you apply
iterated expectations the parameter to the Bernoulli star/galaxy parameter
(also called a) only appears outside the log.

**Comment by rgiordan** [comment]
Got it, this makes sense, thanks for explaining (again).  That doesn't change the fact that (surely due to the Taylor series approximation to the log) the objective isn't invariant to a.

This might be making the optimization harder.  A possible solution would be the mixture of poissons we discussed a few months ago, though I'm not sure it's necessary.

**Comment by jeff-regier** [comment]
I could be mistaken but I think the Taylor expansion only changes the
objective function for S > 1. Block coordinate ascent, with 1 block of star
params, 1 block of galaxy params, and one block of the other params, might
work well, at least when S = 1. And if it does, making it work for S > 1
seems doable.

**Comment by rgiordan** [comment]
Why do you think it only holds for S=1?  For one thing, the poisson rate is a sum of quantities even for a single source.  For, another, consider the example that started this thread, which uses a single source.

**Comment by jeff-regier** [comment]
Ah, I was mistaken about it holding for S=1. Rather, when S=1, and without background noise (background is effectively another light source), the taylor approximation isn't necessary to make E [ log F_{nbm} ] tractable.

**Comment by jeff-regier** [comment]
Should we delete `test_elbo_invariance_to_a()` and close the issue? If that taylor approximation is any good (and it seems to be) the global optimum should be pretty close to invariant to `a`, but I guess it doesn't follow that the local optimum returned by l-bfgs will be roughly invariant to `a` too. (Is that our current understanding of this issue?)

**Comment by rgiordan** [comment]
I think that's a good idea.  The tests are currently disabled.  Next pull request I'll delete those tests and close this issue.

**Comment by rgiordan** [comment]
Tests deleted in https://github.com/jeff-regier/Celeste.jl/pull/59
