### ISSUE TITLE
test that joint inference improves the elbo for `validate_on_stripe82.jl`

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#490]

**Comment by agnusmaximus** [comment]
Hmm, I'm writing tests for checking that the gradient is around 0. For some reason the gradient doesn't get close to zero even for a small test case with 4 sources.

Some values are very close to zero while others are somewhat large, for example
```c++
Testing gradient: [-0.00181303 5.79939e-5 7402.33 -3.01851e-5; 0.000542868 0.000977167 4539.65 -1.7806e-5; 7.09895 8.28931 9.35291 0.0120433; -2.73603e-6 2.36145e-7 -7.70259 -0.00111664; -1.31593e-8 1.30052e-9 0.00781646 5.30356e-10; -1.33913e-6 1.6402e-7 0.103393 6.83507e-10; -9.08232e-8 -3.80932e-9 -0.156973 -3.48969e-11; 5.35934e-6 -7.18216e-7 -0.209034 -3.20594e-9; -64.3242 8.95438e-10 -98.2321 2.98854e-10; -17104.8 -1.34462e-7 -1617.61 -4.77326e-9; 7.35681e-9 -3.23348e-10 0.00624837 -9.06917e-11; -3.56679e-8 1.59933e-9 -0.0332802 1.09912e-10; -4.7895e-8 -7.51561e-10 -0.292726 -3.39611e-10; 1.38229e-8 -7.23356e-10 0.129662 4.87916e-11; -3.37508e-9 2.78862e-9 -3.46173 8.61304e-12; -4.39446e-7 8.17847e-9 0.219937 4.75631e-10; 3.02029e-6 -3.80225e-9 -0.843352 -1.26374e-9; 7.40276e-7 2.63335e-10 0.181155 -1.62447e-10; -8.74113e-6 -7.23331e-8 2.60293 6.20227e-10; 8.45445e-5 -7.59519e-7 -7.71086 5.91599e-9; -25.798 -1.8013e-6 -83.4468 1.05932e-8; 1.25117e-5 -1.5208e-6 -17.5431 1.20352e-8; 7.17888e-9 -6.51645e-10 44.0323 -2.20988e-11; 3.80516e-7 7.92448e-9 -66.3197 -9.31433e-10; -7481.16 5.63317e-8 -1245.0 -1.94912e-9; 8.05061e-7 2.23903e-8 -150.135 -2.43161e-10; 17769.3 1488.8 2103.08 132.636; 22169.7 1644.47 2275.63 132.636; -0.0724174 -0.0332141 -0.567054 -5.70876; -0.234826 -0.0193662 -0.610306 -3.05219; -11.6344 -5.38207 -13.6711 -0.176822; -11.6344 -5.07476 -11.0592 -0.176822]
```
(This is the result of DeterministicVI.elbo(...).d for 4 sources) 

Some parameters are definitely going to zero, but others are not changing at all. Am I misunderstanding something? Any info would be awesome!

**Comment by jeff-regier** [comment]
There might be two things going on here. First, these parameters may have different scales, so "close to zero" means different things for different parameters. Think of the function `x^2 + 1000000y^2`. At `(0.001, 0.001)` we're pretty close to the minimum, but the partial derivative wrt `y` is much greater. 

You might try adjusting for the scales of the parameters by dividing the gradient by the diagonal of the Hessian. That rescaled vector should be near 0.

Second, I notice that light source 3 is much farther from 0 for some partial derivatives. Could there be a bug? If so, it'll be easier to track it down once you're adjusting for the scales of the parameters.

**Comment by agnusmaximus** [comment]
I see, thanks!! I'll check this out

**Comment by andreasnoack** [comment]
Aren't we computing the Newton update `H\s` for each iteration anyway? Wouldn't `dot(s,H\s)` then be a good and cheap metric to use?

**Comment by jeff-regier** [comment]
We never explicitly form the Hessian `H` for the whole objective function, just for blocks of the Hessian `H_i` along the diagonal. (Each block corresponds to the parameters for one source. Our optimization method is block coordinate ascent, with blocks updated by Newton steps.) The entries of the Hessian off the block diagonal not all zero. So computing `H \ s` may not be straightforward. I'd have to think whether showing `dot(s_i, H_i \ s_i)` is near 0 for each block i suffices. Probably?

But is there a drawback  to verifying convergence by checking that `g[j] / H[j,j]` is near 0 for all coordinates j? This is just for a unit test, not for deciding when to terminate optimization.

**Comment by agnusmaximus** [comment]
Hmm, just to clarify, there are 32 values for each set of parameters and 4 sources. So the hessian will be 128x128 (32x4). If `Diag` is the diagonal of the hessian (length 128), then `Diag[1:32]` is the scaling factor for the parameters of the first source, `Diag[33:64]` is the scaling factor of the parameters of the second source and so on?

It seems like after scaling, there are only a few larger values (> 1) which I'm not sure why that happens. I'm currently tweaking the # of newton steps, etc to see if this changes things.

**Comment by jeff-regier** [comment]
Yes, that's what I was proposing, except that I thought you'd make one source active at a time, to compute its block of Hessian. That way you could check all ~500 sources optimized by `validate_on_stripe82.jl`. But for just 4 sources your way works just fine. Actually, with only 4 sources you might try doing what Andreas suggests.

Would you try your test with just 1 light source (rather than 4)? Then does the gradient, either rescaled or not, go to 0? Now that I think about it, we may need to modify the algorithm slightly to be sure it converges.

**Comment by agnusmaximus** [comment]
Hmm, yeah I tried individually calculating the gradient and it's not really 0. For each set of parameters, a lot of values are super tiny, but there are a few that are .5 and one or two that are >1. 

e.g:
```c++
Unscaled gradient:
32×1 Array{Float64,2}:
   11.9227     
    7.20941    
    4.08974    
    0.00380968 
   -0.000191797
   -0.00082615 
   -0.000177889
   -0.0328016  
   -0.0158634  
   -0.0496955  
   -1.12153e-5 
    0.000105859
   -0.000189563
   -0.000158401
    4.93951e-5 
    0.00168747 
   -0.0202598  
   -0.00114723 
    6.34261e-5 
    0.000592677
   -0.239344   
    0.00105304 
   -5.15711e-5 
   -0.00256566 
   -0.0297564  
   -0.00217096 
 2112.05       
 2280.3        
   -0.0398395  
   -0.0363915  
   -8.35535    
   -8.35514    
Scaled gradient:
32-element Array{Float64,1}:
 -3.72379e-10
 -1.42591e-10
 -0.0556629  
 -1.00554e-5 
  6.81167e-6 
  4.07686e-6 
  8.38781e-6 
  7.17951e-6 
  3.53658e-7 
  4.73091e-9 
  8.58173e-5 
 -4.40778e-5 
  1.2407e-5  
  3.40614e-5 
 -8.46665e-6 
 -6.39409e-6 
  6.95117e-6 
  2.47822e-6 
 -3.70997e-5 
 -1.02419e-6 
  1.09213e-5 
 -4.8606e-7  
  2.30332e-6 
  7.22916e-8 
  6.9581e-9  
  1.99913e-8 
 -0.88594    
 -1.02703    
  0.0647379  
  7.20708    
  0.141144   
  8.25605   
 Is near zero: false

**Comment by agnusmaximus** [comment]
With more iterations the gradient does go closer to 0, but after a certain point it doesn't get any closer

**Comment by jeff-regier** [comment]
With just that one light source, do you get the same results with joint inference as with single infer?

It's also possible that this is what machine precision looks like for our problem, because of how we transform the constrained optimization problem to an unconstrained problem. I'd wonder about that if single infer also finds "optimizers" whose gradients have large norms.

**Comment by jeff-regier** [comment]
You might try setting the tolerance lower too when you call `maximize_f`, e.g. `xtol_rel=1e-8` and `ftol_abs=1e-7`.

**Comment by agnusmaximus** [comment]
Ah the previous parameters were still from optimizing 4 light sources. With optimizing only one light source:

joint_infer
```c++
Scaled gradient
32-element Array{Float64,1}:
 -3.72379e-10
 -1.42591e-10
 -0.0556629  
 -1.00554e-5 
  6.81167e-6 
  4.07686e-6 
  8.38781e-6 
  7.17951e-6 
  3.53658e-7 
  4.73091e-9 
  8.58173e-5 
 -4.40778e-5 
  1.2407e-5  
  3.40614e-5 
 -8.46665e-6 
 -6.39409e-6 
  6.95117e-6 
  2.47822e-6 
 -3.70997e-5 
 -1.02419e-6 
  1.09213e-5 
 -4.8606e-7  
  2.30332e-6 
  7.22916e-8 
  6.9581e-9  
  1.99913e-8 
 -0.88594    
 -1.02703    
  0.0647379  
  7.20708    
  0.141144   
  8.25605    Is near zero: false
```

Single infer
```c++
Scaled gradient
32-element Array{Float64,1}:
 -2.49982e-10
 -9.4969e-11 
 -0.0555957  
 -6.84282e-6 
  4.6571e-6  
  2.85819e-6 
  2.44343e-6 
  4.89553e-6 
  4.43383e-9 
  3.23015e-9 
  1.74596e-5 
 -9.12487e-6 
  3.23604e-6 
  7.38145e-6 
 -5.85063e-6 
 -4.34676e-6 
  4.74082e-6 
  1.67147e-6 
 -7.57301e-6 
 -2.09663e-7 
  2.21448e-6 
 -1.09937e-7 
  1.61012e-6 
  4.96117e-8 
  4.7624e-9  
  1.37073e-8 
 -0.885925   
 -1.02704    
  0.0420799  
  7.23723    
  0.141111   
  8.25608    Is near zero: false
```

**Comment by agnusmaximus** [comment]
Seems like the larger values are close to each other. The difference may be that with single infer 20 newton steps are performed all at once, while with joint infer, multiple updates of 5 newton steps are taken. 

I'll try tweaking xtol_rel and ftol_abs

**Comment by jeff-regier** [comment]
For single infer, with one light source, what value do you get back from `dot(g, H \ g)`, where `g` is the gradient and `H` is the Hessian?

In joint infer, you might also try setting `max_iters=50` everywhere you call `maximize_f`. I'll need to think more about how to make the algorithm converge for sure with fewer iterations. There's an issue with each source having it's own trust region radius that I haven't thought through yet. In the meantime, you might as well set `max_iters=50`, so that each source is optimized to very high precision every time, making this into a standard block coordinate ascent algorithm. That way  you're not debugging two issues at once.

**Comment by agnusmaximus** [comment]
for single infer, `dot(g, H \ g)` gives me -2435.586519212405

I get a similar value with joint infer with max_iters=50

Update, yeah with max_iters the results from joint infer and single infer on one light source gives nearly the same results:

single_infer
```c++
 Scaled gradient
32-element Array{Float64,1}:
 -2.49982e-10
 -9.4969e-11 
 -0.0555957  
 -6.84282e-6 
  4.6571e-6  
  2.85819e-6 
  2.44343e-6 
  4.89553e-6 
  4.43383e-9 
  3.23015e-9 
  1.74596e-5 
 -9.12487e-6 
  3.23604e-6 
  7.38145e-6 
 -5.85063e-6 
 -4.34676e-6 
  4.74082e-6 
  1.67147e-6 
 -7.57301e-6 
 -2.09663e-7 
  2.21448e-6 
 -1.09937e-7 
  1.61012e-6 
  4.96117e-8 
  4.7624e-9  
  1.37073e-8 
 -0.885925   
 -1.02704    
  0.0420799  
  7.23723    
  0.141111   
  8.25608    Is near zero: false
```

joint_infer (max_iter=50)
```c++
 Scaled gradient
32-element Array{Float64,1}:
 -1.60709e-10
 -6.15931e-11
 -0.0555421  
 -4.34744e-6 
  2.93096e-6 
  1.7227e-6  
  9.74727e-7 
  3.09439e-6 
  1.95929e-9 
  2.03835e-9 
  7.00604e-5 
 -3.57331e-5 
  2.38656e-6 
  2.34755e-5 
 -3.67977e-6 
 -2.74107e-6 
  2.99836e-6 
  1.06649e-6 
 -3.03358e-5 
 -8.43143e-7 
  3.18982e-7 
 -4.62808e-7 
  1.00811e-6 
  3.13046e-8 
  3.0076e-9  
  8.73997e-9 
 -0.885857   
 -1.02704    
  0.0605121  
  7.22394    
  0.141112   
  8.25608    Is near zero: false
```

**Comment by jeff-regier** [comment]
I think figured it out...I should have thought of this earlier. The gradient isn't supposed to be 0 because some of the constraints are active. The `Transform` module converts the constrained optimization problem to an unconstrained optimization problem, and it's the latter problem that should have a nearly 0 gradient, not the former. If you look at optimizer (for the constrained problem), I'm pretty sure you'll see that the non-zero entries of the rescaled gradient correspond to coordinates of the optimizer near their bounds.

If you can figure out how to get at the gradient of the unconstrained problem, that's the one to use. I'm also glad to discuss it tomorrow.

**Comment by agnusmaximus** [comment]
I see, that makes sense. Maybe instead of testing the gradient, would it be equivalent to just check that all the sources have converged via the return value of the optimizer? (The optimizer returns whether the optimized source converged or not, which was how I was determining when to stop optimization).

**Comment by agnusmaximus** [comment]
For now I'll look into getting the gradient of the unconstrained problem

**Comment by andreasnoack** [comment]
> `dot(g, H \ g)` gives me `-2435.586519212405`

This is a norm so it ought to be non-negative-ish. Is the Hessian almost singular?

Update: Just realized that we are maximizing so `H` is negative definite, right? Sorry for the noise.

**Comment by jeff-regier** [comment]
That's it, I think

**Comment by agnusmaximus** [comment]
Cool, so I checked the objective value achieved by both single infer and joint infer on stripe82 and joint infer achieves the better score. 

```c++
Score single: -1.420301499707826e8
Score multi: -4.85172164777906e6
```

**Comment by jeff-regier** [comment]
That's great news!
