### ISSUE TITLE
joint inference should optimize the fft elbo

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#491]

**Comment by jeff-regier** [comment]
I think the easiest way is to pass a `use_fft` flag to `one_node_joint_infer`. If true, `one_node_joint_infer` should call `maximize_f` like it's done [here in `infer_source_fft`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/DeterministicVIImagePSF.jl#L51-L54). @agnusmaximus -- Would you mind making this change?

**Comment by agnusmaximus** [comment]
Sounds good, I'll do that

**Comment by jeff-regier** [comment]
Thanks Max!
