### ISSUE TITLE
Version the GalSim FITS file

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#494]
Right now the make/test system doesn't have any good way to know when it should download a new GalSim FITS file and an out-of-date FITS file can cause broken tests and other unexpected behavior which has already bitten us several times. Also, checking out old git commits doesn't work, because you can't easily get the correspding old FITS file. We could just add a Makefile dependency on, say, `test_case_definitions.py` but I fear that will be fragile, and it won't solve the latter problem. I think we should add a version indicator to the FITS filename, so it's `galsim_test_cases_VVV.fits`. There are a lot of ways we could implement it.

Here's an idea: when `generate_test_images.py` generates the FITS file, it includes the first 10 characters of the `md5sum` of the generated file in the filename, and write the filename to `benchmark/galsim/current_fits_filename.txt`, which is checked into git. The `Makefile` uses that file to know what to fetch, and `GalsimBenchmark.jl` uses that file to know what to read. Or, the Makefile sets up a symlink. Something like that. Some benefits:

1) When a new FITS file is generated, it shows a git change, so the developer doesn't forget to address it. (Did you mean to make a new FITS file? If so, upload it.)

2) If the developer who generated the new FITS file forgets to upload it, it causes an immediate error for others. (Maybe it could cause an error for the developer sooner, like with a git hook, but I don't think there's a great way to do it.)

3) If one checks out a previous commit and runs the tests, it pulls the corresponding version of the FITS file automatically. (So `git bisect` works easily, for example.)

If you have a simpler idea let me know, I'm all for simplicity.

**Comment by jeff-regier** [comment]
Sounds like a good solution to me
