### ISSUE TITLE
joint inference with FFT requires 60 GB of memory

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#506]
Running `validate_on_stripe82.jl --joint --fft` takes 60 GB of memory! Not sure if it's those fsm matrices or what.

**Comment by agnusmaximus** [comment]
Cool, I think reallocating during optimization reduces the memory (if I'm interpreting it right). Here's a result from a `julia validate_on_stripe82.jl --joint --fft` run:

```c++
[1] INFO: Done fitting elboargs. Elapsed time: 5895.519572857
6078.256404 seconds (7.40 G allocations: 868.343 GB, 32.84% gc time)
celeste: 585 objects
coadd catalog: 684 objects
/global/homes/a/agnusmax/.julia/v0.5/Celeste/test/data/4263/5/119/photoObj-004263-5-0119.fits
primary catalog: 1164 objects
matched celeste catalog: 417 objects
matched coadd catalog: 417 objects
matched primary catalog: 417 objects
12×6 DataFrames.DataFrame
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.243098  │ 0.409799  │ -0.1667    │ 0.0525113 │ 417 │
│ 2   │ missed_stars │ 0.0263789 │ 0.0719424 │ -0.0455635 │ 0.0111926 │ 417 │
│ 3   │ missed_gals  │ 0.0455635 │ 0.0359712 │ 0.00959233 │ 0.0114188 │ 417 │
│ 4   │ mag_r        │ 0.189753  │ 0.295516  │ -0.105763  │ 0.0221145 │ 416 │
│ 5   │ color_ug     │ 1.25994   │ 0.726995  │ 0.532943   │ 0.0574063 │ 370 │
│ 6   │ color_gr     │ 0.30301   │ 0.218243  │ 0.0847671  │ 0.0180063 │ 413 │
│ 7   │ color_ri     │ 0.18629   │ 0.198449  │ -0.0121588 │ 0.0262932 │ 416 │
│ 8   │ color_iz     │ 0.285698  │ 0.174804  │ 0.110893   │ 0.0248973 │ 417 │
│ 9   │ gal_fracdev  │ 0.260406  │ 0.239862  │ 0.020544   │ 0.0246467 │ 173 │
│ 10  │ gal_ab       │ 0.189946  │ 0.153193  │ 0.0367522  │ 0.0118773 │ 173 │
│ 11  │ gal_scale    │ 1.54675   │ 0.632864  │ 0.913888   │ 0.849523  │ 173 │
│ 12  │ gal_angle    │ 17.6112   │ 14.2396   │ 3.37164    │ 1.87582   │ 81  │
```

The process does take a very long time though (this is 10 iters)... and the GC time is pretty high (maybe since it's doing a bunch of the same allocations over and over). 

Maybe there's a julia way to mark the fsm_mat as delete immediately or something?

**Comment by agnusmaximus** [comment]
Hmm, the results look a bit worse than with single infer for some reason... looking into that...

**Comment by agnusmaximus** [comment]
Hmm, I seem to get some errors with `Pkg.update` (`GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)`), has anyone seen this before?

**Comment by jeff-regier** [comment]
I'm not sure about the git error. Maybe try updating from the command line
with git rather than going through the Julia repl. At worse you can delete
the Celeste directory and clone a fresh version.

Looks like it's mainly position that is off. It's off by a lot though. Is
the final elbo value higher with the --joint flag than without it?

How many threads were you using? That is pretty high GC time.

**Comment by agnusmaximus** [comment]
I was using 1 thread. I still have to try running without the --joint flag (currently I get some sort of assertion error when I run without --joint, but I think this is related to the `Pkg.update` error).

**Comment by agnusmaximus** [comment]
Hmm, I seem to get an assertion error `ERROR: LoadError: AssertionError: all(param .>= sb.lb)` when running with just `--fft`.

**Comment by jeff-regier** [comment]
That's issue #415 ... I suspect it has to do with Transform.jl . I was thinking of working on that once PR #519 is merged, if the issue persists.

In the meantime, if you
```
export JULIA_NUM_THREADS=4
```
beforehand, then the error will get caught and them problematic light source will be excluded from the score.

**Comment by agnusmaximus** [comment]
I see interesting. I ran into that problem with `-joint-infer -fft`, but got around that by using the default optim params. I'll see if the same trick works with just `-fft`. The issue could be deeper than that though, so this might not be a viable fix.

**Comment by agnusmaximus** [comment]
hmm yeah, nvm the same trick (using default optim params), doesn't work with just -fft for some weird reason..

**Comment by jeff-regier** [comment]
I think I've partly figured out the `position` error. When you run with the `--joint` flag, the positions are farther off than should be possible:
```
julia> tail(sort(rae["celeste_err"][:, [:position, :objid]]))
6×2 DataFrames.DataFrame
│ Row │ position │ objid               │
├─────┼──────────┼─────────────────────┤
│ 1   │ 6.20221  │ 8647474692482204561 │
│ 2   │ 6.95266  │ 8647474692482138448 │
│ 3   │ 8.97962  │ 8647474692482203943 │
│ 4   │ 9.32337  │ 8647474692482204177 │
│ 5   │ 9.80174  │ 8647474692482203817 │
│ 6   │ 10.8956  │ 8647474692482204315 │
```

That's over 10 pixels off. At that distance, it's not even finding the same star as it was initialized to.  For single infer (both mog and fft), the error is never more than 1.5 pixels. That's because I set the default `loc_width=1e-4` in `maximize_elbo`. 

1e-4 degrees = 0.36 arcseconds = 0.91 pixels in either direction, so maximum difference from primary is a couple of pixels. On stripe 82, primary's position is never wrong by more than a pixel or two, or else we excluded it from scoring. Thus, Celeste can't be wrong by more than a couple of pixels either (triangle inequality).

Somehow joint inference is overriding the default value of `loc_width`, I think, but I'm not sure where it's happening.

**Comment by agnusmaximus** [comment]
Hmm does that happen regardless of whether the `--fft` flag is added or not?

**Comment by agnusmaximus** [comment]
I'll see if this is related to using the default julia optim params (probably not, but I'll check just in case).

**Comment by jeff-regier** [comment]
Nice. It runs on my machine without using more than 6 GB now.

**Comment by agnusmaximus** [comment]
Great! The high garbage collection time is probably related to doing these repeated allocations. I wonder if there's a Julia method to mark a piece of memory as delete immediately (couldn't find anything by looking online). I'll bring this up during our Wednesday meeting.
