### ISSUE TITLE
unify `GalsimBenchmark` and `Stripe82Score`

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#510]
Maybe call the unified module something like `AccuracyBenchmark`.

We'd like to be able to pick arbitrary combinations of 1) a ground truth catalog (either `coadd`, or a synthetic catalog drawn from the Celeste model), 2) an image generation routine (either galsim, `test/Synthetic.jl` or SDSS), and 3) prediction catalog (`primary`, Celeste MOG, or Celeste FFT).

It's tempting to make the synthetic catalog have the same format as `coadd`, so the script doesn't have to "know" the source of the ground truth, and thus can't possibly treat `coadd` and the synthetic catalog differently. But I don't think that's the way to go, because the `coadd` catalog has a lot of quirks.

**Comment by jeff-regier** [comment]
@gostevehoward  We could go over the `Stripe82Score.jl` code tomorrow before or after the DESI meeting if you like. I'm sure you could figure it out too. The basic idea is that there's a function to load each type of catalog (i.e., primary, coadd, celeste) into a data frame having a common format. These functions are called `load_primary`, `load_coadd`, and `celeste_to_df`. (The first two read from disk, the third takes a vector of results read from disk---for better or worse, that's why the naming convention is slightly different for `celeste_to_df`.) Because the loaded data frames have a common format, any pair can be compared by calling `get_err_df`. You'd presumably create a new one of these functions for the galsim catalog, something like `gimsim_to_df`, that calls `load_ce!` (`ce` stands for `CatalogEntry`) if your galsim catalog is stored as a vector of `CatalogEntry` instances.

You'll notice `load_primary` and `load_coadd` return data frames with a lot of `NA` values. That's because there's no obvious mapping from those catalogs to the common data frame format for some fields, for some types of light sources. You wouldn't need to worry about `NA` values through for the galsim catalog, I think.

**Comment by gostevehoward** [comment]
Here are the pieces that need to be put together, I think:

- [x] `load_coadd_catalog(filename) -> DF` (already done in [load_s82](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L93), I've made some refactorings). The DF this already returns will become the common catalog DF format throughout this benchmark module.
- [x] `generate_catalog_from_celeste_prior(num_sources, seed) -> DF` (mostly already done in [generate_catalog_from_prior.jl](https://github.com/jeff-regier/Celeste.jl/blob/master/benchmark/galsim/generate_catalog_from_prior.jl), I've changed it to return the common catalog DF format)
- [x] a short script to run `load_coadd_catalog` or `generate_catalog_from_celeste_prior`, writing the catalog to a CSV with some unique hash appended to the filename. The CSV is necessary for the GalSim image generation (which runs in Python in a VM, so would be awkward to call directly from Julia) and the hash will ensure we uniquely identify catalogs (as we do with GalSim FITS files currently)
- [x] a Python script to generate FITS images from such a catalog CSV, using GalSim, with the catalog embedded in the FITS file. This is mostly already done in [`galsim_field.py`](https://github.com/jeff-regier/Celeste.jl/blob/master/benchmark/galsim/galsim_field.py) but needs refactoring to read the common catalog DF format.
- [x] a function to load FITS image from either of the above and generate the `Image` and `CatalogEntry` objects to pass to Celeste; this just needs to be pulled out of [`GalsimBenchmark.jl`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/GalsimBenchmark.jl#L295)
- [x] a driver script that runs MOG or FFT Celeste with any of the three images sources (SDSS or one of the generated FITS files), writing JLD results. This should be short, mostly just calling existing code.
- [x] a function to load `primary` predictions to the common catalog DF format; this is done in [`load_primary()`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L177), which should receive the same refactorings as `load_s82`, and maybe the two can share more code
- [x] a function to load JLD celeste results to the common catalog DF format, mostly already implemented by [`celeste_to_df`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L268) and friends
- [x] a script to convert the SDSS primary prediction catalog from its FITS format into the common catalog CSV format (for scoring)
- [x] a function to compare any number of prediction catalogs to a ground truth catalog, mostly already done in [`get_scores_df`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L460) and friends
- [x] a standalone script to call the above scoring function with a specific set of ground truth and prediction catalogs

**Comment by gostevehoward** [comment]
@jeff-regier I do have some questions after all:

1. [This code](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L23) seems to treat the magnitudes in the coadd catalog as "Pogson magnitudes", using the formula
    ![pogson](http://mathurl.com/jhjzp3z.png)
    (The functions [`fluxes_to_color`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L167) and [`load_ce!`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L250) are consistent with this.) However, [this page](http://www.sdss.org/dr12/algorithms/magnitudes/) says SDSS catalog magnitudes are in asinh magnitudes:
    ![asinh](http://mathurl.com/zpfw5f9.png)
    with "softening parameter" *b* different for each color band. Which is the correct one to use in Celeste?
2. [`load_s82`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L123) (i.e., loading the coadd catalog) uses `psfmag`, `expmag`, etc., converting to flux with `mag_to_flux` for the reference band. [`load_primary`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/Stripe82Score.jl#L177) uses `psfflux`, `expflux`, etc. directly. Why the difference? Is it just a matter of circumstance that one file has mags and the other has fluxes?

**Comment by jeff-regier** [comment]
Stripe 82 and primary have similar, but different, formats. One is in flux,
one is magnitude. Both are SDSS, but the stripe82 numbers come to us from
the casjobs web app:
http://skyserver.sdss.org/CasJobs/

(I was stumped for days once figuring out that one of these two sdds
catalog reports galaxy angle in degrees counterclockwise while the other
reports it in degrees clockwise. What a nightmare.)

I wasn't aware of the distinction between Pogson and asinh magnitude. We
could easily be getting this wrong, since it looks like the two are similar
except for faint light sources. Potentially a great catch. Would you ask
David about it, and cc me or the inference list?

**Comment by jeff-regier** [comment]
Also, I wonder if we should be using cModelMag instead of picking between
devMag / expMag for galaxies, or whether it matters. I read now that
there's something called petroMag too.

**Comment by gostevehoward** [comment]
I'll mention it in my email to David.

**Comment by rcthomas** [comment]
The asinh magnitudes are the luptitudes I mentioned on Slack.  All SDSS results are reported in these so if you look at magnitudes in the low S/N regime to compare to SDSS you will want to compute them.

**Comment by gostevehoward** [comment]
Thanks, Rollin. I explicitly CC'd you on the email just now. (If the matter is closed, Jeff, you can just ping that thread.)

**Comment by gostevehoward** [comment]
Remaining tasks:

- [x] debug differences between `validate_on_stripe82.jl` and the new AccuracyBenchmark implementation, fix until the new implementation's results are "close enough" to the old one's

Broken out in separate issues:
- [ ] bring back `error_sds` field in galsim benchmarks output -> #617 
- [ ] implement asinh magnitudes as described above (never heard back from anyone on the email thread, but I think Rollin answered the question) -> #618 
- [ ] a script to generate FITS images from a catalog DF using [`Synthetic.jl`](https://github.com/jeff-regier/Celeste.jl/blob/master/test/Synthetic.jl), i.e., drawing images from the Celeste model, again with catalog embedded in the FITS file. -> #619

**Comment by jeff-regier** [comment]
Closed by #602 ?

**Comment by gostevehoward** [comment]
Sure, I'll break out individual issues for the above three unchecked tasks.
