### ISSUE TITLE
multi-node Celeste run

### ISSUE THREAD

**Issue by rcthomas** [jeff-regier/Celeste.jl#514]
Run Celeste using O(10) Cori-KNL nodes.

**Comment by jeff-regier** [comment]
@kpamnany -- I've placed a list of square regions of the sky for you in
```
/global/homes/j/jregier/sky_boxes
```
These boxes are sorted by expected runtime. The most difficult ones appear first.

**Comment by kpamnany** [comment]
The first box alone (354.5, 355.0, -2.5, -2.0) has 8983 primary sources after the MIN_FLUX cut. At 2 seconds per source (which we aren't at yet I think?), that's 30 minutes of runtime, given 8 threads. If each box has roughly similar, the load imbalance is likely going to be this much or more. This seems too much?

**Comment by jeff-regier** [comment]
I can make them smaller, but then we're going to have to load the data more times. Quarter square degree is really a good size as far as data loading goes. If we use sixteenth square degree regions then we have to load twice as much image data. Can we use all 288 threads on each node for one process once @keno has a Julia branch that supports local memory allocation / parallel GC?

**Comment by jeff-regier** [comment]
In the meantime, @kpamnany, you might use the `tac` command line utility to reverse the order of the list. Then the boxes will be sorted by computational difficulty in ascending order.

**Comment by kpamnany** [comment]
> Can we use all 288 threads on each node for one process once @keno has a Julia branch that supports local memory allocation / parallel GC?

272 threads, on Cori. And it is unlikely. Even for C/Fortran codes, not many can be made to scale that high with threads. And while Keno's change will hopefully help, it is not clear how much it will help.

Let's go with this for now and see what happens.

**Comment by jeff-regier** [comment]
Done yesterday
