### ISSUE TITLE
a 100-node Celeste run

### ISSUE THREAD

**Issue by rcthomas** [jeff-regier/Celeste.jl#515]
Submit a Celeste job to Cori-KNL and have it run/complete before the hackathon.

**Comment by jeff-regier** [comment]
@rcthomas -- Does this need to done before the hackathon? I thought this is what we'd be doing during it.

**Comment by rcthomas** [comment]
My thinking is that if a simple 2- or 4-node run can be done before the hackathon and it works, we should just go ahead and change -N to 100 and submit such a run without the time pressure of having it complete during the 2-day window of the hackathon.  Why wait.

Put another way, we want to be doing *lots* of 100 node runs during the hackathon with quick turnaround under reservation, we better make sure there are no show-stoppers before we come in the door and start doing that.

Proceeding from an abundance of caution here.
