### ISSUE TITLE
for joint infer, position isn't constrained to remain near its initial position

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#523]
For joint infer, **each** call to `maximize_f` may change the position by as much as `1e-4` degree (= 0.92 pixels) in any direction. That adds up over multiple iterations---we may end up with a fitting a different astronomical object than we initialized to.

Instead I think we want to reuse the value returned by [`constrain_model!`](https://github.com/jeff-regier/Celeste.jl/pull/519/files#diff-d1870332c8c8c8506ce0b28517df94ddR190)  (once @jrevels merges the #519) for each call to `maximize_f` for a particular light source.

This issue was initially raised in #506.

**Comment by jeff-regier** [comment]
@agnusmaximus -- Right now in `joint_infer` you're calling the version of `maximize_f` that doesn't take a `transform` as an argument. Instead, you might pre-allocate a vector of transforms before calling `maximize_f` at all, the same way you create `ea_vec` ahead of time now. Basically duplicate [this call](https://github.com/jeff-regier/Celeste.jl/blob/master/src/deterministic_vi/maximize_elbo.jl#L126) to `get_mp_transform`. Then, in `joint_infer.jl`, directly call [this version of `maximize_f`](https://github.com/jeff-regier/Celeste.jl/blob/master/src/deterministic_vi/maximize_elbo.jl#L14) with the right transform rather than [this one](https://github.com/jeff-regier/Celeste.jl/blob/master/src/deterministic_vi/maximize_elbo.jl#L116). I think that should solve this issue because the transform stores the bounds, and the method I'm proposing keeps the bounds from getting re-initialized every time you call `maximize_f`. Does that make sense?

**Comment by agnusmaximus** [comment]
Great, yeah that makes sense. I'll probably get around to trying this later tonight or tomorrow. I'll let you know if I have any other questions!
