### ISSUE TITLE
Galsim fft does not work

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#529]
Galsim's fft fitting doesn't work.  I'm surprised, since I could run this before break.  I've spent a while trying to see what's going wrong, and so far I haven't been able to find anything.

Can other people run this?  Any ideas what changed in the last few weeks that could have made this happen?

```
$ benchmark/galsim/run_galsim_benchmark.jl --fft
Looking for latest FITS filename in '/home/rgiordan/.julia/v0.5/Celeste/benchmark/galsim/latest_filenames/latest_galsim_benchmarks.txt'
Reading '/home/rgiordan/.julia/v0.5/Celeste/benchmark/galsim/output/galsim_benchmarks_0b7bd50da4.fits'...
Found 130 extensions.
Running test case 'simple_star'
ERROR: LoadError: Base.LinAlg.PosDefException(5)
```

**Comment by rgiordan** [comment]
@jeff-regier @gostevehoward

**Comment by jeff-regier** [comment]
It doesn't work for me either now. Looks like it started throwing that error 2.5 weeks ago, with commit [3c15a3b0a6060ce5f6a499da5ddf673575c3ef74](https://github.com/jeff-regier/Celeste.jl/commit/3c15a3b0a6060ce5f6a499da5ddf673575c3ef74).

**Comment by rgiordan** [comment]
I'll assume you're on it?  A unit test may be advisable, too.

**Comment by jeff-regier** [comment]
Yeah, I'm on it. I don't think there's anything wrong with that commit though. Optim shouldn't be throwing the non-posdef errors ever. I thought I fixed them in a previous commit to Optim.jl.

Can you just skip the first galsim case in the meantime? The rest still work, right?

**Comment by jeff-regier** [comment]
I submitted a bug fix to Optim.jl. Until it's merged and tagged, you may want to use my fork.

```
julia> Pkg.rm("Optim")
julia> Pkg.clone("https://github.com/jeff-regier/Optim.jl.git")
julia> Pkg.checkout("Optim", "jcr/newton_tr_fix")
julia> Pkg.build("Optim")
```
