### ISSUE TITLE
inferred_values should be posterior expectations?

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#531]
@gostevehoward , I noticed that ```inferred_values``` in ```GalsimBenchmark.jl``` uses ```exp(r1)``` for the brightness estimate.  I think the correct value would be the posterior mean, which for a lognormal is ```exp(r1 + 0.5 * r2)```.  A similar comment extends to the colors.

I understand the temptation to use ```exp(r1)``` as the "zero-variance" estimate of the brightness.  Or perhaps you intended it to be the variational MAP.  (Or maybe you intend to estimate the log brightness -- but then you should report that, and associated errors, not the brightness.)  But I think that, from a decision theoretic point of view, the posterior mean is probably what we actually want, and that includes a contribution from the variance.

Do you agree?  This is a pedantic point, I know, and probably not practically importance because all our brightness variances are tiny.  But it seems worth clearing up.

**Comment by jeff-regier** [comment]
We're reporting L1 loss on the galsim dataset, so we return the median, since that minimizes L1 loss. (The mean minimizes L2 loss.)

**Comment by rgiordan** [comment]
I see, makes sense.
