### ISSUE TITLE
~4-5x slowdown in benchmark_one_light_source on Julia 0.6

### ISSUE THREAD

**Issue by andreasnoack** [jeff-regier/Celeste.jl#544]
In short
### 0.5
```julia
[1]<1> INFO: Done fitting elboargs. Elapsed time: 12.527314414
```
### 0.6
```julia
[1]<1> INFO: Done fitting elboargs. Elapsed time: 56.20631669
```
The timings are recorded on my Mac with Celeste 1ad5402f4f7635568ab10af5e90e75a7b2e00533
See full profile output in https://gist.github.com/andreasnoack/45a11627c198dcb681fc1fbf4961a444

**Comment by andreasnoack** [comment]
## Julia 0.5

<img width="1203" alt="screen shot 2017-01-27 at 2 34 14 pm" src="https://cloud.githubusercontent.com/assets/505001/22384778/ccd36cba-e49d-11e6-9a67-590bb8ee492e.png">


## Julia 0.6
<img width="1203" alt="screen shot 2017-01-27 at 2 32 53 pm" src="https://cloud.githubusercontent.com/assets/505001/22384735/9f3b4656-e49d-11e6-8229-d00486812bd2.png">

**Comment by Keno** [comment]
Do you have updated flame graphs after your fix? Also, just to be sure that you know about @shashi's branch of ProfileView that's a lot faster.

**Comment by andreasnoack** [comment]
This is with @shashi's branch. I have given up on the official version. Too slow. Sad! I think I'll create an issue with a flame graph on the one-source-benchmark and update it as we optimize the code. Creating the graph is a little cumbersome, though. I couldn't use load the profile data from the JLD file on 0.5 because the representation of `StackFrame` has changed so I had to rebuild a version of `-0.6` where `ProfileView` works just to make the graph.
