### ISSUE TITLE
Set up performance tracking CI

### ISSUE THREAD

**Issue by Keno** [jeff-regier/Celeste.jl#546]
We should set up CI to track how we're doing on performance over time. Julia Computing has compute resources for both Xeon and KNL that this could run on. cc @tanmaykm @nkottary. Let's start with setting this up on anubis. Basically all I want is running the benchmark scripts and recording execution times for now. Once that works, we should also automatically generate flame graphs.

**Comment by jeff-regier** [comment]
Any progress with this issue @keno? We only have about a month to work on optimizing the code before GB, so building a dashboard might not be worth doing if it can't be done quickly.
