### ISSUE TITLE
One light source profile

### ISSUE THREAD

**Issue by andreasnoack** [jeff-regier/Celeste.jl#548]
At least until https://github.com/jeff-regier/Celeste.jl/issues/546 is running, I'll try to make a flame graph for `benchmark_one_light_source` here.

18 February 2017
<img width="1205" alt="screen shot 2017-02-18 at 2 44 33 pm" src="https://cloud.githubusercontent.com/assets/505001/23096375/30e19252-f5e9-11e6-973c-5980c958f642.png">

**Comment by jeff-regier** [comment]
Very interesting! A 10x speed up seems possible if we can avoid all the memory allocation / filling hessians with zeros / rearranging memory order for convolutions.

**Comment by jeff-regier** [comment]
Looks about right, no surprises here. The likelihood calculation takes almost all of the time. There are 3 hot spots in the likelihood calculation.

**Comment by jeff-regier** [comment]
Thanks Andreas for making the graph!
