### ISSUE TITLE
scaling beyond 8 threads

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#560]
We see almost no improvement in the runtime of `benchmark_sixteenth_degree.jl` when we increase the number of threads from 8 to 16, even though the reported time spent in GC doesn't change. Even beyond 4 threads the scaling numbers start getting bad. Are some threads going idle, waiting for other threads to finish?

**Comment by Keno** [comment]
With the newest optimization, we can get from 130s to 80s by going to 16 threads.
