### ISSUE TITLE
Start implementing configuration system and restore GalSim unit tests

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#575]
The GalSim unit tests depend on overriding `min_radius_pix` in `load_active_pixels!`. There's not an easy way to do this, since `load_active_pixels!` is several layers beneath the Celeste interface. I outlined a general "configuration system" approach to fixing this problem which would have side benefits, in PR #538. (This got verbal approval from Keno during the "hackaton".) There, I implemented a simpler workaround for the immediate problem, which involved a kind of ugly chain of callbacks. This would be even uglier in the new implementation in PR #574, so instead of perpetuating the ugliness I propose I implement the kernel of the "configurations system" idea and override `min_radius_pix` that way.

**Comment by jeff-regier** [comment]
The default arguments to `load_active_pixels!` ideally would work for both the galsim tests and the actual images. The problem isn't so much that the default `min_pixel_radius` is too small for galsim tests; it's that we aren't selecting active pixels in a smart way. #157 fixes that.

I hope someday we won't have both single and joint infer, and both mog and FFT point spread functions.

We probably can't do away with configuration stuff entirely so presumably this will be the way to go ultimately.
