### ISSUE TITLE
Tracking issue for SC17 scientific results

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#625]
@jeff-regier 

For the new SDSS results, should I just pick any random RCF from Stripe 82 other than 4263/5/119? Was there some logic behind that choice to begin with?

Did you have any thoughts on the results from #624? Is that the kind of numbers you'd like to see in the paper? It looks like errors are fat tailed, with more than expected (for a gaussian) falling within 1/2 SD and more than expected falling beyond 2 and 3 SDs. The disparity is larger for the GalSim synthetic field than for the Stripe 82 data. I could make histrogram/ECDF plots if you think it's worth examining and debugging (or if you think that'd be preferable to a table in the paper); otherwise I'll just generate those tables for a new RCF and get them into LaTeX form.

Here are the results from #624, copied for reference:

example output for stripe82 benchmark:

```
$ ./score_uncertainty.jl output/stripe82_coadd_catalog_69
f2cbf0f6.csv output/sdss_4263_5_119_predictions_31e4e8e48d.csv
Reading 'output/stripe82_coadd_catalog_69f2cbf0f6.csv'...
Reading 'output/sdss_4263_5_119_predictions_31e4e8e48d.csv'...
549 objids in common
5×5 DataFrames.DataFrame
│ Row │ field                    │ within_half_sd │ within_1_sd │ within_2_sd │ within_3_sd │
├─────┼──────────────────────────┼────────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ reference_band_flux_nmgy │ 0.336976       │ 0.384335    │ 0.506375    │ 0.577413    │
│ 2   │ color_log_ratio_ug       │ 0.602914       │ 0.712204    │ 0.876138    │ 0.952641    │
│ 3   │ color_log_ratio_gr       │ 0.67031        │ 0.779599    │ 0.894353    │ 0.948998    │
│ 4   │ color_log_ratio_ri       │ 0.601093       │ 0.697632    │ 0.859745    │ 0.928962    │
│ 5   │ color_log_ratio_iz       │ 0.56102        │ 0.721311    │ 0.885246    │ 0.945355    │
```

example output for galsim field:

```
julia score_uncertainty.jl output/celeste_prior_catalog
_7cfe0bafa6.csv output/celeste_prior_catalog_7cfe0bafa6_images_8f6f48a08d_predictions_857f3a0488.csv
Reading 'output/celeste_prior_catalog_7cfe0bafa6.csv'...
Reading 'output/celeste_prior_catalog_7cfe0bafa6_images_8f6f48a08d_predictions_857f3a0488.csv'...
500 objids in common
5×5 DataFrames.DataFrame
│ Row │ field                    │ within_half_sd │ within_1_sd │ within_2_sd │ within_3_sd │
├─────┼──────────────────────────┼────────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ reference_band_flux_nmgy │ 0.73           │ 0.742       │ 0.748       │ 0.758       │
│ 2   │ color_log_ratio_ug       │ 0.524          │ 0.564       │ 0.628       │ 0.676       │
│ 3   │ color_log_ratio_gr       │ 0.748          │ 0.762       │ 0.79        │ 0.84        │
│ 4   │ color_log_ratio_ri       │ 0.82           │ 0.832       │ 0.854       │ 0.872       │
│ 5   │ color_log_ratio_iz       │ 0.792          │ 0.812       │ 0.83        │ 0.85        │
```

**Comment by jeff-regier** [comment]
Hi Steve, 4263/5/119 was arbitrary. Any other RCF should be fine.

The Stripe 82 uncertainties look better than the galsim ones for color. Ideally 68%/95%/99% of color point estimates would be within 1/2/3 sds. I'd say those proportions are holding up pretty well for all but 6%--8% of the light sources. Those light sources are likely misfit by the model. The `within_half_sd` values seem kind of high too--especially given that the variational inference (w mean field-type assumptions) tends to underestimate variance rather than overestimate it.

`reference_band_flux_nmgy` is log normal, not normal, so we can't directly compare those to 68%/95%/99%. There's presumably a more general way to do this kind of thing.

**Comment by gostevehoward** [comment]
I was already taking the log of reference band flux in computing errors; my bad for not labeling it correctly.

In a move of extreme stupidity I forgot to take abs() of the errors in the above summary tables. Sorry! Here are corrected tables (though maybe there's still a serious bug somewhere):

For Stripe82:

```
│ Row │ field                        │ within_half_sd │ within_1_sd │ within_2_sd │ within_3_sd │
├─────┼──────────────────────────────┼────────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ color_log_ratio_gr           │ 0.222222       │ 0.449909    │ 0.717668    │ 0.867031    │
│ 2   │ color_log_ratio_iz           │ 0.256831       │ 0.533698    │ 0.814208    │ 0.921676    │
│ 3   │ color_log_ratio_ri           │ 0.17122        │ 0.346084    │ 0.663024    │ 0.801457    │
│ 4   │ color_log_ratio_ug           │ 0.227687       │ 0.411658    │ 0.684882    │ 0.832423    │
│ 5   │ log_reference_band_flux_nmgy │ 0.107468       │ 0.198543    │ 0.3898      │ 0.495446    │
```

For galsim (on a field drawn from the Celeste prior):

```
│ Row │ field                        │ within_half_sd │ within_1_sd │ within_2_sd │ within_3_sd │
├─────┼──────────────────────────────┼────────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ color_log_ratio_gr           │ 0.042          │ 0.084       │ 0.16        │ 0.266       │
│ 2   │ color_log_ratio_iz           │ 0.064          │ 0.146       │ 0.282       │ 0.4         │
│ 3   │ color_log_ratio_ri           │ 0.038          │ 0.074       │ 0.15        │ 0.222       │
│ 4   │ color_log_ratio_ug           │ 0.06           │ 0.114       │ 0.222       │ 0.302       │
│ 5   │ log_reference_band_flux_nmgy │ 0.014          │ 0.032       │ 0.054       │ 0.08        │
```

Here are corresponding Q-Q plots:
* [s82_plots.pdf](https://github.com/jeff-regier/Celeste.jl/files/866784/s82_plots.pdf)
* [galsim_plots.pdf](https://github.com/jeff-regier/Celeste.jl/files/866786/galsim_plots.pdf)

The summary is that
1. There are major outliers, presumably corresponding to misfit sources.
2. Even excluding the outliers, the posterior variance is too low.
3. Colors aren't bad in Stripe 82, are worse in GalSim, but reference band flux is way off in both.

It seems too far off, which makes me think there's still a stupid bug somewhere. I'll investigate.

Also these results are not with joint inference, but I guess we probably want joint inference used for these, so I'm re-running Celeste and will report the results.

**Comment by jeff-regier** [comment]
Thanks for the updates. Yes, those `log_reference_band_flux_nmgy` uncertainties are pretty far off--hopefully a bug. It would be useful to have another table like these for synthetic data drawn from the Celeste model too. Should make it easier to catch bugs, and to assess how much error is from model misfit (none in the case of synthetic data drawn from our model) rather than from variational inference (still present even for synthetic data from our model).

**Comment by gostevehoward** [comment]
OK, I'll need to implement #619 then, hopefully won't take too long.

I'll also generate a GalSim field from the Stripe82 ground truth so that we have a better apples-to-apples comparison. That is at least something I already have implemented.

**Comment by gostevehoward** [comment]
For what it's worth, here's output for GalSim imagery generated from the Stripe 82 coadd ground truth catalog, with joint inference enabled. It's a bit better than the Celeste prior catalog (especially `color_log_ratio_ug` but still a lot worse than the real imagery.

```
 Row │ field                        │ within_half_sd │ within_1_sd │ within_2_sd │ within_3_sd │
├─────┼──────────────────────────────┼────────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ color_log_ratio_gr           │ 0.121345       │ 0.223684    │ 0.359649    │ 0.527778    │
│ 2   │ color_log_ratio_iz           │ 0.0730994      │ 0.154971    │ 0.340643    │ 0.502924    │
│ 3   │ color_log_ratio_ri           │ 0.0935673      │ 0.178363    │ 0.333333    │ 0.552632    │
│ 4   │ color_log_ratio_ug           │ 0.156433       │ 0.437135    │ 0.824561    │ 0.925439    │
│ 5   │ log_reference_band_flux_nmgy │ 0.0570175      │ 0.112573    │ 0.244152    │ 0.387427    │
```

Q-Q plots: [s82_galsim_joint_plots.pdf](https://github.com/jeff-regier/Celeste.jl/files/868752/s82_galsim_joint_plots.pdf)

I'll work on #619

**Comment by gostevehoward** [comment]
@jeff-regier I'm confused about image dimensions in Celeste.

Consider `test/data/4263/5/119/frame-r-004263-5-119.fits`. When I open in `fv`, it calls the image 2048 x 1489:

![image](https://cloud.githubusercontent.com/assets/1097616/24335160/e6712fb0-122c-11e7-8350-918cfff9ea74.png)

Plotting in POW puts DEC on the x-axis and RA on the y-axis:

![image](https://cloud.githubusercontent.com/assets/1097616/24335163/008f0ff2-122d-11e7-8fe1-bad26cdb789e.png)

`ds9` also puts the image wider than tall, and marks the max x/y coords as 2048/1489:

![image](https://cloud.githubusercontent.com/assets/1097616/24335175/578699ec-122d-11e7-8cb8-59dc06ee11bd.png)

However, when I load the image in Celeste using `SDSSIO.load_field_images()`, the height and width are interchanged:

```
size(images[1].pixels) = (2048, 1489)
images[1].W = 1489
images[1].H = 2048
```

My guess is that FITS files take the "computer graphics" point of view, where the "first" axis (in indexing order) corresponds to "x", "width", or "horizontal", while the "second" axis corresponds to "y", "height" or "vertical". While Celeste takes the "matrix" point of view, where the "first" axis corresponds to "rows" or "height" while the "second" axis corresponds to "columns" or "width". I suppose this is fine, as long as we're always careful about which axis corresponds to RA and which to dec, and careful to adjust our interpretation of angle, according to the context. I just want to check if there's something I'm missing.

**Comment by gostevehoward** [comment]
I think I figured out one piece of the puzzle I hadn't recognized, which is that SDSS FITS files set up the WCS so that the first world axis (which we call RA) increases along the second image axis (which we call Y), and the second world axis (which we call Dec) increases along the first image axis (which we call X). So if you think of world coordinates as a tuple (ra, dec) and image coordinates as a tuple (x, y) then the world axes and image axes are transposed from each other. Very confusing. Maybe it's best to never think of RA and dec as an ordered tuple, but rather as just two named properties.

**Comment by jeff-regier** [comment]
Part of the issue may be that Julia's 2d arrays are column-major rather than row-major, whereas the fitsio library that FITSIO.jl wraps is C or C++.

**Comment by gostevehoward** [comment]
Having investigated many possible leads (and there are many more I haven't looked at), I suspect our old friend `min_radius_px` might be behind some of the problem with `log_reference_band_flux_nmgy` errors being way too large.

Compare this plot, made with single inference on a Synthetic.jl version of 4263/5/119 (code for that image generation forthcoming),

[s82_synthetic_single.pdf](https://github.com/jeff-regier/Celeste.jl/files/873189/s82_synthetic_single.pdf)

to this plot, in which I set `min_radius_px=40`, as in the GalSim tests:

[s82_synthetic_mrp40_error.pdf](https://github.com/jeff-regier/Celeste.jl/files/873191/s82_synthetic_mrp40_error.pdf)

The former doesn't look much better than the one for real SDSS imagery. In the latter, the variance underestimation is at least similar between `log_reference_band_flux_nmgy` and the color log-ratios.

It's far from decisive, but it's something.

**Comment by jeff-regier** [comment]
That seems like pretty strong evidence that small `min_radius_pix` throws off the brightness uncertainties--nice discovery. And it makes some sense. Uncertainties could easily be more susceptible to bias (from `min_radius_px` in this case) than the point estimates, so the point estimates could be fine while the uncertainties are off.

It occurred to me, for real data, model misfit could effect brightness much more than colors. Since color is a ratio, it won't be as susceptible to PSF & galaxy shape misfit. I'm glad you're working with `Synthetic.jl` data now, where model misfit isn't an issue. We should probably stick with that until all the problems there are worked out. Too much to debug at once otherwise.

For SC17, you might report primarily on UQ with `Synthetic.jl` data. For real data, you could just say the observed error correlates in some sense with model uncertainty. Perhaps partition the light sources into 2 groups: low model uncertainty and high model uncertainty. Then report the observed error for each group. Reducing model misfit on real data is future work / beyond the scope of this article.

**Comment by gostevehoward** [comment]
Here's an example of SDSS imagery (left) and Synthetic.jl imagery (right) generated from the corresponding coadd catalog. This is for RCF 3325/5/110, which I'm planning to use for SC17. (An arbitrary choice.)

![image](https://cloud.githubusercontent.com/assets/1097616/24380502/84727d08-1300-11e7-97e1-542035cebb33.png)

Note many of the brightest sources on the left (true image) are not present in the right (synthetic image). This is not a bug in synthetic image generation; those sources are not present in the coadd catalog CSV (as I verified manually), presumably because we filter on the SATURATED flag (I didn't verify this, just a guess).

**Comment by gostevehoward** [comment]
Here are some results for 3325/5/110. All predictions are using joint inference. All google drive spreadsheets are in [this folder](https://drive.google.com/open?id=0BzFj9pY3RKMcMmJIdG5IUHhRYlE).

## SDSS catalogs

* [Coadd catalog](https://docs.google.com/spreadsheets/d/1XQrVXsenlNjvrCN5p6oNNuU_40vIlzNntNhorvc3O74/edit?usp=sharing)
* [Primary catalog](https://docs.google.com/spreadsheets/d/1oH31S6rqZnAiC443eu_Z-_GvdVtiFU_3iUR07AYrFKs/edit?usp=sharing)

## Real imagery

* [Predictions](https://docs.google.com/spreadsheets/d/1KIPTYAQwEc1TpH6ul6nMU2oprCxWRURJJ6nyxjRuUDE/edit?usp=sharing)
* [Posterior errors](https://docs.google.com/spreadsheets/d/1Yf_NwoSdSfPdvsklooT1JVscpwv-uGYjN-2EOa0kl_Y/edit?usp=sharing)

```
Reading 'output/coadd_for_3325_5_110_99fd74846f.csv'...
Reading 'output/sdss_3325_5_110_primary_634c71449f.csv'...
Reading 'output/sdss_3325_5_110_predictions_e47f159b12.csv'...
449 objids in common
13×6 DataFrames.DataFrame
│ Row │ N   │ first     │ second    │ diff       │ diff_sd    │ field                         │
├─────┼─────┼───────────┼───────────┼────────────┼────────────┼───────────────────────────────┤
│ 1   │ 449 │ 0.0423163 │ 0.0534521 │ -0.0111359 │ 0.0133057  │ missed_stars                  │
│ 2   │ 449 │ 0.0400891 │ 0.122494  │ -0.0824053 │ 0.0141877  │ missed_galaxies               │
│ 3   │ 449 │ 0.362231  │ 0.269593  │ 0.0926385  │ 0.00820243 │ position                      │
│ 4   │ 449 │ 0.212049  │ 0.142557  │ 0.069492   │ 0.0115445  │ reference_band_flux_mag       │
│ 5   │ 449 │ 0.57848   │ 0.557264  │ 0.0212162  │ 0.0716471  │ reference_band_flux_nmgy      │
│ 6   │ 84  │ 22.5443   │ 17.5432   │ 5.00106    │ 1.81606    │ angle_deg                     │
│ 7   │ 166 │ 0.37757   │ 0.279591  │ 0.0979789  │ 0.0279923  │ de_vaucouleurs_mixture_weight │
│ 8   │ 166 │ 0.31018   │ 0.226424  │ 0.0837559  │ 0.0153144  │ minor_major_axis_ratio        │
│ 9   │ 166 │ 1.61707   │ 0.916526  │ 0.700546   │ 0.437235   │ half_light_radius_px          │
│ 10  │ 301 │ 1.31591   │ 0.597548  │ 0.71836    │ 0.0630535  │ color_log_ratio_ug            │
│ 11  │ 437 │ 0.475826  │ 0.210931  │ 0.264895   │ 0.0276529  │ color_log_ratio_gr            │
│ 12  │ 446 │ 0.254861  │ 0.123517  │ 0.131344   │ 0.0139769  │ color_log_ratio_ri            │
│ 13  │ 440 │ 0.479414  │ 0.168367  │ 0.311047   │ 0.0285608  │ color_log_ratio_iz            │
```

[Posterior z-score plots](https://github.com/jeff-regier/Celeste.jl/files/873998/3325_real_joint_errors.pdf)

## Synthetic imagery

* [Predictions](https://docs.google.com/spreadsheets/d/1LFumc2HgWTNQpxfsXU8zlqLblqQSEDCZR9yVCDniVhw/edit?usp=sharing)
* [Errors](https://docs.google.com/spreadsheets/d/1fOJEiGxQ6a21GHkzGU03izMaA09RAuuQRZ0s51GGG4c/edit?usp=sharing)

```
Reading 'output/coadd_for_3325_5_110_99fd74846f.csv'...
Reading 'output/sdss_3325_5_110_predictions_e47f159b12.csv'...
Reading 'output/coadd_for_3325_5_110_99fd74846f_synthetic_7e74f8e502_predictions_87733c7686.csv'...
449 objids in common
13×6 DataFrames.DataFrame
│ Row │ N   │ first     │ second    │ diff        │ diff_sd    │ field                         │
├─────┼─────┼───────────┼───────────┼─────────────┼────────────┼───────────────────────────────┤
│ 1   │ 449 │ 0.0534521 │ 0.0111359 │ 0.0423163   │ 0.0108335  │ missed_stars                  │
│ 2   │ 449 │ 0.122494  │ 0.242762  │ -0.120267   │ 0.0175286  │ missed_galaxies               │
│ 3   │ 449 │ 0.269593  │ 0.219312  │ 0.050281    │ 0.00745295 │ position                      │
│ 4   │ 449 │ 0.142557  │ 0.142642  │ -8.45464e-5 │ 0.0063548  │ reference_band_flux_mag       │
│ 5   │ 449 │ 0.557264  │ 0.485905  │ 0.0713587   │ 0.0482943  │ reference_band_flux_nmgy      │
│ 6   │ 84  │ 17.5432   │ 14.9404   │ 2.60282     │ 1.76872    │ angle_deg                     │
│ 7   │ 166 │ 0.279591  │ 0.427671  │ -0.148079   │ 0.0316488  │ de_vaucouleurs_mixture_weight │
│ 8   │ 166 │ 0.226424  │ 0.276097  │ -0.0496733  │ 0.0154058  │ minor_major_axis_ratio        │
│ 9   │ 166 │ 0.916526  │ 1.05412   │ -0.137595   │ 0.0360319  │ half_light_radius_px          │
│ 10  │ 342 │ 0.68972   │ 0.614233  │ 0.0754867   │ 0.0232899  │ color_log_ratio_ug            │
│ 11  │ 445 │ 0.220661  │ 0.21808   │ 0.00258053  │ 0.0080303  │ color_log_ratio_gr            │
│ 12  │ 448 │ 0.123334  │ 0.105533  │ 0.017801    │ 0.00504439 │ color_log_ratio_ri            │
│ 13  │ 448 │ 0.168184  │ 0.0814198 │ 0.0867645   │ 0.00774639 │ color_log_ratio_iz            │
```

[Posterior z-score plots](https://github.com/jeff-regier/Celeste.jl/files/873999/3325_synthetic_joint_errors.pdf)

## Synthetic imagery, `min_radius_pix=40`

```
Reading 'output/coadd_for_3325_5_110_99fd74846f.csv'...
Reading 'output/sdss_3325_5_110_predictions_e47f159b12.csv'...
Reading 'output/coadd_for_3325_5_110_99fd74846f_synthetic_7e74f8e502_predictions_173e58b2fb.csv'...
449 objids in common
13×6 DataFrames.DataFrame
│ Row │ N   │ first     │ second     │ diff       │ diff_sd    │ field                         │
├─────┼─────┼───────────┼────────────┼────────────┼────────────┼───────────────────────────────┤
│ 1   │ 449 │ 0.0534521 │ 0.00890869 │ 0.0445434  │ 0.0106271  │ missed_stars                  │
│ 2   │ 449 │ 0.122494  │ 0.25167    │ -0.129176  │ 0.0178998  │ missed_galaxies               │
│ 3   │ 449 │ 0.269593  │ 0.221648   │ 0.047945   │ 0.00766602 │ position                      │
│ 4   │ 449 │ 0.142557  │ 0.137473   │ 0.00508472 │ 0.00683522 │ reference_band_flux_mag       │
│ 5   │ 449 │ 0.557264  │ 0.322558   │ 0.234706   │ 0.0622928  │ reference_band_flux_nmgy      │
│ 6   │ 84  │ 17.5432   │ 15.2135    │ 2.32969    │ 1.78228    │ angle_deg                     │
│ 7   │ 166 │ 0.279591  │ 0.380341   │ -0.100749  │ 0.0298111  │ de_vaucouleurs_mixture_weight │
│ 8   │ 166 │ 0.226424  │ 0.249073   │ -0.0226493 │ 0.014696   │ minor_major_axis_ratio        │
│ 9   │ 166 │ 0.916526  │ 1.04545    │ -0.128921  │ 0.0307129  │ half_light_radius_px          │
│ 10  │ 342 │ 0.68972   │ 0.618192   │ 0.071527   │ 0.0232218  │ color_log_ratio_ug            │
│ 11  │ 445 │ 0.220661  │ 0.21775    │ 0.00291045 │ 0.00786911 │ color_log_ratio_gr            │
│ 12  │ 448 │ 0.123334  │ 0.104591   │ 0.0187431  │ 0.00501015 │ color_log_ratio_ri            │
│ 13  │ 448 │ 0.168184  │ 0.0828396  │ 0.0853447  │ 0.00762563 │ color_log_ratio_iz            │
```

[Posterior z-score plots](https://github.com/jeff-regier/Celeste.jl/files/874068/3325_synthetic_mrp40_joint_errors.pdf)

**Comment by jeff-regier** [comment]
Very interesting, seeing the coadd image and the synthetic image side-by-side. Probably `SDSSIO` isn't the right place to filter out saturate/bright/large light sources any longer. We'd rather render them in the synthetic data, I think. It's really just in `AccuracyBenchmark` that we'd want to filter them out for comparison because the coadd catalog isn't accurate for saturated light sources.

**Comment by gostevehoward** [comment]
Looks like, on 3325/5/110, with the latest code, setting `min_radius_pix=40` didn't improve the posterior error fit so much, though it did reduce most of the large errors in flux estimation and generally improved estimation accuracy for most variables.

**Comment by jeff-regier** [comment]
The sky background looks quite a bit less variable for `synthetic` than for `coadd`. I've computed the sample variance for groups of pixel in real images away from light sources before: the sample variance really is pretty close to the mean of those pixels in those cases. (As one would expect with a Poisson rv.) So I'm kind of surprised the backgrounds look different here. Is the background actually more variable for `coadd` than for `synthetic`, or does it have something to do with how it's rendered here?

**Comment by gostevehoward** [comment]
I'm not sure if I recorded this somewhere, but here's the exact query I used for the coadd catalog for 3325/5/110 used here:

```sql
declare @EDGE bigint set @EDGE=dbo.fPhotoFlags('EDGE')
declare @SATURATED bigint set @SATURATED=dbo.fPhotoFlags('SATURATED')
declare @NODEBLEND bigint set @NODEBLEND=dbo.fPhotoFlags('NODEBLEND')
declare @bad_flags bigint set @bad_flags=(@SATURATED|@EDGE|@NODEBLEND)

select *
from (
  select
    objid, rerun, run, camcol, field, flags,
    ra, dec, probpsf,
    psfmag_u, psfmag_g, psfmag_r, psfmag_i, psfmag_z,
    devmag_u, devmag_g, devmag_r, devmag_i, devmag_z,
    expmag_u, expmag_g, expmag_r, expmag_i, expmag_z,
    fracdev_r,
    devab_r, expab_r,
    devphi_r, expphi_r,
    devrad_r, exprad_r
  into coadd_field_catalog
  from stripe82.photoobj
  where
    run in (106, 206) and
    ra between 0.254 and 0.419 and
    dec between 0.407 and 0.633
) as tmp
where
  ((psfmag_i < 22 and probpsf = 1) 
   or (probpsf = 0 and (expmag_i < 22 or devmag_i < 22)))
  and (flags & @bad_flags) = 0
```

It's the same as the one in the [wiki page](https://github.com/jeff-regier/Celeste.jl/wiki/About-SDSS-and-Stripe-82) (currently), but with different ra/dec bounds.
