### ISSUE TITLE
mean and sky-subtracted images for a particular SDSS frame

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#663]
Given a particular SDSS frame/image, generate a new image with the same format and metadata as the SDSS one, but, depending on a command-line argument, where each pixel's value is 1) mean brightness of the variational distribution (in nanomaggies), or 2) sky subtracted brightness (Celeste minus SDSS).

For a particular frame, it's first necessary to load the relevant part of the Celeste catalog, stored in
```
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld
```
The file names of the jld files in that directory indicate what region of the sky they describe.

There's some code [here](https://github.com/jeff-regier/Celeste.jl/blob/fft/src/CelesteEDA.jl#L93-L142) that shows how to render images given variational parameters. It's for an older version of Celeste though (the fft branch), so the syntax would need to modified slightly.

We'd call the script created for this issue with taskfarmer, to run it on every frame of SDSS. We'd upload the renderings to [legacysurvey.org](http://legacysurvey.org/viewer). (issue #288).

**Comment by jeff-regier** [comment]
@gostevehoward Does this issue make sense? Would you work on it when you have time?

**Comment by gostevehoward** [comment]
I think it makes sense. What is a frame, exactly?

**Comment by jeff-regier** [comment]
Let me quote the SDSS glossary so I'm not slightly off:

> Frame: The data stream from a single CCD in a scanline is cut into a series of frames which measure 2048 × 1489 pixels and overlap 10% with the adjacent frame. The frames in the 5 filters for the same part of the sky are called a field.

Basically, frame = `Image`. Or at least there's a 1-1 mapping between SDSS frames them Celeste `Image`s, and they contain mostly (entirely?) the same data. 5 frames per field (in SDSS). 5 images per RCF (in Celeste).

**Comment by gostevehoward** [comment]
I see, so RCF + band specifies a frame, then?

**Comment by jeff-regier** [comment]
Yes, that's it.

**Comment by gostevehoward** [comment]
@jeff-regier So this script should take an RCF and band, e.g., 325/5/110 "r", and then

* download the frame FITS from the SDSS server, e.g., `frame-r-003325-5-0110.fits`
* load the corresponding Celeste catalog(s) from `celeste-*.jld`,
* generate a new FITS containing the same four extensions as the SDSS frame file, where everything is the same except the pixel values in the first extension,
* and generate the mean brightness or sky-subtracted brightness values using the catalog?

In the catalog filenames, what's the difference between `celeste-A-B-C-D.jld` and `celeste-A-B--C--D.jld`? Is `A-B` a RA range and `C-D` a dec range, in the former case?

When you say "sky-subtracted brightness (Celeste minus SDSS)", do you intend mean brightness from the variational distribution minus SDSS sky level? With the output still in nMgy, I assume?

Thanks for the help, want to make sure I get it right.

**Comment by jeff-regier** [comment]
Yes, that all sounds right. It may be better to generate the whole field (all 5 frames) at once for a particular RCF, rather than just one frame. So the user specifies `325 5 110` on the command line but not "r". 

To download the SDSS data, use the makefile in `test/data`. You can just download everything for the field. (Includes all 5 frames, and some other stuff.)

I think there's only the `celeste-A-B-C-D.jld` format. If you see two hyphens in a row, the second one is probably a minus sign. :-) Some of the declinations are below the equator.

**Comment by gostevehoward** [comment]
Got it, thanks :)

**Comment by gostevehoward** [comment]
I'm failing to find catalog files for some sky regions. Here's the `field_extents.fits` row for RCF 3325/5/110:

```
│ Row │ run  │ camcol │ field │ ramin    │ ramax    │ decmin   │ decmax   │
├─────┼──────┼────────┼───────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 3325 │ 0x05   │ 110   │ 0.254468 │ 0.418259 │ 0.407708 │ 0.632983 │
```

This would require the files `celeste-0.2500-0.5000-0.2500-0.5000.jld` and `celeste-0.2500-0.5000-0.5000-0.7500.jld`. I can't find the second:

```
showard@edison05:~> ls /global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-*     
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--0.5000--0.2500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--0.7500--0.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--1.0000--0.7500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--1.2500--1.0000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--1.5000--1.2500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-0.2500-0.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-1.2500-1.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-14.0000-14.2500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-14.2500-14.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-14.5000-14.7500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-14.7500-15.0000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-34.0000-34.2500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-34.2500-34.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-34.5000-34.7500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000-34.7500-35.0000.jld
```

Am I doing something dumb again?

**Comment by jeff-regier** [comment]
The "missing" box may actually be multiple boxes. (The boxes aren't all 0.25 x 0.25.)
```
$ ls $SCRATCH/celeste_sdds_catalog_jld/*celeste-0.[234]*-0.[2345]*-0.[567]*-0.[567]*.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.3750-0.5000-0.6250.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.3750-0.6250-0.7500.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.2500-0.5000--0.7500--0.5000.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.3750-0.5000-0.5000-0.6250.jld
/global/cscratch1/sd/jregier/celeste_sdds_catalog_jld/celeste-0.3750-0.5000-0.6250-0.7500.jld
```

**Comment by gostevehoward** [comment]
Ah ha, thanks.

**Comment by gostevehoward** [comment]
This is coming along (code [here](https://github.com/gostevehoward/Celeste.jl/blob/write_expectations/bin/write_celeste_expectation.jl)), here's a side-by-side of a noiseless expectations image (left) and a true frame (right):

![screenshot from 2017-05-13 18-37-32](https://cloud.githubusercontent.com/assets/1097616/26030569/d568640e-380b-11e7-8365-9b05e6141ef5.png)

There are a lot of these weird bright galaxies in the expectations image with very lower minor-to-major axis ratios. They do seem to be in the catalog: check out this [CSV version](https://docs.google.com/spreadsheets/d/1jWMQsPoUqeojyLM6UVYI6JLFhzfEPZR52-AivtFTvYA/edit?usp=sharing) of the corresponding catalog, where row 404 (highlighted blue in the spreadsheet) seems to correspond to the galaxy under my mouse (in the left window). Half-light radius of 21 and flux of 490.

**Comment by jeff-regier** [comment]
That is weird. It could be that the catalog was generated with an old version of Celeste. Would you mind adding a flag to the script that causes it to regenerates the relevant part of the Celeste catalog rather than uses the (potentially stale) Celeste catalog? Feel free to decline if you're out of time. I believe it's just a matter of calling `one_node_joint_infer` after invoking the makefile in `test/data` enough times to load the SDSS data locally. It'd be generally useful to be able to run your script without having a copy of the Celeste SDSS catalog on hand.

**Comment by gostevehoward** [comment]
No problem, `benchmark/accuracy/run_celeste_on_field.jl` already does that. I'll have to do a little file format finagling but shouldn't be a big deal.

**Comment by gostevehoward** [comment]
Seems to be working reasonably well now:

![screenshot from 2017-05-14 17-24-06](https://cloud.githubusercontent.com/assets/1097616/26039024/28cfc0e2-38ca-11e7-8c01-763edf74d4c2.png)

This is from Celeste initialized with coadd data:
```
Celeste.jl/benchmark/accuracy$ julia write_ground_truth_catalog_csv.jl coadd ../../test/data/coadd_for_3325_5_110.fit
Celeste.jl/benchmark/accuracy$ julia run_celeste_on_field.jl --use-full-initialization output/coadd_for_3325_5_110_f86460183f.csv --run 3325 --camcol 5 --field 110
Celeste.jl/benchmark/accuracy$ julia ../../bin/write_celeste_expectation.jl 3325 5 110 --catalog-dir output [--subtract-sdss]
```

If you wanted Celeste initialized with primary data, substitute these first two commands:
```
Celeste.jl/benchmark/accuracy$ julia sdss_rcf_to_csv.jl --run 3325 --camcol 5 --field 
110
Celeste.jl/benchmark/accuracy$ julia run_celeste_on_field.jl --use-full-initialization
 output/sdss_3325_5_110_primary_df2758e55d.csv --run 3325 --camcol 5 --field 110
```

**Comment by gostevehoward** [comment]
Here is Celeste expectation minus SDSS value:

![screenshot from 2017-05-14 17-49-48](https://cloud.githubusercontent.com/assets/1097616/26039278/d629f098-38cd-11e7-978b-32ab1f419d38.png)

**Comment by jeff-regier** [comment]
Very nice, Steve. That's pretty much what we'd expect the sky-subtracted images to look like.

Would you add documentation to the wiki for this script too,if you haven't already?

**Comment by gostevehoward** [comment]
Documented here: https://github.com/jeff-regier/Celeste.jl/wiki/Rendering-Celeste-posterior-expectations
