### ISSUE TITLE
require FITSIO v"0.11"

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#698]
Once it's tagged, or whatever version of FITSIO it is that gets rid of all the warnings, e.g.,

```
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /home/jeff/.julia/v0.6/FITSIO/test/libcfitsio.jl:58
```

**Comment by giordano** [comment]
Version 0.11 of FITSIO.jl, with all those warnings cleared, has been tagged a few hours ago.  Is it necessary to require the latest version or can we close the ticket?

**Comment by kbarbary** [comment]
Not yet tagged in METADATA, but hopefully will be soon.
