### ISSUE TITLE
incremental compilation broken on Mac

### ISSUE THREAD

**Issue by mrkite92** [jeff-regier/Celeste.jl#721]
Hi Celeste gurus,

Atom: 1.20.1 x64
Electron: 1.6.9
OS: Mac OS X 10.12.6

Stack trace on Atom while using command using Celeste:

Precompiling module Celeste.
WARNING: eval from module Main to Model:    
Expr(:curly, Expr(:., :Core, :Tuple)::Any, Expr(:., :Core, :Float64)::Any, Expr(:., :Core, :Float64)::Any)::Any
  ** incremental compilation may be broken for this module **

ERROR: LoadError: LoadError: LoadError: 
TypeError: SArray: in S, expected S<:Tuple, got Tuple{Int64,Int64,Int64}
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Users/marquett/.julia/v0.6/Celeste/src/bivariate_normals.jl, in expression starting on line 521
while loading /Users/marquett/.julia/v0.6/Celeste/src/Model.jl, in expression starting on line 54
while loading /Users/marquett/.julia/v0.6/Celeste/src/Celeste.jl, in expression starting on line 18

**Comment by giordano** [comment]
The "incremental compilation may be broken for this module" warning is already fixed on master, see #697.  Instead, I have no idea what's causing the error.

**Comment by mrkite92** [comment]
> Le 6 oct. 2017 à 15:07, Mosè Giordano <notifications@github.com> a écrit :
> 
> The "incremental compilation may be broken for this module" warning is already fixed on master, see #697 <https://github.com/jeff-regier/Celeste.jl/issues/697>. Instead, I have no idea what's causing the error.
> 

OK, thanks for immediate answer. Latest master pulled, tests went smoothly until:


ti profile:
prep: 7.983e-06 (7983)
fork: 0.000137581 (387.659 - 339.201)
user: 1.7804e-05 (217.781 - 27.2226)
join: 9.35e-07 (4.334e-06 - 1.619e-06)

signal (11): Segmentation fault: 11
while loading /Users/marquett/.julia/v0.6/Celeste/test/test_infer.jl, in expression starting on line 9
Assertion failed: (uv__has_active_reqs(stream->loop)), function uv__write_callbacks, file /Users/osx/buildbot/slave/package_osx10_9-x64/build/deps/srccache/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/src/unix/stream.c, line 956.

signal (6): Abort trap: 6
while loading /Users/marquett/.julia/v0.6/Celeste/test/test_infer.jl, in expression starting on line 9
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 763281431 (Pool: 763269202; Big: 12229); GC: 1889
===============================[ ERROR: Celeste ]===============================

failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /Users/marquett/.julia/v0.6/Celeste/test/runtests.jl`, ProcessSignaled(6)) [0]

================================================================================
Base.Pkg.Entry.PkgTestError("Celeste had test errors")
 

The directory /Users/osx/ (bold above) seems suspect to me…

Cheers,
JB

**Comment by kbarbary** [comment]
The directory `/Users/osx/...` is just a directory on the machine where libuv was compiled. If you had compiled Julia from source, you'd see a directory on your machine.

Do you know if you're running with julia threads? This seems similar to #720.

**Comment by jeff-regier** [comment]
I tried it on my mac laptop. Installation seems to go smoothly. 

```
Jeffreys-MacBook-Pro:Celeste jeff$ rm -rf ~/.julia
Jeffreys-MacBook-Pro:Celeste jeff$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.clone("https://github.com/jeff-regier/Celeste.jl.git")
INFO: Initializing package repository /Users/jeff/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning Celeste from https://github.com/jeff-regier/Celeste.jl.git
INFO: Computing changes...
INFO: Cloning cache of AxisAlgorithms from https://github.com/timholy/AxisAlgorithms.jl.git
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
...
ar: creating archive libwcs-PIC.a
INFO: Package database updated

julia> Pkg.build("Celeste")
INFO: Building SpecialFunctions
INFO: Building Rmath
...
INFO: Changing Directory to /Users/jeff/.julia/v0.6/Celeste/deps/src/sep-1.0.2

julia> using Celeste
...
```

I'll try the unit tests shortly, once nersc.gov is back up....

**Comment by jeff-regier** [comment]
However, I see the same error message you're reporting on JuliaCIBot here:

https://github.com/JuliaLang/METADATA.jl/pull/11501
https://juliarun-ci.s3.amazonaws.com/d1c4c7ed0a2f23b4abdc4e36632f4107c122a6d1/current_release_of_Celeste_on_julia_0_6.log

This may be an issue with static arrays, that gets fixed in few days (?) by the release of Julia 0.6.1.

**Comment by jeff-regier** [comment]
I don't get any error with the sequence of commands below on a Macbook. I'm using Julia 0.6.1 here---that could have helped. Please reopen the issue if the commands below, with Julia 0.6.1, still lead to an error message.

```
$ rm -rf ~/.julia
$ julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> Pkg.clone("https://github.com/jeff-regier/Celeste.jl.git")
INFO: Initializing package repository /Users/jeff/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning Celeste from https://github.com/jeff-regier/Celeste.jl.git
INFO: Computing changes...
INFO: Cloning cache of AxisAlgorithms from https://github.com/timholy/AxisAlgorithms.jl.git
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
...
julia> Pkg.build("Celeste")
INFO: Building SpecialFunctions
INFO: Building Rmath
INFO: Building Homebrew
Already up-to-date.
INFO: Building Blosc
...
julia> Pkg.test("Celeste")
INFO: Testing Celeste
curl --create-dirs -o 3900/6/269/fpM-003900-u6-0269.fit.gz https://data.sdss.org/sas/dr12/boss/photo/redux/301/3900/objcs/6/fpM-003900-u6-0269.fit.gz
...
Test Summary:                          |
whole accuracy benchmark pipeline runs | No tests
Test Summary:            | Pass  Total
flux <-> mags conversion |    4      4
Test Summary:      | Pass  Total
...
```
