### ISSUE TITLE
banish NLopt from our codebase

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#74]
...and replace it with the new trust-region-based method.

Benefits:
- Fixes the unit tests, which are failing now on Travis-CI because of some random NLopt problem
- Reuses the existing unit tests to validate the new Hessian-based way of optimizing
- I can finish #16 pretty quickly once we can set `D > 2`. The model should work much better once color doesn't misfit the data so badly.
- I can finish #14 pretty quickly once we can set `D > 2`, by making the color model for stars rich enough to represent quasars too. (Effectively "stars" come to represent all point sources.)

**Comment by rgiordan** [comment]
SGTM, but remind me what this has to do with D > 2?  Does that give the NLOpt failure more often for some weird reason?

**Comment by jeff-regier** [comment]
I thought Celeste with NLopt only worked for `D == 2`, where D is the
number of mixture components of the color prior. That was the case back in
February at least. Are all the calls to NLopt now going through the
transform module by default, so that we can use any number of mixture
components (and have mixing weights constrained to sum to 1)?

**Comment by rgiordan** [comment]
Yep, everything goes through transform now.

**Comment by rgiordan** [comment]
It's not quite banished, but with https://github.com/jeff-regier/Celeste.jl/pull/79 I think it's close enough.
