### ISSUE TITLE
rasterized psf

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#87]
Modeling the PSF in Celeste with rasterized "eigenimages" rather than a mixture-of-Gaussians. Use cubic or lanzos interpolation.

Advantages:
- More accurate---and we've heard from Dustin via David that the mixture of Gaussians doesn't  fit well.
- Faster to convert from the existing SDSS PSF format to a rasterized image than to fit a mixture of Gaussians.

At first, use the eigenimages (`RawPSF`) from the SDSS pipeline.  For DECaLS, we'll have to learn these rasterized images ourselves, probably from within the model rather than from eigen decompositions.

**Comment by rgiordan** [comment]
The work for the Hessian will be very similar whether we do it this way or not, so we can investigate this in parallel.

**Comment by jeff-regier** [comment]
We may want to use a discrete 2D FFT for convolving galaxies with a rasterized psf. [This short, applied tutorial](http://www4.ncsu.edu/eos/users/w/white/www/white/ma325/MVlec7.pdf) might teach us just enough about to 2D FFT. Also, Dustin has a note titled ["A method for fast galaxy–PSF convolution"](https://github.com/dstndstn/fft-gal-convolution/blob/master/gal-conv.tex).

**Comment by rgiordan** [comment]
Right now this working in [my other repo](https://github.com/rgiordan/CelesteDev.jl/tree/master/rasterized_psf).  It's about 5x slower than the current ELBO, but there are a lot of obvious improvements that I can make, which I have labeled as issues.  Before merging with `Celeste.jl` I still need to do a lot of testing and validation, though.

**Comment by rgiordan** [comment]
I merged a version of this in https://github.com/jeff-regier/Celeste.jl/pull/419.  I'd prefer to keep this open until I've done more validation.

**Comment by rgiordan** [comment]
The basics of this are done in https://github.com/jeff-regier/Celeste.jl/pull/455 and working on an array of test images.  The specifics that remain to be done have their own issues.
