### ISSUE TITLE
Replace test stamps with images having a non-trivial WCS

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#90]
All the test images in `Synthetic.jl` use either an identity WCS or a symmetric one.  For testing purposes, we should replace them all with an actual asymmetric WCS.

**Comment by jeff-regier** [comment]
We should remove all functions related to stamps, e.g. `load_stamp_catalog`, `load_stamp_blob`, , from the code base at the same time. We're using stamps exclusively in unit tests now, but this leads to tests that aren't testing the code in a realistic setting.

**Comment by jeff-regier** [comment]
This issue would be a good time to start using [FactCheck.jl](https://github.com/JuliaLang/FactCheck.jl) for unit tests, too. It's much more readable than `Base.Test`.
