### ISSUE TITLE
Remove GSL.jl dependency

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#93]
It won't compile easily on NERSC, and it's less accurate than ForwardDiff.jl anyway.

**Comment by rgiordan** [comment]
For an example of how to deal with the `ModelParams` problem, check out the Hessian tests in the `exact_hessian` branch.  I don't recall why I didn't write it as a `convert` method -- maybe I had a hard time figuring out what the right parent type would be for the `ForwardDiff` types.
